window.PDZ_DATA.lessons.push(
  {
    id: 51, module: 4, title: 'Cliente e servidor', time: '50–60 min',
    learn: ['O que é cliente', 'O que é servidor', 'Requisição e resposta', 'Comunicação em rede', 'Front-end e servidor'],
    importance: 'Grande parte das aplicações web funciona por meio da comunicação entre clientes e servidores. Entender esses papéis prepara você para estudar HTTP, APIs e back-end.',
    before: 'Você já criou interfaces no navegador com HTML, CSS e JavaScript. Agora vai entender como essa interface pode conversar com outros sistemas.',
    explanation: 'Cliente e servidor são papéis em uma comunicação. O cliente inicia uma solicitação, chamada requisição. O servidor recebe essa solicitação, processa o que for necessário e devolve uma resposta. Um navegador pode atuar como cliente ao pedir uma página ou dados. Um programa executado em um servidor pode receber pedidos de vários clientes. Cliente não significa necessariamente computador do usuário e servidor não significa necessariamente uma máquina física específica: estamos falando principalmente de papéis desempenhados por softwares em uma comunicação.',
    everyday: 'Pense em uma biblioteca. Você faz um pedido por um livro; a equipe recebe o pedido, localiza o material e entrega uma resposta. A analogia ajuda a visualizar pedido e resposta, embora redes funcionem por regras técnicas próprias.',
    programming: 'Quando um navegador acessa uma página, ele pode enviar uma requisição ao servidor. O servidor responde com o conteúdo ou com dados que o navegador utilizará.',
    code: 'Cliente\n  ↓ requisição\nServidor\n  ↓ processamento\nServidor\n  ↓ resposta\nCliente',
    lineByLine: 'A primeira seta representa a requisição iniciada pelo cliente. O servidor recebe e processa o pedido. A última seta representa a resposta enviada de volta ao cliente.',
    guided: 'Escolha um site que você usa e descreva, em palavras simples, uma ação que provavelmente envolve cliente → servidor → resposta.',
    exercise: 'Explique quem inicia normalmente a requisição em uma comunicação cliente-servidor e o que o servidor faz ao recebê-la.',
    challenge: 'Explique por que cliente e servidor devem ser entendidos como papéis e não apenas como dois tipos fixos de computador.',
    findError: 'Afirmação: “Servidor é sempre um computador enorme em um data center e cliente é sempre um celular.” Corrija.',
    common: 'Confundir servidor com uma única máquina física, achar que o cliente apenas recebe dados e esquecer que a comunicação envolve requisições e respostas.',
    summary: 'O cliente inicia uma requisição. O servidor recebe, processa e devolve uma resposta. Esses termos descrevem papéis na comunicação.',
    task: 'Desenhar um fluxo cliente → requisição → servidor → resposta → cliente e escrever um exemplo de cada etapa.',
    video: '',
    hint1: 'Pense em quem faz o pedido primeiro.',
    hint2: 'Servidor recebe um pedido e devolve alguma resposta.',
    solution: 'O cliente normalmente inicia a requisição. O servidor recebe o pedido, processa a solicitação e devolve uma resposta. Cliente e servidor são papéis que softwares assumem em uma comunicação.'
  },
  {
    id: 52, module: 4, title: 'URL, domínio, IP e porta', time: '50–60 min',
    learn: ['O que é uma URL', 'Scheme, host, path e query', 'Diferença entre domínio e IP', 'O que é uma porta'],
    importance: 'URLs aparecem em navegadores, APIs e ferramentas de desenvolvimento. Saber ler seus componentes ajuda a entender para onde uma requisição está indo.',
    before: 'Você já entende que um cliente pode enviar uma requisição para um servidor.',
    explanation: 'URL é um endereço que indica como e onde acessar um recurso. Em https://exemplo.com:443/cursos?modulo=4, https é o scheme, que indica o esquema usado; exemplo.com é o host e, nesse caso, um domínio; 443 é a porta explícita; /cursos é o path; e modulo=4 é a query. Um domínio é um nome legível que pode ser resolvido para um endereço IP. IP identifica um endereço de rede. Porta ajuda a identificar o serviço ou processo de rede no host. Nem toda URL mostra a porta porque alguns esquemas usam portas padrão que podem ser omitidas.',
    everyday: 'Um endereço postal tem partes diferentes, como rua, número e complemento. Uma URL também possui partes com funções próprias, embora a comparação seja apenas uma analogia.',
    programming: 'Ao consumir uma API, você poderá encontrar uma URL como https://api.exemplo.com/alunos?turma=5. O host indica o destino, /alunos o caminho do recurso e turma=5 um parâmetro de consulta.',
    code: 'https://exemplo.com:443/cursos?modulo=4\n\nhttps        → scheme\nexemplo.com  → host/domínio\n443          → porta\n/cursos      → path\nmodulo=4     → query',
    lineByLine: 'Scheme aparece antes de ://. O host vem depois. A porta pode aparecer após dois-pontos. O path identifica o caminho do recurso. A query vem após ? e carrega parâmetros.',
    guided: 'Pegue três URLs conhecidas e tente localizar scheme, host, path e query quando existirem.',
    exercise: 'Separe a URL https://site.exemplo.com:443/produtos?categoria=livros em scheme, host, porta, path e query.',
    challenge: 'Explique por que domínio e endereço IP não devem ser tratados como sinônimos.',
    findError: 'Afirmação: “O domínio exemplo.com é o próprio endereço IP do servidor.” Corrija.',
    common: 'Confundir domínio com URL inteira, chamar path de domínio e acreditar que toda URL precisa mostrar uma porta.',
    summary: 'Uma URL pode conter scheme, host, porta, path e query. Domínio é um nome; IP é um endereço de rede; porta identifica um serviço no host.',
    task: 'Analisar cinco URLs e identificar seus componentes em uma tabela de estudos.',
    video: '',
    hint1: 'Tudo antes de :// indica o scheme.',
    hint2: 'A query começa depois do caractere ?.',
    solution: 'scheme: https; host: site.exemplo.com; porta: 443; path: /produtos; query: categoria=livros.'
  },
  {
    id: 53, module: 4, title: 'Introdução ao HTTP', time: '50–60 min',
    learn: ['O que é protocolo', 'O que é HTTP', 'Mensagens HTTP', 'Método e recurso em nível introdutório', 'Ideia inicial de comunicação stateless'],
    importance: 'HTTP é a base da comunicação de muitas aplicações web e APIs. Entendê-lo ajuda a enxergar o que acontece por trás do navegador.',
    before: 'Você já sabe quem são cliente e servidor e consegue decompor uma URL.',
    explanation: 'Um protocolo é um conjunto de regras para comunicação. HTTP significa Hypertext Transfer Protocol e é um protocolo da camada de aplicação usado para troca de mensagens na Web. O cliente envia uma mensagem de requisição e o servidor devolve uma mensagem de resposta. Uma requisição indica, entre outras coisas, o método e o recurso desejado. HTTP é frequentemente descrito como stateless: cada requisição deve trazer as informações necessárias para ser entendida no contexto do protocolo; aplicações podem criar sessões ou outros mecanismos acima dele para manter estado entre interações.',
    everyday: 'Em uma conversa formal existe uma estrutura esperada para que as mensagens sejam compreendidas. Protocolos de rede também definem regras, mas de maneira técnica e padronizada.',
    programming: 'Ao abrir /alunos, o navegador ou outro cliente pode enviar uma mensagem HTTP solicitando esse recurso ao servidor.',
    code: 'Cliente → mensagem HTTP de requisição → Servidor\nCliente ← mensagem HTTP de resposta  ← Servidor',
    lineByLine: 'A primeira mensagem vai do cliente ao servidor e pede algo. A segunda volta do servidor ao cliente com o resultado da solicitação.',
    guided: 'Explique em uma frase o que significa protocolo e em outra frase o papel do HTTP.',
    exercise: 'Complete: HTTP é um ______ usado para troca de ______ entre cliente e servidor na Web.',
    challenge: 'Explique por que dizer apenas “HTTP é a internet” está incorreto.',
    findError: 'Afirmação: “HTTP é um navegador usado para abrir sites.” Corrija.',
    common: 'Confundir HTTP com navegador, internet ou servidor e tentar decorar métodos antes de entender o fluxo de mensagens.',
    summary: 'HTTP é um protocolo de aplicação para troca de mensagens entre clientes e servidores. Requisições pedem recursos e respostas devolvem resultados.',
    task: 'Criar um mapa conceitual ligando protocolo, HTTP, cliente, servidor, requisição e resposta.',
    video: '',
    hint1: 'HTTP define regras de comunicação.',
    hint2: 'O que viaja entre cliente e servidor são mensagens.',
    solution: 'HTTP é um protocolo usado para troca de mensagens entre clientes e servidores na Web.'
  },
  {
    id: 54, module: 4, title: 'Request e Response', time: '50–60 min',
    learn: ['Request e response', 'Headers', 'Body', 'Status code', 'Metadados versus conteúdo'],
    importance: 'Ao trabalhar com APIs, você precisará interpretar o que foi enviado na requisição e o que voltou na resposta.',
    before: 'Você já sabe que HTTP organiza a troca de mensagens entre cliente e servidor.',
    explanation: 'Request é a requisição enviada pelo cliente. Response é a resposta enviada pelo servidor. Headers transportam metadados sobre a mensagem, por exemplo o tipo de conteúdo aceito ou retornado. O body, quando existe, carrega o conteúdo da mensagem. A resposta também possui um status code que indica o resultado em nível HTTP. Nem toda requisição ou resposta precisa ter body. Por exemplo, uma requisição GET pode não ter body e uma resposta 204, por definição, não traz conteúdo no corpo.',
    everyday: 'Pense em um formulário de solicitação: há informações sobre o pedido e pode haver conteúdo anexado. A resposta também pode trazer um resultado e um código que resume a situação.',
    programming: 'Uma API pode receber GET /alunos e responder com status 200, header Content-Type: application/json e um body com dados em JSON.',
    code: 'REQUEST\nGET /alunos HTTP/1.1\nHost: exemplo.com\nAccept: application/json\n\nRESPONSE\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n[{"id": 1, "nome": "Ana"}]',
    lineByLine: 'GET /alunos identifica o método e o caminho do recurso. Host indica o host alvo. Accept informa um tipo de conteúdo aceito. Na resposta, 200 OK é o status. Content-Type descreve o formato do corpo. O JSON aparece no body.',
    guided: 'Copie o exemplo e marque visualmente quais linhas pertencem a request, response, headers, status e body.',
    exercise: 'No exemplo da aula, identifique o status code, um header da resposta e o body.',
    challenge: 'Explique por que não é correto afirmar que toda mensagem HTTP possui body.',
    findError: 'Afirmação: “Header e body são a mesma parte da mensagem HTTP.” Corrija.',
    common: 'Confundir header com body, achar que status code existe na requisição da mesma forma que na resposta e acreditar que body é obrigatório em todas as mensagens.',
    summary: 'Request é o pedido do cliente; response é a resposta do servidor. Headers carregam metadados, body pode carregar conteúdo e status code resume o resultado HTTP.',
    task: 'Criar duas caixas no caderno: uma para request e outra para response, identificando headers, body e status quando aplicável.',
    video: '',
    hint1: '200 OK aparece na primeira linha da resposta.',
    hint2: 'Content-Type é um header; o array JSON é o body.',
    solution: 'Status code: 200. Header da resposta: Content-Type: application/json. Body: [{"id": 1, "nome": "Ana"}].'
  },
  {
    id: 55, module: 4, title: 'HTTP versus HTTPS', time: '50–60 min',
    learn: ['Diferença entre HTTP e HTTPS', 'O papel do TLS', 'Criptografia em trânsito', 'Certificado em nível conceitual', 'Por que HTTPS não garante segurança total'],
    importance: 'Quase toda aplicação web moderna deve proteger a comunicação em trânsito. Entender o limite dessa proteção evita uma falsa sensação de segurança.',
    before: 'Você já entende requisições, respostas, headers, body e status codes em nível introdutório.',
    explanation: 'HTTPS é HTTP protegido por TLS durante o transporte. TLS cria um canal criptografado entre as partes, ajuda a proteger a confidencialidade e a integridade dos dados em trânsito e usa certificados para apoiar a autenticação do servidor. Isso reduz o risco de alguém no caminho ler ou alterar facilmente a comunicação. Porém HTTPS não torna toda a aplicação segura: um sistema ainda pode possuir vulnerabilidades, configurações ruins, senhas fracas ou falhas de autorização.',
    everyday: 'Enviar uma mensagem dentro de um envelope lacrado protege melhor o conteúdo durante o transporte, mas não garante que tudo na origem e no destino esteja correto ou seguro.',
    programming: 'Uma aplicação acessada por https:// usa HTTP sobre uma conexão protegida por TLS. O código da aplicação continua precisando de práticas de segurança próprias.',
    code: 'HTTP  → dados trafegam sem a proteção de TLS\nHTTPS → HTTP + proteção de TLS em trânsito\n\nHTTPS ≠ “aplicação totalmente segura”',
    lineByLine: 'A primeira linha mostra a ausência de TLS no HTTP simples. A segunda representa HTTP protegido por TLS. A terceira lembra que segurança da conexão é apenas uma parte da segurança do sistema.',
    guided: 'Explique com suas palavras o que TLS protege e cite uma falha que HTTPS sozinho não consegue corrigir.',
    exercise: 'Complete: HTTPS é ______ protegido por ______ durante o transporte dos dados.',
    challenge: 'Explique por que um site pode usar HTTPS e ainda assim ter uma falha grave de segurança na aplicação.',
    findError: 'Afirmação: “Se aparece um cadeado HTTPS, então o site inteiro é confiável e não pode ter vulnerabilidades.” Corrija.',
    common: 'Tratar HTTPS como sinônimo de sistema seguro, confundir criptografia em trânsito com proteção de dados em todos os lugares e ignorar o papel do certificado.',
    summary: 'HTTPS é HTTP protegido por TLS. Ele protege a comunicação em trânsito, mas não substitui as demais práticas de segurança de uma aplicação.',
    task: 'Criar uma comparação HTTP × HTTPS com três diferenças e escrever duas coisas que HTTPS não garante.',
    video: '',
    hint1: 'A primeira lacuna é o protocolo já estudado.',
    hint2: 'A segunda lacuna é a tecnologia que protege o transporte.',
    solution: 'HTTPS é HTTP protegido por TLS durante o transporte dos dados.'
  }
);