window.PDZ_DATA.lessons.push(
  {
    id: 86, module: 8, title: 'Por que programadores precisam entender redes', time: '50–60 min',
    learn: ['rede', 'comunicação entre máquinas', 'cliente e servidor', 'API pela rede', 'deploy', 'conectividade'],
    importance: 'Front-end, back-end, banco de dados e APIs normalmente precisam se comunicar por uma rede. Entender o básico ajuda a desenvolver e diagnosticar aplicações.',
    before: 'Você já estudou cliente/servidor, HTTP, APIs, FastAPI, banco de dados e uma aplicação full stack.',
    explanation: 'Uma rede permite que dispositivos e programas troquem dados. Em uma aplicação web, o navegador pode enviar uma requisição a um back-end, que pode consultar um banco de dados e responder. Para quem programa, redes ajudam a entender por que localhost funciona, por que um servidor pode não estar acessível e como aplicações se conectam.',
    everyday: 'Pense em uma entrega: alguém faz um pedido, há um endereço de destino, um caminho e uma resposta. Redes também precisam identificar origem, destino e forma de transportar dados.',
    programming: 'Desenhe o caminho: navegador → rede → API FastAPI → PostgreSQL → resposta.',
    code: 'Navegador\n   ↓ requisição HTTP\nRede\n   ↓\nAPI FastAPI\n   ↓ consulta\nPostgreSQL\n   ↑ dados\nAPI FastAPI\n   ↑ resposta HTTP\nNavegador',
    lineByLine: 'O navegador atua como cliente. A requisição atravessa a rede. A API recebe e processa. O banco persiste dados. A resposta volta ao cliente.',
    guided: 'Liste três situações em que um problema de rede pode parecer um problema de código.',
    exercise: 'Explique com suas palavras por que uma API hospedada em outro computador depende de rede para ser usada pelo front-end.',
    challenge: 'Diferencie erro de lógica da aplicação e falha de conectividade usando um exemplo simples.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se o código está correto, a rede nunca pode impedir o aplicativo de funcionar.”',
    common: 'Pensar que todo erro ao acessar uma API é obrigatoriamente erro no código da API.',
    summary: 'Redes conectam sistemas. Para programadores, entender conectividade ajuda a construir, integrar e diagnosticar aplicações.',
    task: 'Desenhar a arquitetura de uma aplicação simples mostrando cliente, rede, servidor e banco de dados.',
    video: '',
    hint1: 'Pense no caminho que os dados percorrem.',
    hint2: 'Separe aplicação, rede e armazenamento.',
    solution: 'Exemplo: navegador → Internet/rede local → servidor FastAPI → PostgreSQL → servidor → navegador. Um problema pode ocorrer em qualquer etapa.'
  },
  {
    id: 87, module: 8, title: 'Modelo OSI', time: '50–60 min',
    learn: ['modelo OSI', '7 camadas', 'Física', 'Enlace', 'Rede', 'Transporte', 'Sessão', 'Apresentação', 'Aplicação'],
    importance: 'O modelo OSI organiza funções de comunicação em camadas e ajuda a raciocinar sobre onde um problema de rede pode estar.',
    before: 'Você sabe por que aplicações precisam se comunicar por redes.',
    explanation: 'OSI é um modelo conceitual de referência com sete camadas: Física, Enlace, Rede, Transporte, Sessão, Apresentação e Aplicação. Ele ajuda a separar responsabilidades. Não significa que o computador execute literalmente sete programas separados em cada comunicação.',
    everyday: 'É como organizar uma viagem em etapas: estrada, veículo, rota, regras de transporte e serviço usado pelo passageiro. As etapas ajudam a localizar problemas.',
    programming: 'Associe HTTP à camada de Aplicação e IP à camada de Rede em uma visão conceitual.',
    code: '7 Aplicação\n6 Apresentação\n5 Sessão\n4 Transporte\n3 Rede\n2 Enlace\n1 Física',
    lineByLine: 'As camadas inferiores lidam mais diretamente com transmissão e acesso ao meio; as superiores representam funções cada vez mais próximas das aplicações. O modelo é uma referência para estudo e diagnóstico.',
    guided: 'Memorize a ordem das sete camadas e escreva uma frase curta sobre a função geral de cada uma.',
    exercise: 'Qual camada do modelo OSI está associada ao roteamento IP em uma visão introdutória?',
    challenge: 'Explique por que o modelo OSI é útil mesmo que a Internet real não siga esse modelo de forma literal em todos os detalhes.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“O modelo OSI é formado por sete programas obrigatórios que todo computador executa separadamente.”',
    common: 'Tratar as camadas como softwares físicos independentes ou imaginar que OSI descreve exatamente toda implementação real.',
    summary: 'OSI é um modelo conceitual de sete camadas usado para organizar e compreender funções de rede.',
    task: 'Criar uma tabela com as sete camadas e uma explicação de uma linha para cada uma.',
    video: 'https://www.youtube.com/watch?v=bmgvIlvVAlc',
    hint1: 'IP é associado à camada 3.',
    hint2: 'A camada 3 é chamada Rede.',
    solution: 'Camada 3 — Rede.'
  },
  {
    id: 88, module: 8, title: 'TCP/IP e relação com o OSI', time: '50–60 min',
    learn: ['modelo TCP/IP', 'Acesso à Rede', 'Internet', 'Transporte', 'Aplicação', 'comparação com OSI'],
    importance: 'TCP/IP está mais diretamente ligado à arquitetura usada na Internet. Compará-lo ao OSI ajuda a organizar o que você já aprendeu.',
    before: 'Você conhece as sete camadas do modelo OSI.',
    explanation: 'O modelo TCP/IP costuma ser apresentado com quatro camadas: Acesso à Rede, Internet, Transporte e Aplicação. A relação com OSI é aproximada, não uma equivalência perfeita. Protocolos como IP ficam na camada Internet; TCP e UDP na camada Transporte; HTTP e DNS aparecem na camada de Aplicação.',
    everyday: 'Duas classificações podem organizar o mesmo assunto de maneiras diferentes. Uma pode ter mais categorias e outra agrupar várias categorias juntas.',
    programming: 'Classifique HTTP, TCP e IP nas camadas do modelo TCP/IP.',
    code: 'Aplicação: HTTP, DNS\nTransporte: TCP, UDP\nInternet: IP, ICMP\nAcesso à Rede: tecnologias de acesso ao meio',
    lineByLine: 'HTTP e DNS atendem aplicações. TCP e UDP transportam dados entre processos. IP participa do endereçamento e encaminhamento. Acesso à Rede cobre a ligação com a rede física/local.',
    guided: 'Monte uma comparação simples entre 7 camadas do OSI e 4 camadas do TCP/IP.',
    exercise: 'Em qual camada TCP/IP ficam TCP e UDP?',
    challenge: 'Explique por que dizer “camada X do OSI é exatamente igual à camada Y do TCP/IP” pode ser uma simplificação excessiva.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“OSI e TCP/IP são exatamente o mesmo modelo, apenas com nomes diferentes.”',
    common: 'Forçar um mapeamento perfeito entre modelos diferentes.',
    summary: 'TCP/IP organiza a comunicação em quatro camadas. A comparação com OSI é útil, mas aproximada.',
    task: 'Criar um quadro comparativo OSI × TCP/IP com exemplos de protocolos.',
    video: 'https://www.youtube.com/watch?v=c5vfwNBbl4g',
    hint1: 'TCP e UDP são protocolos de transporte.',
    hint2: 'A camada se chama Transporte.',
    solution: 'TCP e UDP ficam na camada de Transporte do modelo TCP/IP.'
  },
  {
    id: 89, module: 8, title: 'IPv4 e IPv6', time: '50–60 min',
    learn: ['endereço IP', 'IPv4', '32 bits', 'IPv6', '128 bits', 'decimal pontuado', 'hexadecimal'],
    importance: 'Endereços IP identificam interfaces em redes IP e são fundamentais para que dados sejam encaminhados até seus destinos.',
    before: 'Você conhece as camadas de Rede/Internet nos modelos estudados.',
    explanation: 'IPv4 usa endereços de 32 bits, normalmente escritos em quatro números decimais separados por pontos, como 192.0.2.10. IPv6 usa 128 bits e costuma ser representado em hexadecimal, como 2001:db8::10. IPv6 amplia enormemente o espaço de endereços. Um endereço IP não é a mesma coisa que um nome de domínio.',
    everyday: 'Um nome de contato e um número de telefone identificam a mesma pessoa de formas diferentes. Domínio e IP também têm papéis diferentes e podem ser relacionados por DNS.',
    programming: 'Identifique se os exemplos apresentados estão em formato IPv4 ou IPv6.',
    code: 'IPv4: 192.0.2.10\nIPv6: 2001:db8::10',
    lineByLine: 'IPv4 aparece em quatro grupos decimais. IPv6 usa grupos hexadecimais separados por dois-pontos e pode usar abreviações válidas como ::.',
    guided: 'Compare quantidade de bits, aparência e motivo de existência de IPv4 e IPv6.',
    exercise: 'Quantos bits possui um endereço IPv4? E um IPv6?',
    challenge: 'Explique por que um domínio e um endereço IP não devem ser tratados como sinônimos.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“IPv6 usa 64 bits e substitui nomes de domínio.”',
    common: 'Confundir domínio com IP e memorizar tamanhos incorretos.',
    summary: 'IPv4 usa 32 bits; IPv6 usa 128 bits. IP e domínio são conceitos diferentes.',
    task: 'Criar uma comparação curta entre IPv4 e IPv6 com exemplos.',
    video: '',
    hint1: 'IPv4 é o menor dos dois.',
    hint2: 'Os tamanhos são 32 e 128 bits.',
    solution: 'IPv4: 32 bits. IPv6: 128 bits.'
  },
  {
    id: 90, module: 8, title: 'IP público, privado, localhost, gateway e NAT', time: '50–60 min',
    learn: ['IP público', 'IP privado', 'faixas privadas', 'localhost', 'gateway', 'NAT'],
    importance: 'Esses conceitos explicam por que um serviço pode funcionar apenas no seu computador, na rede local ou estar disponível pela Internet.',
    before: 'Você sabe o que são IPv4 e IPv6.',
    explanation: 'IPs privados IPv4 são usados em redes internas. As faixas privadas são 10.0.0.0/8, 172.16.0.0/12 e 192.168.0.0/16. Localhost aponta para a própria máquina: 127.0.0.1 em IPv4 e ::1 em IPv6. O gateway é o equipamento ou rota usada para alcançar outras redes. NAT traduz endereços entre contextos de rede, frequentemente permitindo que vários dispositivos privados compartilhem conectividade externa. NAT não é sinônimo de firewall.',
    everyday: 'Pense em um prédio: apartamentos têm números internos, enquanto o prédio tem um endereço externo. A portaria encaminha o que entra e sai, mas isso não significa que ela seja automaticamente um sistema completo de segurança.',
    programming: 'Explique por que uma API ouvindo apenas em 127.0.0.1 normalmente não fica acessível de outro computador da rede.',
    code: 'Privados IPv4:\n10.0.0.0/8\n172.16.0.0/12\n192.168.0.0/16\n\nLocalhost:\n127.0.0.1\n::1',
    lineByLine: 'As três primeiras faixas são reservadas para uso privado em IPv4. 127.0.0.1 e ::1 representam loopback/localhost e apontam para a própria máquina.',
    guided: 'Identifique em exemplos quais endereços pertencem às faixas privadas e qual representa localhost.',
    exercise: 'O endereço 192.168.1.25 é público ou privado? E 127.0.0.1 representa o quê?',
    challenge: 'Explique por que NAT e firewall não são a mesma coisa.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“NAT é um firewall e sempre protege completamente uma rede.”',
    common: 'Confundir IP privado com localhost e tratar NAT como sinônimo de firewall.',
    summary: 'IP público e privado têm contextos distintos; localhost representa a própria máquina; gateway conecta a outras redes; NAT traduz endereços e não é firewall.',
    task: 'Mapear sua compreensão de máquina local → rede privada → gateway/NAT → Internet sem registrar dados sensíveis reais da sua rede.',
    video: '',
    hint1: '192.168.0.0/16 é uma das faixas privadas.',
    hint2: '127.0.0.1 é loopback.',
    solution: '192.168.1.25 é privado. 127.0.0.1 representa localhost/loopback IPv4.'
  }
);