window.PDZ_DATA.lessons.push(
  {
    id: 56, module: 4, title: 'O que é uma API', time: '50–60 min',
    learn: ['Interface', 'API', 'Contrato', 'Cliente consumidor', 'Servidor/provedor', 'Endpoint'],
    importance: 'APIs permitem que sistemas diferentes troquem dados e funcionalidades de forma previsível.',
    before: 'Você já entende cliente, servidor, requisição, resposta e HTTP.',
    explanation: 'API significa Application Programming Interface. Uma API define uma forma de um software conversar com outro. Ela funciona como um contrato: descreve quais operações existem, quais dados podem ser enviados e quais respostas são esperadas. O cliente consumidor faz a requisição; o servidor ou provedor oferece a funcionalidade. Endpoint é um ponto específico de acesso da API, normalmente associado a uma URL e a uma operação.',
    everyday: 'Pense em um cardápio: ele apresenta opções e regras de pedido sem exigir que o cliente entre na cozinha. A API cumpre papel semelhante entre softwares.',
    programming: 'Uma API de estudantes poderia oferecer um endpoint como /alunos para listar ou cadastrar estudantes, dependendo do método HTTP usado.',
    code: 'GET /alunos\n\nResposta conceitual:\n[{"id": 1, "nome": "Ana"}]',
    lineByLine: 'GET indica a intenção da requisição. /alunos é o endpoint relacionado ao recurso alunos. A resposta mostra uma representação em JSON.',
    guided: 'Imagine um aplicativo escolar e escreva três endpoints que poderiam existir, como /alunos, /turmas e /cursos.',
    exercise: 'Explique com suas palavras o que são API, contrato e endpoint.',
    challenge: 'Descreva quem seria cliente e quem seria provedor em um aplicativo que consulta previsão do tempo por uma API.',
    findError: 'Afirmação: “API é sempre um banco de dados exposto na internet.” Corrija.',
    common: 'Confundir API com banco de dados, servidor ou linguagem de programação.',
    summary: 'API é uma interface entre softwares. Ela estabelece um contrato de comunicação e expõe pontos de acesso chamados endpoints.',
    task: 'Desenhar um esquema Cliente → API → Servidor e criar três endpoints conceituais.',
    video: '',
    hint1: 'Pense na API como uma forma organizada de pedir dados ou ações.',
    hint2: 'Endpoint é um ponto específico de acesso, não a API inteira.',
    solution: 'API é uma interface que define como softwares podem se comunicar. O contrato descreve operações e formatos esperados. Endpoint é um ponto específico da API usado para acessar um recurso ou funcionalidade.'
  },
  {
    id: 57, module: 4, title: 'REST e recursos', time: '50–60 min',
    learn: ['REST', 'Recurso', 'Representação', 'Endpoint', 'Convenções de URLs', 'Estilo arquitetural'],
    importance: 'REST organiza APIs em torno de recursos e convenções que tornam a comunicação mais previsível.',
    before: 'Você já sabe o que é API e endpoint.',
    explanation: 'REST é um estilo arquitetural, não um protocolo. Em APIs que seguem princípios REST, costuma-se organizar URLs em torno de recursos, como alunos, cursos ou tarefas. Recurso é a entidade conceitual; representação é a forma como seus dados são enviados, por exemplo em JSON. URLs tendem a usar substantivos para representar recursos, enquanto a ação esperada é expressa principalmente pelo método HTTP.',
    everyday: 'Em vez de criar uma URL diferente para cada ação, você pode pensar no recurso “livros” e usar formas padronizadas de consultar ou alterar esse recurso.',
    programming: 'Exemplos de recursos: /alunos, /alunos/10, /tarefas/3. O mesmo recurso pode responder de maneiras diferentes conforme o método HTTP.',
    code: 'GET /alunos\nGET /alunos/10\nPOST /alunos',
    lineByLine: '/alunos representa a coleção. /alunos/10 representa um item específico. O método HTTP informa a semântica esperada da operação.',
    guided: 'Transforme as ideias “listar cursos”, “ver curso 5” e “criar curso” em combinações de método e URL.',
    exercise: 'Explique a diferença entre recurso e representação.',
    challenge: 'Explique por que REST não deve ser descrito como um protocolo.',
    findError: 'Afirmação: “REST substitui o HTTP e define um novo protocolo de rede.” Corrija.',
    common: 'Tratar REST como protocolo ou colocar verbos em todas as URLs sem necessidade.',
    summary: 'REST é um estilo arquitetural. APIs REST costumam modelar recursos e usar convenções de URL combinadas com métodos HTTP.',
    task: 'Criar uma pequena tabela conceitual com os recursos alunos, cursos e tarefas e exemplos de endpoints.',
    video: '',
    hint1: 'Recurso é a coisa; representação é como seus dados aparecem.',
    hint2: 'HTTP continua sendo o protocolo usado na comunicação.',
    solution: 'Recurso é a entidade conceitual, como um aluno. Representação é a forma dos dados enviados, como JSON. REST é um estilo arquitetural que pode usar HTTP, não um protocolo separado.'
  },
  {
    id: 58, module: 4, title: 'Métodos HTTP', time: '50–60 min',
    learn: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'Semântica esperada'],
    importance: 'Métodos HTTP comunicam a intenção da requisição e ajudam cliente e servidor a seguir convenções claras.',
    before: 'Você já conhece HTTP, APIs, endpoints e recursos REST.',
    explanation: 'GET é usado para obter uma representação. POST costuma criar um novo recurso ou acionar processamento. PUT normalmente substitui a representação de um recurso de forma completa. PATCH altera parcialmente. DELETE solicita remoção. Essas são semânticas esperadas de HTTP; o método não obriga uma operação específica de banco de dados. Um servidor pode gerar dados dinamicamente, acessar arquivos ou executar outras lógicas.',
    everyday: 'Consultar uma ficha lembra GET; cadastrar uma nova lembra POST; substituir todos os dados lembra PUT; alterar apenas o telefone lembra PATCH; remover um cadastro lembra DELETE.',
    programming: 'Uma API de tarefas pode usar GET /tarefas, POST /tarefas, PATCH /tarefas/3 e DELETE /tarefas/3.',
    code: 'GET /tarefas\nPOST /tarefas\nPUT /tarefas/3\nPATCH /tarefas/3\nDELETE /tarefas/3',
    lineByLine: 'Cada linha usa um método HTTP sobre um recurso. O método comunica a intenção esperada; a URL identifica a coleção ou um item específico.',
    guided: 'Associe os métodos adequados às ações listar tarefas, criar tarefa, substituir tarefa, alterar apenas status e excluir tarefa.',
    exercise: 'Explique a diferença entre PUT e PATCH.',
    challenge: 'Explique por que não é correto dizer que POST significa obrigatoriamente INSERT no banco.',
    findError: 'Afirmação: “DELETE sempre executa DELETE SQL.” Corrija.',
    common: 'Confundir método HTTP com comando SQL e tratar PUT e PATCH como sinônimos absolutos.',
    summary: 'GET, POST, PUT, PATCH e DELETE comunicam intenções. Eles não determinam obrigatoriamente como o servidor implementa a operação internamente.',
    task: 'Criar cinco exemplos de requisições para uma API de biblioteca, uma para cada método estudado.',
    video: '',
    hint1: 'PATCH é adequado para alteração parcial.',
    hint2: 'O servidor decide sua implementação interna.',
    solution: 'PUT normalmente representa substituição completa da representação de um recurso; PATCH altera parte dela. Métodos HTTP descrevem a semântica da requisição, não comandos obrigatórios de banco.'
  },
  {
    id: 59, module: 4, title: 'JSON e códigos de status', time: '50–60 min',
    learn: ['JSON', 'Python dict ≠ objeto JavaScript ≠ JSON', '200, 201 e 204', '400, 401, 403, 404 e 422', '500'],
    importance: 'APIs precisam de formatos previsíveis para dados e sinais claros sobre o resultado de cada requisição.',
    before: 'Você já estudou JSON em Python e agora vai relacioná-lo ao uso em APIs.',
    explanation: 'JSON é um formato textual de intercâmbio de dados. Um dicionário Python e um objeto JavaScript são estruturas das respectivas linguagens; JSON é texto em um formato próprio. Entre os status comuns: 200 indica sucesso genérico; 201 indica criação bem-sucedida; 204 indica sucesso sem conteúdo no corpo; 400 indica requisição inválida em sentido geral; 401 indica que autenticação é necessária ou inválida; 403 indica acesso proibido apesar de a identidade ou contexto poder ser conhecido; 404 indica recurso não encontrado; 422 costuma indicar conteúdo sintaticamente compreensível mas semanticamente inválido para processamento; 500 indica erro interno do servidor.',
    everyday: 'O status funciona como um resumo rápido do resultado; o corpo pode trazer detalhes adicionais quando apropriado.',
    programming: 'POST /alunos pode responder 201 com o aluno criado. DELETE /alunos/10 pode responder 204 sem body. GET de um aluno inexistente pode responder 404.',
    code: 'HTTP/1.1 201 Created\nContent-Type: application/json\n\n{"id": 2, "nome": "Bia"}',
    lineByLine: '201 Created informa o resultado. Content-Type descreve o formato do corpo. A última linha é um texto JSON válido representando o recurso criado.',
    guided: 'Associe um status plausível aos casos: consulta bem-sucedida, criação, exclusão sem retorno, não encontrado e falha interna.',
    exercise: 'Explique a diferença entre objeto JavaScript e JSON e entre 401 e 403.',
    challenge: 'Por que uma resposta 204 não deve depender de um corpo para comunicar o resultado?',
    findError: 'Afirmação: “JSON é exatamente a mesma coisa que um objeto JavaScript.” Corrija.',
    common: 'Confundir JSON com estruturas da linguagem e usar qualquer status de erro sem entender seu significado.',
    summary: 'JSON é formato textual. Status HTTP comunicam o resultado da requisição e devem ser escolhidos de acordo com a semântica da resposta.',
    task: 'Montar um quadro com os status 200, 201, 204, 400, 401, 403, 404, 422 e 500 e um exemplo para cada.',
    video: '',
    hint1: 'JSON é texto; objeto JavaScript é uma estrutura em memória.',
    hint2: '401 se relaciona a autenticação; 403, à proibição de acesso.',
    solution: 'JSON é um formato textual. Um objeto JavaScript é uma estrutura da linguagem. 401 indica ausência ou falha de autenticação; 403 indica que a operação não é permitida naquele contexto.'
  },
  {
    id: 60, module: 4, title: 'Fetch e consumo de API', time: '50–60 min',
    learn: ['fetch()', 'Promise', 'async e await', 'response.ok', 'response.json()', 'Tratamento básico de erros'],
    importance: 'O front-end usa requisições para buscar ou enviar dados a APIs. fetch() é uma API do navegador muito usada para isso.',
    before: 'Você já conhece JavaScript, HTTP, APIs, métodos, JSON e códigos de status.',
    explanation: 'fetch() inicia uma requisição HTTP e retorna uma Promise, que representa um resultado que pode chegar depois. async permite declarar uma função assíncrona e await espera a resolução de uma Promise dentro dela. A resposta possui propriedades como ok e status. response.ok é true para status na faixa de sucesso 200–299. response.json() também é assíncrono e interpreta o corpo JSON. Importante: fetch() não rejeita a Promise apenas porque o servidor respondeu 404 ou 500; por isso o código deve verificar response.ok ou response.status. Erros de rede podem rejeitar a Promise e ser tratados com try/catch.',
    everyday: 'Você faz um pedido e continua esperando a resposta. A Promise representa esse resultado futuro; quando ele chega, o código pode prosseguir.',
    programming: 'Vamos consumir um endpoint conceitual /alunos e tratar respostas HTTP e erros de rede.',
    code: 'async function carregarAlunos() {\n  try {\n    const response = await fetch("/alunos");\n\n    if (!response.ok) {\n      throw new Error(`HTTP ${response.status}`);\n    }\n\n    const alunos = await response.json();\n    console.log(alunos);\n  } catch (erro) {\n    console.error("Falha ao carregar:", erro);\n  }\n}',
    lineByLine: 'async habilita await na função. fetch inicia a requisição. await espera a resposta. response.ok é verificado porque 4xx e 5xx não causam rejeição automática do fetch. response.json() interpreta o JSON. catch recebe erros lançados pelo código ou falhas de rede.',
    guided: 'Digite o exemplo e identifique em qual linha ocorre a requisição, a validação do status e a conversão do JSON.',
    exercise: 'Explique por que verificar apenas try/catch não basta para tratar respostas HTTP 404 e 500 com fetch().',
    challenge: 'Adapte o exemplo para exibir uma mensagem diferente quando response.status for 404.',
    findError: 'Afirmação: “Se a API responder 500, fetch() sempre cai automaticamente no catch.” Corrija.',
    common: 'Esquecer await em response.json(), não verificar response.ok e imaginar que todo erro HTTP rejeita fetch().',
    summary: 'fetch() retorna uma Promise. Com async/await, o fluxo fica mais legível. response.ok deve ser verificado para detectar respostas HTTP de erro.',
    task: 'Criar um exemplo conceitual de função assíncrona que faça GET, verifique response.ok e leia JSON.',
    video: 'https://www.youtube.com/watch?v=vEwPnjqWQ-g',
    hint1: 'HTTP 404 ainda pode produzir uma resposta válida para fetch().',
    hint2: 'Verifique response.ok antes de interpretar o sucesso da operação.',
    solution: 'try/catch trata rejeições e erros lançados. Como fetch() normalmente resolve mesmo com 404 ou 500, é necessário verificar response.ok ou response.status e lançar/tratar o erro conforme a lógica da aplicação.'
  }
);