window.PDZ_DATA.lessons.push(
  {
    id: 81, module: 7, title: 'Visão completa de uma aplicação full stack', time: '50–60 min',
    learn: ['full stack', 'front-end', 'back-end', 'API', 'banco de dados', 'fluxo ponta a ponta'],
    importance: 'Até aqui você estudou as partes separadamente. Agora vai enxergar como elas trabalham juntas dentro de uma aplicação real.',
    before: 'Você já conhece HTML, CSS, JavaScript, HTTP, APIs, FastAPI e PostgreSQL.',
    explanation: 'Uma aplicação full stack reúne interface, lógica de servidor e dados persistentes. O navegador exibe o front-end. O JavaScript pode enviar uma requisição HTTP para a API. O FastAPI recebe essa requisição, aplica regras e pode consultar ou alterar dados no PostgreSQL. Depois, a API devolve uma resposta e o JavaScript atualiza a interface.',
    everyday: 'Ao marcar uma tarefa como concluída, o clique acontece na tela, a alteração é enviada ao servidor, o servidor salva no banco e a tela mostra o novo estado.',
    programming: 'Descreva o caminho de um clique em “Adicionar tarefa” até o registro ser salvo no banco.',
    code: 'HTML/CSS/JavaScript\n        ↓ requisição HTTP\nFastAPI / API\n        ↓ SQL\nPostgreSQL\n        ↑ resultado\nFastAPI / API\n        ↑ resposta HTTP\nJavaScript atualiza a tela',
    lineByLine: 'O navegador apresenta a interface. O JavaScript inicia a comunicação. HTTP transporta requisição e resposta. FastAPI executa a lógica do back-end. SQL consulta ou altera o PostgreSQL. A resposta retorna até a interface.',
    guided: 'Pegue o exemplo de criar uma tarefa e escreva, em ordem, qual tecnologia participa de cada etapa.',
    exercise: 'Explique em suas palavras o que acontece depois que o usuário clica em um botão que precisa salvar dados no servidor.',
    challenge: 'Explique por que uma aplicação pode funcionar visualmente no navegador e ainda assim falhar se a API ou o banco estiver indisponível.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nO CSS envia os dados diretamente para o PostgreSQL e recebe a resposta.',
    common: 'Misturar as responsabilidades de HTML, CSS, JavaScript, API e banco de dados.',
    summary: 'Full stack conecta interface, comunicação HTTP, back-end e persistência em banco de dados.',
    task: 'Desenhar o fluxo completo HTML/CSS/JS → HTTP → FastAPI → SQL → PostgreSQL → resposta.',
    video: '',
    hint1: 'Comece pelo navegador e termine no banco; depois faça o caminho de volta.',
    hint2: 'JavaScript conversa com a API por HTTP; ele não deve acessar diretamente o banco de dados.',
    solution: 'Clique → JavaScript lê os dados → fetch envia HTTP → FastAPI recebe e valida → FastAPI executa SQL → PostgreSQL grava → FastAPI devolve resposta → JavaScript atualiza a tela.'
  },
  {
    id: 82, module: 7, title: 'Front-end consumindo API e CORS', time: '50–60 min',
    learn: ['fetch()', 'URL da API', 'origem', 'CORS', 'CORSMiddleware'],
    importance: 'O front-end só se torna realmente conectado ao back-end quando consegue enviar requisições e tratar as respostas da API.',
    before: 'Você já usou fetch() e entende requisição e resposta HTTP.',
    explanation: 'O front-end pode chamar a API com fetch(). Quando front-end e API estão em origens diferentes, o navegador aplica a política de CORS. Uma origem considera esquema, host e porta. No FastAPI, CORSMiddleware pode permitir origens específicas. CORS é uma política do navegador; ele não autentica usuários e não substitui autorização no servidor.',
    everyday: 'É como uma portaria que decide de quais endereços o navegador aceita certas comunicações. Isso não prova quem a pessoa é nem quais dados ela pode acessar.',
    programming: 'Faça o navegador buscar uma lista de tarefas em http://localhost:8000/tarefas.',
    code: "fetch('http://localhost:8000/tarefas')\n  .then(response => {\n    if (!response.ok) {\n      throw new Error('Falha ao carregar tarefas');\n    }\n    return response.json();\n  })\n  .then(tarefas => console.log(tarefas));\n\n# FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=['http://localhost:5500'],\n    allow_methods=['*'],\n    allow_headers=['*'],\n)",
    lineByLine: 'fetch chama a URL da API. response.ok verifica sucesso HTTP. response.json converte o corpo JSON. No FastAPI, CORSMiddleware recebe uma lista de origens permitidas para requisições feitas pelo navegador.',
    guided: 'Troque a URL por outra rota da sua API e observe quais partes pertencem ao front-end e quais pertencem ao servidor.',
    exercise: 'Escreva um fetch para GET /tarefas e explique o que é uma origem.',
    challenge: 'Explique por que permitir CORS não significa que a rota está protegida contra acesso indevido.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nCORS serve para fazer login e impedir que usuários não autorizados vejam dados.',
    common: 'Confundir CORS com autenticação, ignorar response.ok e liberar origens indiscriminadamente sem entender a necessidade.',
    summary: 'fetch conecta o front-end à API; CORS controla comunicação entre origens no navegador, mas não substitui segurança do servidor.',
    task: 'Criar uma página simples que consuma GET /tarefas e configurar uma origem local permitida no FastAPI.',
    video: '',
    hint1: 'Origem envolve protocolo/esquema, host e porta.',
    hint2: 'CORS responde à pergunta “de qual origem o navegador permite esta chamada?”, não “quem é o usuário?”.',
    solution: "fetch('http://localhost:8000/tarefas').then(async r => { if (!r.ok) throw new Error('Erro'); return r.json(); }).then(console.log);"
  },
  {
    id: 83, module: 7, title: 'FastAPI conectado ao PostgreSQL', time: '50–60 min',
    learn: ['conexão com banco', 'consulta parametrizada', 'transação', 'commit', 'rollback', 'ORM'],
    importance: 'A partir daqui, os dados deixam de existir apenas enquanto o servidor está ligado e passam a ser persistidos no PostgreSQL.',
    before: 'Você já criou APIs em memória e já conhece SQL e PostgreSQL.',
    explanation: 'O back-end precisa de um driver ou biblioteca para abrir conexão com PostgreSQL, executar SQL e receber resultados. Consultas devem receber valores por parâmetros da biblioteca, em vez de montar SQL concatenando texto do usuário. Uma transação agrupa operações: commit confirma e rollback desfaz alterações da transação quando necessário. ORM é uma camada opcional que representa dados como objetos, mas não é o banco de dados e não substitui o conhecimento de SQL.',
    everyday: 'Uma transação lembra uma alteração que só vira definitiva depois de confirmada; se algo dá errado antes da confirmação, é possível desfazer aquele conjunto de operações.',
    programming: 'Conecte conceitualmente uma rota GET /tarefas a uma consulta SELECT no PostgreSQL.',
    code: "# Exemplo conceitual com psycopg\nimport psycopg\n\nwith psycopg.connect('postgresql://usuario:senha@localhost/app') as conn:\n    with conn.cursor() as cur:\n        cur.execute('SELECT id, titulo, status FROM tarefas WHERE status = %s', ('pendente',))\n        tarefas = cur.fetchall()\n\n# Em projeto real, a credencial deve vir de variável de ambiente, não ficar escrita no código.",
    lineByLine: 'psycopg.connect abre a conexão. cursor cria o objeto usado para executar SQL. O valor pendente é enviado como parâmetro separado da instrução SQL. fetchall lê as linhas retornadas. O bloco with ajuda a encerrar recursos corretamente.',
    guided: 'Identifique no exemplo o que é conexão, SQL, parâmetro e resultado.',
    exercise: 'Explique por que concatenar diretamente texto recebido do usuário em uma consulta SQL é inadequado.',
    challenge: 'Explique a diferença entre PostgreSQL, SQL, driver e ORM.',
    findError: "EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\ncur.execute(\"SELECT * FROM tarefas WHERE titulo = '\" + titulo_usuario + \"'\")",
    common: 'Guardar senha do banco no código, confundir ORM com banco, esquecer de fechar recursos e concatenar entrada do usuário no SQL.',
    summary: 'FastAPI acessa PostgreSQL por uma biblioteca de banco; consultas parametrizadas e transações tornam o fluxo mais correto e seguro.',
    task: 'Mapear uma rota da API para uma consulta SQL e identificar onde entram conexão, parâmetros, commit e rollback.',
    video: '',
    hint1: 'Valores vindos do usuário devem ser parâmetros da consulta.',
    hint2: 'ORM é uma camada de abstração; PostgreSQL continua sendo o SGBD.',
    solution: 'PostgreSQL é o SGBD; SQL é a linguagem de consulta; o driver permite que o Python converse com PostgreSQL; ORM é uma abstração opcional sobre essa interação.'
  },
  {
    id: 84, module: 7, title: 'CRUD ponta a ponta', time: '50–60 min',
    learn: ['criar', 'listar', 'atualizar', 'excluir', 'interface → API → banco → interface'],
    importance: 'O CRUD ponta a ponta junta tudo que foi aprendido e mostra como uma alteração percorre todas as camadas da aplicação.',
    before: 'Você já entende front-end consumindo API e FastAPI conectado ao PostgreSQL.',
    explanation: 'Cada operação de CRUD possui um fluxo completo. O front-end coleta dados e envia HTTP. O FastAPI valida e executa a regra. O banco persiste ou consulta. A API devolve status e dados. O front-end interpreta essa resposta e atualiza a interface. Erros também devem seguir esse caminho e ser exibidos de forma compreensível.',
    everyday: 'Excluir uma tarefa envolve clicar em excluir, enviar o id, o servidor localizar e remover o registro, devolver a resposta e só então a tela refletir o resultado.',
    programming: 'Implemente conceitualmente o fluxo DELETE /tarefas/{id} e a chamada fetch correspondente.',
    code: "async function excluirTarefa(id) {\n  const response = await fetch(`http://localhost:8000/tarefas/${id}`, {\n    method: 'DELETE'\n  });\n\n  if (!response.ok) {\n    throw new Error('Não foi possível excluir');\n  }\n\n  await carregarTarefas();\n}",
    lineByLine: 'A função recebe o id. fetch chama o endpoint correto com DELETE. response.ok verifica o resultado HTTP. Se a exclusão deu certo, carregarTarefas busca novamente o estado atual e redesenha a lista.',
    guided: 'Faça o mesmo raciocínio para POST e PATCH antes de escrever código.',
    exercise: 'Descreva o fluxo completo para alterar o status de uma tarefa de pendente para concluída.',
    challenge: 'Explique por que atualizar a interface antes de saber se a API confirmou a operação pode causar inconsistência visual.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nAo clicar em excluir, remova o item da tela e não envie nenhuma requisição para a API.',
    common: 'Atualizar apenas a tela sem persistir no servidor, ignorar respostas HTTP e duplicar estado sem sincronização.',
    summary: 'CRUD full stack exige sincronização entre interface, API e banco de dados.',
    task: 'Escrever o fluxo e os endpoints necessários para criar, listar, atualizar e excluir tarefas.',
    video: '',
    hint1: 'Para cada ação, pense primeiro no método HTTP e no endpoint.',
    hint2: 'Depois da resposta, a interface precisa representar o estado confirmado pelo servidor.',
    solution: 'PATCH /tarefas/{id} recebe o novo status → FastAPI valida → UPDATE no PostgreSQL → API devolve sucesso → front-end atualiza ou recarrega a lista.'
  },
  {
    id: 85, module: 7, title: 'Projeto Full Stack: Gerenciador de tarefas v1', time: '50–60 min',
    learn: ['HTML/CSS/JavaScript', 'FastAPI', 'PostgreSQL', 'CRUD', 'validação', 'integração completa'],
    importance: 'Este projeto é a primeira aplicação completa do curso, com interface, API e dados persistentes trabalhando juntos.',
    before: 'Você domina as partes principais necessárias para integrar front-end, back-end e banco de dados.',
    explanation: 'A versão 1 do gerenciador de tarefas não terá login. O objetivo é dominar a arquitetura full stack sem adicionar autenticação cedo demais. A tabela tarefas terá id, titulo, descricao, status e created_at. O front-end cria e lista tarefas, permite editar status e conteúdo e excluir registros. O FastAPI valida dados, executa SQL e devolve respostas adequadas.',
    everyday: 'É um aplicativo pessoal de tarefas no qual os dados continuam existindo mesmo depois de fechar o navegador ou reiniciar o servidor.',
    programming: 'Construa o projeto em três partes: banco, API e interface, testando cada camada antes de integrar tudo.',
    code: "CREATE TABLE tarefas (\n  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  titulo VARCHAR(200) NOT NULL,\n  descricao TEXT,\n  status VARCHAR(30) NOT NULL DEFAULT 'pendente',\n  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\n\n# Endpoints esperados\nGET    /tarefas\nPOST   /tarefas\nPATCH  /tarefas/{id}\nDELETE /tarefas/{id}",
    lineByLine: 'A tabela define os dados persistentes. id identifica cada tarefa. titulo é obrigatório. descricao pode guardar texto maior. status começa como pendente. created_at registra a criação. Os quatro endpoints cobrem o CRUD necessário nesta versão.',
    guided: 'Primeiro crie a tabela e teste SQL. Depois implemente os endpoints no FastAPI. Por fim, conecte a interface com fetch().',
    exercise: 'Implemente uma tela que liste tarefas vindas da API e um formulário que crie uma nova tarefa.',
    challenge: 'Complete editar e excluir, trate erros e garanta que a interface reflita o estado realmente salvo no banco.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nSalvar as tarefas apenas no localStorage e afirmar que o projeto já usa PostgreSQL.',
    common: 'Tentar construir todas as camadas ao mesmo tempo, guardar segredos no front-end, pular validação no servidor e confundir localStorage com banco do servidor.',
    summary: 'O projeto fecha o módulo integrando HTML/CSS/JS, HTTP, FastAPI, SQL e PostgreSQL em um CRUD persistente.',
    task: 'Finalizar o Gerenciador de tarefas v1 com CRUD completo, sem login, e documentar o fluxo ponta a ponta.',
    video: '',
    hint1: 'Teste banco, API e front-end separadamente antes da integração final.',
    hint2: 'A fonte de verdade das tarefas deve ser o PostgreSQL; a interface apenas apresenta e envia ações.',
    solution: 'Projeto concluído quando criar, listar, editar e excluir tarefas pela interface altera de fato os registros no PostgreSQL por meio da API FastAPI.'
  }
);