window.PDZ_DATA.lessons.push(
{
 id:106,module:10,title:'Domínios, registradores, TLD e subdomínios',time:'55 min',
 learn:['Entender o que é um nome de domínio','Diferenciar domínio, TLD e subdomínio','Entender o papel de um registrador'],
 importance:'Um domínio oferece um nome legível para acessar um serviço na Internet, evitando que a pessoa precise memorizar endereços IP.',
 before:'Você já viu que um aplicativo publicado precisa estar acessível na Internet. Agora veremos como nomes como exemplo.com se relacionam com esse acesso.',
 explanation:'Um domínio é um nome registrado dentro do sistema de nomes da Internet. Em exemplo.com, “com” é o TLD e “exemplo.com” é o domínio. Em app.exemplo.com, “app” é um subdomínio. O registrador é a empresa credenciada pela qual um domínio pode ser registrado. Registrar um domínio não é a mesma coisa que contratar hospedagem.',
 everyday:'Pense no domínio como um nome fácil de lembrar que ajuda a chegar ao serviço correto; a infraestrutura que executa o aplicativo é outra parte do sistema.',
 programming:'Um front-end pode ser publicado em app.exemplo.com e uma API em api.exemplo.com, dependendo da arquitetura escolhida.',
 code:'Domínio: exemplo.com\nTLD: .com\nSubdomínio: app.exemplo.com',
 lineByLine:['exemplo.com é um exemplo de domínio.','.com representa o TLD nesse exemplo.','app.exemplo.com acrescenta o subdomínio app.'],
 guided:'Identifique domínio, TLD e subdomínio em cursos.exemplo.com.',
 exercise:'Explique com suas palavras a diferença entre domínio e hospedagem.',
 challenge:'Imagine um site e uma API. Proponha nomes de subdomínios para cada serviço.',
 findError:'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Comprar um domínio significa que o aplicativo já está hospedado.”\nCorreção: domínio e hospedagem são serviços diferentes.',
 common:'Confundir domínio, site e hospedagem como se fossem a mesma coisa.',
 summary:'Domínio é o nome; TLD é a parte final como .com; subdomínio acrescenta uma divisão ao domínio; registrador participa do registro do nome.',
 task:'Desenhar domínio → DNS → serviço publicado.',video:'',hint1:'Comece identificando a parte final do nome.',hint2:'Depois separe o nome principal do prefixo.',solution:'Em app.exemplo.com: .com é o TLD, exemplo.com é o domínio e app é o subdomínio.'
},
{
 id:107,module:10,title:'Como funciona o DNS',time:'60 min',
 learn:['Entender a finalidade do DNS','Conhecer resolver, root, TLD e servidor autoritativo','Visualizar uma resolução de nome de forma simplificada'],
 importance:'O DNS permite descobrir informações associadas a nomes de domínio, sendo fundamental para acessar serviços por nomes legíveis.',
 before:'Na aula anterior, você conheceu os domínios. Agora veremos como o sistema encontra informações necessárias para chegar ao serviço.',
 explanation:'Quando uma resposta não está disponível em cache, um resolvedor DNS pode consultar a hierarquia do DNS. De forma simplificada, ele obtém orientação de servidores raiz, depois de servidores responsáveis pelo TLD e finalmente consulta o servidor autoritativo do domínio. O servidor autoritativo fornece os registros DNS pelos quais é responsável. Cache pode evitar que todas essas consultas aconteçam a cada acesso.',
 everyday:'É como consultar uma cadeia organizada de informações até chegar à fonte responsável pelo endereço procurado.',
 programming:'Ao publicar um app, você configura registros DNS para relacionar nomes como app.exemplo.com ao destino apropriado.',
 code:'Cliente → Resolver DNS\n          ↓\n        Root\n          ↓\n       TLD (.com)\n          ↓\nServidor autoritativo\n          ↓\n      Resposta DNS',
 lineByLine:['O cliente consulta um resolvedor.','O resolvedor pode usar cache ou realizar consultas.','Root e TLD orientam a busca pela autoridade adequada.','O servidor autoritativo responde pelos registros do domínio.'],
 guided:'Explique por que o servidor raiz não precisa guardar diretamente o IP de todos os sites do mundo.',
 exercise:'Coloque em ordem: servidor autoritativo, resolver, TLD, root.',
 challenge:'Explique onde o cache pode reduzir consultas repetidas.',
 findError:'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“O DNS é um único servidor mundial que contém todos os domínios.”\nCorreção: DNS é um sistema distribuído e hierárquico.',
 common:'Imaginar que uma consulta DNS sempre percorre toda a hierarquia, ignorando cache.',
 summary:'DNS é distribuído. Resolvedores consultam informações e podem usar cache; root, TLD e servidores autoritativos têm papéis diferentes.',
 task:'Desenhar o caminho simplificado de uma resolução DNS.',video:'',hint1:'Comece pelo resolver.',hint2:'Depois pense na hierarquia root → TLD → autoritativo.',solution:'Cliente → resolver → root → TLD → servidor autoritativo → resposta, quando o cache não fornece antes a informação necessária.'
},
{
 id:108,module:10,title:'Registros A e AAAA',time:'50 min',
 learn:['Entender registros DNS A e AAAA','Relacionar A com IPv4','Relacionar AAAA com IPv6'],
 importance:'A e AAAA estão entre os registros usados para associar nomes a endereços IP.',
 before:'Você já sabe como uma consulta DNS chega a uma fonte autoritativa. Agora veremos dois tipos de registro.',
 explanation:'Um registro A associa um nome a um endereço IPv4. Um registro AAAA associa um nome a um endereço IPv6. Eles não significam “site” ou “servidor” por si só; são registros que fornecem endereços IP para um nome.',
 everyday:'É como ter duas formas padronizadas de registrar endereços, uma para IPv4 e outra para IPv6.',
 programming:'Um serviço pode ter registros A e AAAA quando está disponível pelos dois protocolos.',
 code:'exemplo.com.  A     192.0.2.10\nexemplo.com.  AAAA  2001:db8::10',
 lineByLine:['A aponta o nome para um IPv4.','AAAA aponta o nome para um IPv6.','Os endereços usados no exemplo pertencem a faixas reservadas para documentação.'],
 guided:'Qual registro você escolheria para um destino IPv6?',
 exercise:'Complete: A → ____; AAAA → ____.',
 challenge:'Explique por que um domínio pode ter A e AAAA ao mesmo tempo.',
 findError:'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Registro AAAA aponta para quatro endereços IPv4.”\nCorreção: AAAA é usado para endereço IPv6.',
 common:'Achar que a quantidade de letras A indica a quantidade de endereços.',
 summary:'A → IPv4. AAAA → IPv6.',task:'Criar dois registros fictícios usando os endereços de documentação da aula.',video:'',hint1:'Lembre das versões IP.',hint2:'A está associado ao IPv4; AAAA ao IPv6.',solution:'A → IPv4; AAAA → IPv6.'
},
{
 id:109,module:10,title:'CNAME, MX, TXT e NS',time:'60 min',
 learn:['Conhecer registros CNAME, MX, TXT e NS','Entender que CNAME referencia outro hostname','Relacionar MX a email e NS à autoridade DNS'],
 importance:'DNS guarda diferentes tipos de informação, não apenas endereços IP.',
 before:'A e AAAA relacionam nomes a IPs. Outros registros resolvem necessidades diferentes.',
 explanation:'CNAME cria um alias para outro nome de host, não aponta diretamente para um endereço IP. MX indica servidores responsáveis pelo recebimento de email de um domínio e possui prioridade. TXT armazena texto e é usado em diversas verificações e políticas. NS indica os servidores DNS autoritativos de uma zona. As regras exatas de configuração dependem do provedor e do contexto.',
 everyday:'É como um cadastro com campos diferentes: um campo para apelido, outro para correio, outro para informações textuais e outro para indicar quem responde oficialmente pela zona.',
 programming:'Na publicação de serviços, você pode encontrar CNAME ao conectar um subdomínio a um hostname fornecido pela plataforma e TXT em verificações de domínio.',
 code:'www.exemplo.com. CNAME destino.exemplo.net.\nexemplo.com. MX 10 mail.exemplo.com.\nexemplo.com. TXT "texto-de-verificacao"\nexemplo.com. NS ns1.exemplo.net.',
 lineByLine:['CNAME referencia outro hostname.','MX identifica destino de email e inclui prioridade.','TXT contém informação textual.','NS indica servidor autoritativo da zona.'],
 guided:'Qual tipo de registro você procuraria ao configurar o recebimento de email?',
 exercise:'Associe: CNAME, MX, TXT, NS às suas funções.',
 challenge:'Explique por que “CNAME aponta para um IP” está conceitualmente errado.',
 findError:'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“www.exemplo.com CNAME 192.0.2.10”\nCorreção: CNAME referencia outro hostname; para IPv4, use registro A quando apropriado.',
 common:'Confundir CNAME com A.',summary:'CNAME → outro hostname; MX → email; TXT → texto; NS → servidores autoritativos da zona.',task:'Montar uma pequena tabela com os seis registros estudados: A, AAAA, CNAME, MX, TXT e NS.',video:'',hint1:'Pense em alias, email, texto e autoridade.',hint2:'CNAME não recebe diretamente um IP.',solution:'CNAME=alias para hostname; MX=email; TXT=texto; NS=servidores autoritativos.'
},
{
 id:110,module:10,title:'TTL, cache, subdomínios e HTTPS',time:'60 min',
 learn:['Entender TTL e cache DNS','Revisar subdomínios','Diferenciar DNS de HTTPS','Conectar domínio, DNS e publicação'],
 importance:'Publicar um app exige entender que encontrar o destino pelo DNS e proteger a comunicação com HTTPS são etapas diferentes.',
 before:'Você já conhece domínios e os principais registros DNS. Agora vamos conectar as peças.',
 explanation:'TTL (Time To Live) informa por quanto tempo uma resposta DNS pode ser mantida em cache, conforme o registro e o resolvedor. Alterações DNS podem não aparecer instantaneamente para todos por causa de caches e outros fatores. Subdomínios permitem organizar nomes como app.exemplo.com e api.exemplo.com. DNS ajuda a localizar o destino associado a um nome; HTTPS protege a comunicação HTTP em trânsito usando TLS e certificados. DNS não substitui HTTPS, e HTTPS não substitui DNS.',
 everyday:'Saber o endereço de um lugar e usar um transporte protegido até ele são problemas diferentes. A comparação é apenas uma analogia: DNS e TLS têm mecanismos técnicos próprios.',
 programming:'Fluxo simplificado: navegador resolve o nome pelo DNS, conecta-se ao destino e, em HTTPS, estabelece uma conexão protegida por TLS antes de trocar dados HTTP protegidos em trânsito.',
 code:'app.exemplo.com\n      ↓ DNS\nDestino do serviço\n      ↓ TLS/HTTPS\nComunicação HTTP protegida em trânsito',
 lineByLine:['O nome é consultado pelo DNS.','O resultado ajuda a localizar o destino.','HTTPS usa TLS para proteger a comunicação em trânsito.'],
 guided:'Explique por que trocar um registro DNS não é a mesma coisa que instalar/configurar um certificado TLS.',
 exercise:'Defina em uma frase: TTL, cache DNS e HTTPS.',
 challenge:'Descreva o caminho de app.exemplo.com até uma aplicação publicada, citando DNS e HTTPS.',
 findError:'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se o DNS está configurado, a conexão já é HTTPS automaticamente.”\nCorreção: DNS e HTTPS cumprem funções diferentes; HTTPS depende da configuração TLS/certificado adequada.',
 common:'Chamar o tempo de atualização de DNS de um cronômetro universal e exato para todos os usuários.',
 summary:'TTL influencia cache DNS. Subdomínios organizam nomes. DNS localiza informações do destino; HTTPS protege a comunicação em trânsito.',task:'Desenhar a arquitetura domínio → DNS → serviço → HTTPS.',video:'',hint1:'Separe localização de proteção.',hint2:'DNS responde sobre nomes; TLS/HTTPS protege a comunicação.',solution:'O navegador resolve o nome via DNS, conecta-se ao destino e usa TLS quando o serviço está corretamente configurado para HTTPS.'
}
);