window.PDZ_DATA.lessons.push(
  {
    id: 76, module: 6, title: 'CREATE TABLE e INSERT', time: '50–60 min',
    learn: ['CREATE TABLE', 'definição de colunas e tipos', 'PRIMARY KEY', 'INSERT INTO', 'VALUES'],
    importance: 'Antes de consultar dados, você precisa saber como uma tabela é definida e como novos registros são inseridos.',
    before: 'Você já conhece tabelas, tipos, chave primária, chave estrangeira e relacionamentos.',
    explanation: 'CREATE TABLE cria a estrutura de uma tabela, definindo colunas, tipos e restrições. INSERT INTO adiciona registros. A estrutura deve ser pensada antes dos dados. Em exemplos iniciais, vamos usar alunos e cursos.',
    everyday: 'Criar uma tabela é como preparar uma ficha com campos definidos antes de começar a preenchê-la.',
    programming: 'Crie uma tabela alunos e insira dois registros.',
    code: 'CREATE TABLE alunos (\n  id INTEGER PRIMARY KEY,\n  nome VARCHAR(100) NOT NULL,\n  idade INTEGER\n);\n\nINSERT INTO alunos (id, nome, idade)\nVALUES (1, \'Ana\', 20);\n\nINSERT INTO alunos (id, nome, idade)\nVALUES (2, \'Bruno\', 22);',
    lineByLine: 'CREATE TABLE alunos inicia a definição. id é a chave primária. nome usa VARCHAR(100) e não aceita nulo. INSERT INTO informa tabela e colunas; VALUES informa os valores na mesma ordem.',
    guided: 'Crie uma tabela cursos com id, nome e carga_horaria. Depois insira dois cursos.',
    exercise: 'Escreva um INSERT que adicione um aluno chamado Carla, de 19 anos, com id 3.',
    challenge: 'Explique por que é melhor informar explicitamente as colunas em INSERT INTO em vez de depender da ordem física da tabela.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nINSERT alunos VALUES (4, \'Davi\', 21);',
    common: 'Esquecer INTO, misturar a ordem das colunas e valores, inserir texto sem aspas simples e ignorar restrições.',
    summary: 'CREATE TABLE define a estrutura; INSERT INTO adiciona registros.',
    task: 'Criar as tabelas alunos e cursos e inserir ao menos três registros em cada uma.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'A forma básica é INSERT INTO tabela (colunas) VALUES (valores);',
    hint2: 'Textos em SQL costumam aparecer entre aspas simples.',
    solution: 'INSERT INTO alunos (id, nome, idade) VALUES (3, \'Carla\', 19);'
  },
  {
    id: 77, module: 6, title: 'SELECT e WHERE', time: '50–60 min',
    learn: ['SELECT', 'FROM', 'seleção de colunas', 'WHERE', 'filtros'],
    importance: 'Consultar dados é uma das tarefas mais frequentes em sistemas que usam banco de dados.',
    before: 'Você já criou tabelas e inseriu registros.',
    explanation: 'SELECT escolhe quais colunas retornar. FROM informa a tabela. WHERE aplica condições. Em projetos reais, prefira selecionar apenas as colunas necessárias em vez de usar SELECT * indiscriminadamente.',
    everyday: 'É como pedir apenas nome e idade de estudantes com mais de 18 anos, em vez de trazer toda a ficha de todos.',
    programming: 'Consulte nomes e idades de alunos com idade maior ou igual a 20.',
    code: 'SELECT nome, idade\nFROM alunos\nWHERE idade >= 20;',
    lineByLine: 'SELECT nome, idade define as colunas da resposta. FROM alunos define a origem. WHERE idade >= 20 mantém apenas registros que atendem à condição.',
    guided: 'Faça consultas por nome, idade e id usando operadores de comparação.',
    exercise: 'Liste apenas nome e idade dos alunos com idade menor que 21.',
    challenge: 'Explique por que SELECT * pode ser inadequado quando a tabela tem muitas colunas e a aplicação precisa de poucas.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nSELECT FROM alunos WHERE idade > 18;',
    common: 'Esquecer as colunas após SELECT, escrever condições sem WHERE e usar SELECT * como padrão automático.',
    summary: 'SELECT lê dados; WHERE filtra linhas conforme condições.',
    task: 'Criar cinco consultas diferentes usando seleção explícita de colunas e WHERE.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Comece com SELECT nome, idade FROM alunos.',
    hint2: 'Depois acrescente WHERE com a condição desejada.',
    solution: 'SELECT nome, idade FROM alunos WHERE idade < 21;'
  },
  {
    id: 78, module: 6, title: 'UPDATE e DELETE', time: '50–60 min',
    learn: ['UPDATE', 'SET', 'DELETE FROM', 'WHERE', 'risco de alterar ou excluir várias linhas'],
    importance: 'Atualizar e excluir dados exige cuidado, porque um comando sem filtro pode afetar muitos registros de uma vez.',
    before: 'Você já sabe consultar registros com WHERE.',
    explanation: 'UPDATE altera valores existentes e usa SET para indicar novas informações. DELETE FROM remove registros. Em ambos, WHERE é frequentemente essencial. Um UPDATE sem WHERE pode alterar todas as linhas; um DELETE sem WHERE pode remover todas as linhas da tabela.',
    everyday: 'Se você quer corrigir a idade de uma única pessoa, precisa identificá-la claramente antes de aplicar a alteração.',
    programming: 'Atualize a idade do aluno de id 2 e depois remova um registro específico.',
    code: 'UPDATE alunos\nSET idade = 23\nWHERE id = 2;\n\nDELETE FROM alunos\nWHERE id = 3;',
    lineByLine: 'UPDATE escolhe a tabela; SET informa o novo valor; WHERE limita a alteração. DELETE FROM escolhe a tabela e WHERE limita quais linhas serão removidas.',
    guided: 'Antes de executar UPDATE ou DELETE, escreva primeiro um SELECT com o mesmo WHERE para conferir quais linhas seriam afetadas.',
    exercise: 'Altere o nome do aluno id 1 para Ana Silva.',
    challenge: 'Explique por que revisar o WHERE antes de UPDATE e DELETE é uma prática de segurança operacional.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nDELETE FROM alunos;',
    common: 'Executar UPDATE ou DELETE sem WHERE quando a intenção era atingir apenas um registro.',
    summary: 'UPDATE altera; DELETE remove. WHERE evita afetar linhas indevidas quando a operação deve ser seletiva.',
    task: 'Praticar dois UPDATEs e dois DELETEs específicos, sempre conferindo antes com SELECT.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Use WHERE id = ... para atingir um registro específico.',
    hint2: 'Teste o filtro primeiro com SELECT.',
    solution: "UPDATE alunos SET nome = 'Ana Silva' WHERE id = 1;"
  },
  {
    id: 79, module: 6, title: 'Ordenação e funções de agregação', time: '50–60 min',
    learn: ['ORDER BY', 'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'GROUP BY'],
    importance: 'Agregações transformam várias linhas em informações resumidas, como quantidade, média, mínimo e máximo.',
    before: 'Você já sabe criar, inserir, consultar, atualizar e excluir registros.',
    explanation: 'ORDER BY organiza resultados. COUNT conta linhas; SUM soma valores; AVG calcula média; MIN e MAX encontram extremos. GROUP BY cria grupos antes da agregação, permitindo resumir dados por categoria.',
    everyday: 'Em vez de listar todas as matrículas, você pode perguntar quantos alunos existem em cada curso.',
    programming: 'Conte matrículas por curso e ordene o resultado.',
    code: 'SELECT curso_id, COUNT(*) AS total_matriculas\nFROM matriculas\nGROUP BY curso_id\nORDER BY total_matriculas DESC;',
    lineByLine: 'SELECT retorna curso_id e a contagem. COUNT(*) conta linhas de cada grupo. GROUP BY curso_id separa as linhas por curso. ORDER BY organiza do maior para o menor.',
    guided: 'Calcule idade média dos alunos e descubra menor e maior idade.',
    exercise: 'Escreva consultas com COUNT, AVG, MIN e MAX sobre a tabela alunos.',
    challenge: 'Explique por que GROUP BY é necessário quando queremos uma contagem separada para cada curso.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nSELECT curso_id, COUNT(*) FROM matriculas;',
    common: 'Misturar colunas comuns e agregadas sem agrupar corretamente e esquecer a direção ASC/DESC quando a ordem importa.',
    summary: 'ORDER BY ordena; funções de agregação resumem; GROUP BY resume por grupos.',
    task: 'Criar consultas de contagem, média, mínimo, máximo e agrupamento por curso.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Para resumir por categoria, pense em GROUP BY.',
    hint2: 'ORDER BY pode usar ASC ou DESC.',
    solution: 'SELECT COUNT(*) AS total, AVG(idade) AS media, MIN(idade) AS menor, MAX(idade) AS maior FROM alunos;'
  },
  {
    id: 80, module: 6, title: 'JOIN e projeto do módulo', time: '50–60 min',
    learn: ['INNER JOIN', 'LEFT JOIN', 'junção por chaves', 'tabelas alunos, cursos e matriculas', 'projeto relacional'],
    importance: 'Bancos relacionais ganham força quando dados separados em tabelas podem ser combinados de forma controlada.',
    before: 'Você entende chaves, relacionamentos e consultas SQL básicas.',
    explanation: 'JOIN combina linhas de tabelas relacionadas. INNER JOIN retorna combinações que encontram correspondência segundo a condição ON. LEFT JOIN preserva todas as linhas da tabela à esquerda e inclui dados correspondentes da direita quando existirem. A condição de junção normalmente relaciona chave estrangeira com chave primária.',
    everyday: 'A matrícula guarda os identificadores; o JOIN permite exibir o nome do aluno e o nome do curso em vez de apenas números.',
    programming: 'Monte o projeto escolar com alunos, cursos e matriculas e consulte aluno + curso.',
    code: 'SELECT a.nome AS aluno, c.nome AS curso\nFROM matriculas m\nINNER JOIN alunos a ON a.id = m.aluno_id\nINNER JOIN cursos c ON c.id = m.curso_id;\n\nSELECT a.nome, m.curso_id\nFROM alunos a\nLEFT JOIN matriculas m ON m.aluno_id = a.id;',
    lineByLine: 'FROM matriculas parte da tabela associativa. INNER JOIN alunos encontra o aluno da matrícula. INNER JOIN cursos encontra o curso. O segundo exemplo usa LEFT JOIN para manter alunos mesmo quando não houver matrícula correspondente.',
    guided: 'Crie as três tabelas, insira dados e faça uma consulta que exiba nomes de alunos e cursos.',
    exercise: 'Faça um LEFT JOIN que liste todos os cursos, inclusive os que ainda não têm matrícula.',
    challenge: 'Explique a diferença prática entre INNER JOIN e LEFT JOIN usando um aluno sem matrícula.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nSELECT a.nome, c.nome\nFROM alunos a\nINNER JOIN cursos c;',
    common: 'Esquecer a condição ON, juntar colunas erradas e escolher INNER JOIN quando era necessário preservar linhas sem correspondência.',
    summary: 'INNER JOIN mantém correspondências; LEFT JOIN preserva todas as linhas da esquerda. O projeto fecha o módulo conectando modelagem e SQL.',
    task: 'Finalizar o banco escolar com alunos, cursos e matriculas e produzir consultas com INNER JOIN e LEFT JOIN.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'No N:N, a tabela matriculas liga aluno_id a curso_id.',
    hint2: 'Para manter todos os cursos, coloque cursos à esquerda do LEFT JOIN.',
    solution: 'SELECT c.nome AS curso, m.aluno_id FROM cursos c LEFT JOIN matriculas m ON m.curso_id = c.id;'
  }
);