window.PDZ_DATA.lessons.push(
  {
    id: 116, module: 12, title: 'Criptografia, hash e codificação', time: '50–60 min',
    learn: ['plaintext', 'ciphertext', 'chave', 'criptografia', 'hash', 'codificação', 'Base64'],
    importance: 'Segurança começa por usar os conceitos certos. Criptografar, gerar hash e codificar dados resolvem problemas diferentes e não devem ser tratados como sinônimos.',
    before: 'Você já estudou HTTPS, autenticação, autorização, segredos e práticas de segurança defensiva.',
    explanation: 'Criptografia transforma um texto legível, chamado plaintext, em ciphertext usando um algoritmo e uma chave, permitindo recuperar o conteúdo quando o processo adequado e a chave correta estão disponíveis. Hash transforma dados em um valor de tamanho definido e é projetado para não ser revertido de forma prática. Codificação muda a representação de dados para transporte ou compatibilidade. Base64 é codificação: qualquer pessoa pode decodificar sem possuir uma chave secreta.',
    everyday: 'Criptografia é como colocar uma mensagem em um cofre com chave. Hash é mais parecido com uma impressão digital do conteúdo. Codificação é como mudar o formato de escrita para facilitar transporte.',
    programming: 'Classifique três situações: proteger um segredo, verificar se um arquivo mudou e representar bytes como texto.',
    code: 'Criptografia → plaintext + chave → ciphertext\nHash         → dados → resumo não reversível na prática\nBase64       → bytes ↔ texto codificado',
    lineByLine: 'A criptografia depende de chave. O hash produz um resumo e não é usado para recuperar o conteúdo original. Base64 apenas altera a representação e pode ser revertido sem segredo.',
    guided: 'Explique por que colocar uma senha em Base64 não protege a senha.',
    exercise: 'Qual conceito é mais adequado para: confidencialidade de dados, verificação de integridade e transporte textual de bytes?',
    challenge: 'Explique por que hash e criptografia não são intercambiáveis em um sistema de autenticação.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Vou proteger a senha usando Base64 porque ninguém conseguirá ler.”',
    common: 'Chamar Base64 de criptografia ou imaginar que todo hash pode ser decodificado.',
    summary: 'Criptografia protege confidencialidade com chaves. Hash gera um resumo não reversível na prática. Codificação apenas muda a representação.',
    task: 'Criar uma tabela com objetivo, reversibilidade e uso típico de criptografia, hash e Base64.',
    video: '',
    hint1: 'Pergunte se existe uma chave secreta e se o objetivo é recuperar o conteúdo depois.',
    hint2: 'Base64 não usa chave; hash não foi feito para recuperar o original.',
    solution: 'Confidencialidade → criptografia. Integridade → hash. Representação textual de bytes → codificação como Base64.'
  },
  {
    id: 117, module: 12, title: 'Criptografia simétrica', time: '50–60 min',
    learn: ['criptografia simétrica', 'chave secreta compartilhada', 'AES', 'proteção de chaves'],
    importance: 'Criptografia simétrica é amplamente usada para proteger grandes volumes de dados com eficiência, mas depende do gerenciamento correto da chave secreta.',
    before: 'Você já diferencia criptografia, hash e codificação.',
    explanation: 'Na criptografia simétrica, a mesma chave secreta é usada para cifrar e decifrar os dados. AES é um exemplo moderno amplamente usado. A segurança não depende apenas do algoritmo: a chave precisa ser gerada, armazenada e compartilhada com cuidado. Não se deve criar algoritmo criptográfico próprio para sistemas reais.',
    everyday: 'É como duas pessoas terem cópias da mesma chave de um cofre. Quem possui a chave consegue abrir e fechar.',
    programming: 'Pense em uma aplicação que cifra um backup antes de armazená-lo. A chave não deve ficar escrita no código-fonte ou no repositório.',
    code: 'plaintext + chave secreta → cifra simétrica → ciphertext\nciphertext + mesma chave → decifra → plaintext',
    lineByLine: 'A mesma chave participa das duas direções. Se a chave vazar, a confidencialidade pode ser comprometida. Por isso o gerenciamento da chave faz parte da segurança.',
    guided: 'Liste três locais inadequados para guardar uma chave de produção.',
    exercise: 'Por que enviar a chave junto com o arquivo cifrado, no mesmo local e sem proteção, reduz a segurança?',
    challenge: 'Explique a principal dificuldade prática da criptografia simétrica quando muitas pessoas precisam se comunicar com segurança.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Para facilitar, vou inventar meu próprio algoritmo de criptografia e guardar a chave dentro do JavaScript público do site.”',
    common: 'Achar que um algoritmo forte compensa uma chave exposta.',
    summary: 'Criptografia simétrica usa a mesma chave para cifrar e decifrar. AES é um exemplo moderno; a chave deve ser protegida.',
    task: 'Desenhar o fluxo de cifra e decifra simétrica e marcar onde a chave precisa ser protegida.',
    video: '',
    hint1: 'Pense no que acontece se qualquer pessoa conseguir ler a chave.',
    hint2: 'Código entregue ao navegador é público para o usuário.',
    solution: 'A chave deve permanecer em ambiente protegido. Se ela acompanha os dados de forma exposta, quem obtiver ambos pode decifrar o conteúdo.'
  },
  {
    id: 118, module: 12, title: 'Criptografia assimétrica e assinaturas digitais', time: '50–60 min',
    learn: ['chave pública', 'chave privada', 'RSA', 'ECC', 'assinatura digital', 'verificação'],
    importance: 'Criptografia assimétrica permite resolver problemas de troca de chaves, identidade e assinaturas digitais sem compartilhar a chave privada.',
    before: 'Você já conhece criptografia simétrica e a importância de proteger chaves.',
    explanation: 'Na criptografia assimétrica existe um par de chaves relacionado matematicamente: uma pública e uma privada. Dependendo do protocolo, a chave pública pode participar de operações de confidencialidade ou verificação, enquanto a privada deve permanecer secreta. RSA e ECC são famílias conhecidas. Assinatura digital usa algoritmos próprios para produzir uma assinatura verificável com a chave pública; não é correto resumir o processo como simplesmente “criptografar com a chave privada”.',
    everyday: 'Imagine um selo que só o titular consegue produzir, mas que outras pessoas conseguem conferir usando uma informação pública. A analogia ajuda, mas a assinatura digital é um processo matemático específico.',
    programming: 'Em sistemas reais, bibliotecas e protocolos maduros cuidam dos detalhes criptográficos. A aplicação normalmente usa APIs de alto nível em vez de implementar matemática criptográfica manualmente.',
    code: 'Chave privada → permanece secreta\nChave pública → pode ser distribuída\nAssinatura → criada com operação de assinatura\nVerificação → realizada com a chave pública',
    lineByLine: 'As duas chaves têm papéis diferentes. A chave privada não deve ser publicada. A assinatura serve para verificar autenticidade e integridade conforme o esquema utilizado.',
    guided: 'Explique por que a chave pública pode ser distribuída enquanto a privada deve permanecer protegida.',
    exercise: 'Qual chave deve permanecer secreta em um par assimétrico?',
    challenge: 'Diferencie confidencialidade, autenticação e assinatura digital em poucas frases.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Assinatura digital é sempre apenas criptografar o arquivo inteiro com a chave privada.”',
    common: 'Tratar assinatura digital como uma inversão simplista da criptografia de chave pública.',
    summary: 'Criptografia assimétrica usa par de chaves. A privada fica secreta; a pública pode ser distribuída. Assinaturas digitais usam esquemas próprios de assinatura e verificação.',
    task: 'Criar um diagrama com chave pública, chave privada, assinatura e verificação.',
    video: '',
    hint1: 'O nome já ajuda: privada deve permanecer privada.',
    hint2: 'A pública serve para operações que podem ser compartilhadas, como verificação em muitos esquemas.',
    solution: 'A chave privada deve permanecer secreta. A chave pública pode ser distribuída para os usos previstos pelo algoritmo/protocolo, como verificação de assinaturas.'
  },
  {
    id: 119, module: 12, title: 'Hash de senhas, certificados e TLS', time: '60 min',
    learn: ['hash de senha', 'salt', 'Argon2id', 'certificado digital', 'TLS', 'HTTPS'],
    importance: 'Senhas e conexões exigem proteções específicas. Armazenar senha corretamente e proteger dados em trânsito são responsabilidades diferentes.',
    before: 'Você já conhece hash, criptografia, chaves e HTTPS em nível introdutório.',
    explanation: 'Senhas não devem ser guardadas em texto puro nem cifradas de forma reversível como padrão. O servidor deve armazenar uma derivação de senha produzida por uma função adequada para senhas, com salt único por senha. Argon2id é um exemplo moderno apropriado em muitos contextos. Salt não precisa ser secreto; ele ajuda a evitar que hashes iguais representem senhas iguais e dificulta ataques pré-computados. MD5, SHA-1 e SHA-256 puro não são escolhas adequadas para armazenamento de senhas. Separadamente, certificados digitais ajudam o cliente a autenticar o servidor em TLS. HTTPS é HTTP protegido por TLS, oferecendo proteção da comunicação em trânsito quando corretamente configurado.',
    everyday: 'O hash da senha protege o que fica armazenado no servidor. TLS protege a conversa enquanto os dados viajam pela rede. São camadas diferentes.',
    programming: 'Fluxo de login: o servidor recebe a senha por HTTPS, aplica a função de verificação de senha adequada contra o hash armazenado e, se corresponder, inicia uma sessão ou outro mecanismo de autenticação.',
    code: 'Cadastro:\nsenha → função própria para senha + salt → senha_hash\n\nLogin:\nsenha informada → verificação segura → corresponde?\n\nTransporte:\nNavegador ⇄ TLS/HTTPS ⇄ servidor',
    lineByLine: 'A senha original não precisa ser recuperada do banco. A função de verificação compara de forma apropriada com o hash armazenado. TLS protege os dados enquanto trafegam.',
    guided: 'Explique por que salt pode ser armazenado junto com o hash e ainda assim continuar útil.',
    exercise: 'Por que SHA-256 puro não deve ser a solução padrão para armazenar senhas?',
    challenge: 'Explique a diferença entre proteger uma senha no banco e protegê-la durante o envio pela Internet.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Vou salvar senha = SHA256(senha) e pronto, porque SHA-256 é forte.”',
    common: 'Confundir hash rápido de uso geral com função de derivação de senha e imaginar que HTTPS elimina a necessidade de armazenamento seguro.',
    summary: 'Use função própria para senhas, como Argon2id quando apropriado, com salt. Certificados e TLS protegem a comunicação HTTPS. São proteções complementares.',
    task: 'Desenhar cadastro e login mostrando onde entram hash de senha, salt, banco e HTTPS.',
    video: '',
    hint1: 'Funções de senha devem ser deliberadamente custosas para dificultar tentativas massivas.',
    hint2: 'Salt não é uma senha secreta; seu papel é tornar cada derivação única.',
    solution: 'SHA-256 é rápido e não foi projetado para derivação de senhas. Funções próprias para senha, como Argon2id, incluem mecanismos adequados de custo e salt.'
  },
  {
    id: 120, module: 12, title: 'Projeto Final — Gerenciador de tarefas Full Stack', time: 'Projeto final',
    learn: ['arquitetura full stack', 'cadastro', 'login', 'autorização', 'CRUD', 'FastAPI', 'PostgreSQL', 'deploy', 'HTTPS', 'Git/GitHub'],
    importance: 'O projeto final conecta os principais conhecimentos do curso em uma aplicação realista: interface, API, banco, autenticação, autorização, segurança e publicação.',
    before: 'Você percorreu Python, lógica, terminal, Git, front-end, HTTP, APIs, FastAPI, SQL, PostgreSQL, redes, Linux, deploy, DNS, segurança e criptografia.',
    explanation: 'O projeto é um gerenciador de tarefas com cadastro, login, logout e tarefas privadas por usuário. O front-end usa HTML, CSS e JavaScript e consome uma API FastAPI. O back-end valida dados, autentica o usuário e autoriza cada operação. PostgreSQL persiste usuários e tarefas. Senhas são armazenadas com função de hash própria para senha. Segredos ficam em variáveis de ambiente. A publicação deve usar HTTPS e um banco de produção. Git e GitHub registram a evolução do projeto. O objetivo pedagógico é construir por etapas, não tentar fazer tudo de uma vez.',
    everyday: 'É a montagem final de um sistema completo: cada parte estudada durante o curso agora ocupa um lugar claro na arquitetura.',
    programming: 'Arquitetura: INTERNET → DOMÍNIO/DNS → HTTPS → SERVIDOR → FRONT-END/BACK-END → API → POSTGRESQL. O front-end nunca deve confiar apenas em esconder botões: o back-end deve validar que a tarefa realmente pertence ao usuário autenticado.',
    code: 'Tabelas:\nusuarios(id, nome, email, senha_hash, created_at)\ntarefas(id, usuario_id, titulo, descricao, status, created_at, updated_at)\n\nEndpoints:\nPOST /usuarios\nPOST /login\nGET /tarefas\nPOST /tarefas\nGET /tarefas/{id}\nPATCH /tarefas/{id}\nDELETE /tarefas/{id}',
    lineByLine: 'usuarios guarda identidade e hash de senha. tarefas referencia o dono por usuario_id. Os endpoints permitem cadastrar, autenticar e executar o CRUD. Toda leitura ou alteração de tarefa deve respeitar o usuário autenticado.',
    guided: 'Divida o projeto em sete etapas: banco, cadastro, login, CRUD no back-end, autorização, front-end e deploy.',
    exercise: 'Qual regra impede que o usuário A altere a tarefa do usuário B?',
    challenge: 'Escreva um checklist de conclusão contendo funcionalidade, segurança, banco, testes manuais, deploy, README e revisão final.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se eu esconder no front-end o botão de excluir tarefas de outras pessoas, a autorização está resolvida.”',
    common: 'Confiar apenas no front-end para segurança, guardar senha em texto puro, colocar segredo no Git e esquecer validação no servidor.',
    summary: 'O projeto final integra front-end, FastAPI, PostgreSQL, autenticação, autorização, segurança, HTTPS, deploy e versionamento.',
    task: 'Construir o projeto final por etapas e registrar no README a arquitetura, instalação local, variáveis necessárias sem valores secretos e instruções de execução.',
    video: '',
    hint1: 'Autorização é responsabilidade do servidor.',
    hint2: 'Ao buscar uma tarefa, filtre também pelo usuário autenticado ou aplique regra equivalente de autorização no back-end.',
    solution: 'O back-end deve verificar a identidade autenticada e permitir consultar/alterar/excluir apenas recursos pertencentes àquele usuário. Esconder controles no front-end melhora a interface, mas não oferece autorização.'
  }
);