window.PDZ_DATA.lessons.push(
  {
    id: 26, module: 2, title: 'Introdução à Programação Orientada a Objetos', time: '50–60 min',
    learn: ['O que é um paradigma de programação', 'O que são classe e objeto', 'Diferença entre dados e comportamentos', 'Modelagem simples de entidades'],
    importance: 'POO oferece uma forma de organizar programas relacionando dados e comportamentos. Ela é uma abordagem útil, mas não é a única forma correta de programar.',
    before: 'Você já sabe organizar programas com funções e trabalhar com estruturas como listas e dicionários.',
    explanation: 'Um paradigma é uma forma de pensar e estruturar programas. Na Programação Orientada a Objetos, agrupamos informações e comportamentos relacionados em entidades. Uma classe funciona como um modelo; um objeto é uma ocorrência criada a partir desse modelo. Os dados ficam associados ao objeto e os comportamentos representam ações que ele pode realizar.',
    everyday: 'Pense em uma ficha de aluno. A ideia de “Aluno” define quais informações e ações fazem sentido. Cada estudante real seria um objeto diferente, com seus próprios dados.',
    programming: 'Em vez de espalhar nome, idade e ações de um aluno pelo programa, podemos modelar a entidade Aluno e manter esses elementos relacionados.',
    code: 'class Aluno:\n    pass\n\naluno1 = Aluno()\nprint(aluno1)',
    lineByLine: 'class Aluno cria um modelo chamado Aluno. pass indica que a classe ainda não possui conteúdo. Aluno() cria uma instância. aluno1 guarda a referência para esse objeto.',
    guided: 'Liste três entidades de um sistema escolar e, para cada uma, escreva exemplos de dados e comportamentos que poderiam estar relacionados.',
    exercise: 'Explique com suas palavras a diferença entre classe e objeto. Depois dê um exemplo fora da programação.',
    challenge: 'Escolha uma entidade do cotidiano e descreva pelo menos três dados e duas ações que ela poderia ter em uma modelagem orientada a objetos.',
    findError: 'Afirmação: “POO é a única maneira correta de organizar qualquer programa.” Corrija essa ideia.',
    common: 'Pensar que classe e objeto são exatamente a mesma coisa ou que POO substitui todas as outras formas de organizar código.',
    summary: 'POO é um paradigma. Classes funcionam como modelos e objetos são instâncias criadas a partir delas. A ideia central é relacionar dados e comportamentos.',
    task: 'Fazer um mapa simples com as entidades Aluno, Turma e Curso, listando possíveis dados e comportamentos.', video: 'https://www.youtube.com/watch?v=dJyZmwLpxnE',
    hint1: 'Classe é o modelo; objeto é um exemplar criado a partir dele.', hint2: 'Pense em “molde” e “objeto produzido”, lembrando que é apenas uma analogia.', solution: 'Exemplo: classe Aluno representa o modelo; aluno1 e aluno2 podem ser objetos diferentes, cada um com seus próprios dados.'
  },
  {
    id: 27, module: 2, title: 'Classes e objetos', time: '50–60 min',
    learn: ['Sintaxe de class', 'Instâncias', 'Atributos simples', 'Criação de vários objetos'],
    importance: 'Criar classes e instâncias é a base prática para usar orientação a objetos em Python.',
    before: 'Você já entende que uma classe é um modelo e um objeto é uma instância criada a partir dela.',
    explanation: 'Em Python, usamos class para definir uma classe. Depois usamos o nome da classe seguido de parênteses para criar objetos. Cada objeto pode receber valores próprios em seus atributos, permitindo representar entidades diferentes a partir do mesmo modelo.',
    everyday: 'Um formulário padrão pode ser preenchido por várias pessoas. O modelo é o mesmo, mas cada formulário preenchido tem informações diferentes.',
    programming: 'Podemos criar dois objetos Aluno e atribuir nomes diferentes a cada um.',
    code: 'class Aluno:\n    pass\n\naluno1 = Aluno()\naluno2 = Aluno()\naluno1.nome = "Ana"\naluno2.nome = "Bruno"\nprint(aluno1.nome)\nprint(aluno2.nome)',
    lineByLine: 'A classe é criada uma vez. Aluno() cria duas instâncias distintas. O atributo nome recebe um valor diferente em cada objeto. Os dois prints mostram dados independentes.',
    guided: 'Crie uma classe Livro vazia, depois duas instâncias e atribua um título diferente a cada uma.',
    exercise: 'Crie uma classe Curso, duas instâncias e atribua nomes diferentes aos cursos. Mostre os valores com print().',
    challenge: 'Crie três objetos da classe Aluno e atribua nome e idade a cada um sem usar listas ainda.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nclass Aluno\n    pass',
    common: 'Esquecer os dois-pontos após class, confundir nome da classe com nome do objeto e achar que mudar um atributo de uma instância altera todas as outras.',
    summary: 'A classe define o modelo; instâncias são objetos independentes. Atributos guardam dados associados a cada objeto.',
    task: 'Criar uma classe simples e pelo menos três objetos com valores diferentes em seus atributos.', video: null,
    hint1: 'Comece com class Curso: seguido de pass.', hint2: 'Depois crie curso1 = Curso() e curso2 = Curso().', solution: 'class Curso:\n    pass\n\ncurso1 = Curso()\ncurso2 = Curso()\ncurso1.nome = "Python"\ncurso2.nome = "Lógica"\nprint(curso1.nome)\nprint(curso2.nome)'
  },
  {
    id: 28, module: 2, title: 'Atributos, métodos e self', time: '50–60 min',
    learn: ['O que é um atributo', 'O que é um método', 'O papel de self', 'Como um método usa dados da própria instância'],
    importance: 'Métodos permitem que objetos realizem ações relacionadas aos próprios dados, tornando a organização do código mais clara.',
    before: 'Você já sabe criar classes, instâncias e atributos simples.',
    explanation: 'Atributos representam dados ligados ao objeto. Métodos são funções definidas dentro da classe. Em métodos de instância, self referencia o próprio objeto que está usando o método. Por meio de self, o método pode acessar ou alterar os atributos daquela instância.',
    everyday: 'Uma ficha de aluno possui dados, como nome. Uma ação relacionada pode ser “apresentar-se”. O método usa os dados daquela ficha específica.',
    programming: 'Podemos criar um método apresentar() que mostre o nome guardado no próprio objeto.',
    code: 'class Aluno:\n    def apresentar(self):\n        print(f"Olá, meu nome é {self.nome}.")\n\naluno = Aluno()\naluno.nome = "Ana"\naluno.apresentar()',
    lineByLine: 'def apresentar(self) cria um método. self.nome acessa o atributo nome da própria instância. aluno.apresentar() chama o método usando o objeto aluno.',
    guided: 'Adicione a uma classe Livro um método mostrar_titulo() que exiba self.titulo.',
    exercise: 'Crie uma classe Pessoa com atributo nome e método cumprimentar() que mostre uma mensagem usando self.nome.',
    challenge: 'Crie um método alterar_nome() que receba um novo nome e atualize o atributo da própria instância.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nclass Aluno:\n    def apresentar():\n        print(self.nome)',
    common: 'Esquecer self no primeiro parâmetro do método, tentar usar self fora do contexto de uma instância e confundir método com função externa.',
    summary: 'Atributos guardam dados, métodos representam ações e self referencia a instância que está executando o método.',
    task: 'Criar uma classe com dois atributos definidos nas instâncias e dois métodos que usem self.', video: null,
    hint1: 'O primeiro parâmetro de um método de instância deve ser self.', hint2: 'Para acessar nome dentro do método, use self.nome.', solution: 'class Pessoa:\n    def cumprimentar(self):\n        print(f"Olá! Eu sou {self.nome}.")\n\npessoa = Pessoa()\npessoa.nome = "Ana"\npessoa.cumprimentar()'
  },
  {
    id: 29, module: 2, title: '__init__ e encapsulamento básico', time: '50–60 min',
    learn: ['Como funciona __init__', 'Inicialização de atributos', 'Atributos internos por convenção', 'Significado de _nome em Python'],
    importance: '__init__ ajuda a criar objetos já com os dados necessários e introduz uma forma mais organizada de controlar o estado inicial de cada instância.',
    before: 'Você já sabe usar atributos, métodos e self.',
    explanation: '__init__ é um método especial executado durante a criação do objeto. Ele costuma receber valores e atribuí-los à instância usando self. Um nome como _nome indica, por convenção, que o atributo é destinado ao uso interno da classe. Essa convenção não cria uma barreira rígida de privacidade em Python.',
    everyday: 'Ao preencher uma ficha no momento do cadastro, ela já nasce com os dados principais completos em vez de receber cada informação separadamente depois.',
    programming: 'Podemos exigir o nome ao criar Aluno("Ana") e armazená-lo em self._nome.',
    code: 'class Aluno:\n    def __init__(self, nome):\n        self._nome = nome\n\n    def apresentar(self):\n        print(f"Aluno: {self._nome}")\n\naluno = Aluno("Ana")\naluno.apresentar()',
    lineByLine: '__init__ recebe self e nome. self._nome guarda o valor no objeto. O sublinhado é uma convenção de uso interno. Aluno("Ana") chama a inicialização e cria o objeto com o nome definido.',
    guided: 'Crie uma classe Produto com __init__(self, nome, preco) e um método mostrar() que exiba esses dados.',
    exercise: 'Crie uma classe Livro que receba titulo e autor no __init__ e possua um método descricao().',
    challenge: 'Altere um exemplo antigo que atribuía atributos após criar o objeto para que passe a usar __init__.',
    findError: 'Afirmação: “Um atributo chamado _nome é completamente privado e impossível de acessar fora da classe.” Corrija.',
    common: 'Esquecer self no __init__, esquecer de atribuir self.atributo = parametro e interpretar o sublinhado como proteção absoluta.',
    summary: '__init__ prepara o estado inicial do objeto. A convenção _nome comunica intenção de uso interno, mas não impõe privacidade rígida.',
    task: 'Criar duas classes simples usando __init__ e pelo menos um método em cada uma.', video: null,
    hint1: 'Receba os valores como parâmetros no __init__.', hint2: 'Guarde cada valor com self.titulo = titulo e self.autor = autor.', solution: 'class Livro:\n    def __init__(self, titulo, autor):\n        self.titulo = titulo\n        self.autor = autor\n\n    def descricao(self):\n        print(f"{self.titulo} — {self.autor}")'
  },
  {
    id: 30, module: 2, title: 'Projeto com POO — Sistema Escolar', time: '50–60 min',
    learn: ['Aplicar classe, objeto, atributo e método em conjunto', 'Usar self e __init__ em um projeto', 'Distribuir responsabilidades entre Aluno, Turma e Curso', 'Comparar organização funcional e orientada a objetos'],
    importance: 'O projeto mostra na prática por que classes podem ajudar a organizar responsabilidades em um programa com várias entidades relacionadas.',
    before: 'Você já estudou paradigma, classes, objetos, atributos, métodos, self e __init__.',
    explanation: 'Nesta etapa, você reorganiza partes do Sistema Escolar do Módulo 1 em classes. Aluno representa dados e ações de um estudante; Turma agrupa alunos; Curso representa informações do curso. O objetivo não é criar uma arquitetura complexa, mas perceber como responsabilidades podem ficar agrupadas em entidades.',
    everyday: 'Em uma escola real, estudante, turma e curso têm papéis diferentes. Separar essas responsabilidades ajuda a entender quem deve guardar cada informação e executar cada ação.',
    programming: 'A classe Aluno pode calcular sua média, enquanto Turma pode manter uma lista de alunos e Curso pode guardar nome e descrição.',
    code: 'class Aluno:\n    def __init__(self, nome, notas):\n        self.nome = nome\n        self.notas = notas\n\n    def calcular_media(self):\n        return sum(self.notas) / len(self.notas)\n\nclass Turma:\n    def __init__(self, nome):\n        self.nome = nome\n        self.alunos = []\n\n    def adicionar_aluno(self, aluno):\n        self.alunos.append(aluno)\n\nclass Curso:\n    def __init__(self, nome):\n        self.nome = nome',
    lineByLine: 'Aluno guarda nome e notas e possui comportamento para calcular média. Turma guarda seu nome e uma lista de alunos, além do método para adicionar objetos Aluno. Curso começa com uma responsabilidade simples: guardar seu nome.',
    guided: 'Implemente primeiro Aluno e teste com um único objeto. Depois crie Turma e adicione esse aluno. Só então inclua Curso.',
    exercise: 'Crie dois alunos, adicione ambos a uma turma e mostre o nome e a média de cada um percorrendo turma.alunos.',
    challenge: 'Acrescente um método listar_alunos() à classe Turma sem introduzir conceitos além dos já estudados.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nclass Turma:\n    alunos = []\nExplique por que, neste projeto introdutório, é mais claro inicializar a lista em self.alunos dentro de __init__.',
    common: 'Criar classes demais, misturar responsabilidades sem necessidade, esquecer de usar objetos Aluno dentro de Turma e transformar POO em código mais complicado do que o problema exige.',
    summary: 'Classes ajudam a agrupar dados e comportamentos relacionados. O projeto usa Aluno, Turma e Curso para revisar os fundamentos de POO sem avançar para conceitos mais complexos.',
    task: 'Concluir o Sistema Escolar com Aluno, Turma e Curso e fazer o Checkpoint 2 das Aulas 26–30.', video: 'https://www.youtube.com/watch?v=dJyZmwLpxnE',
    hint1: 'Faça o projeto em etapas: primeiro Aluno, depois Turma, depois Curso.', hint2: 'Use uma lista em self.alunos e append() para guardar objetos Aluno.', solution: 'aluno1 = Aluno("Ana", [8, 9])\naluno2 = Aluno("Bruno", [7, 6])\nturma = Turma("Turma A")\nturma.adicionar_aluno(aluno1)\nturma.adicionar_aluno(aluno2)\nfor aluno in turma.alunos:\n    print(aluno.nome, aluno.calcular_media())'
  }
);
