(() => {
  const lessons = [
    {
      id: 21, module: 2, title: 'Organizando programas com funções', time: '50–60 min',
      learn: ['Divisão de problemas', 'Responsabilidade de funções', 'Reutilização', 'Organização do código', 'Refatoração básica'],
      importance: 'Quando um programa cresce, separar tarefas em funções pequenas torna o código mais fácil de entender, testar e modificar.',
      before: 'Você já sabe criar funções com def, usar parâmetros, argumentos e return.',
      explanation: 'Refatorar é melhorar a organização do código sem mudar o resultado esperado. Uma boa função costuma ter uma responsabilidade clara. Em vez de deixar menu, cálculos e mensagens misturados, podemos separar cada parte em funções com nomes que expliquem o que fazem.',
      everyday: 'Em uma escola, secretaria, professores e direção têm responsabilidades diferentes. No código, funções também podem dividir responsabilidades.',
      programming: 'Um programa de médias pode separar a exibição do menu, o cálculo e a apresentação do resultado.',
      code: 'def mostrar_menu():\n    print("1 - Calcular média")\n    print("0 - Sair")\n\ndef calcular_media(n1, n2):\n    return (n1 + n2) / 2\n\ndef exibir_resultado(media):\n    print(f"Média: {media}")',
      lineByLine: 'mostrar_menu() cuida apenas do menu. calcular_media() recebe dados e devolve o cálculo com return. exibir_resultado() cuida apenas da saída. Essa separação reduz repetição e deixa cada parte mais clara.',
      guided: 'Pegue um programa antigo seu e identifique duas partes que poderiam virar funções separadas.',
      exercise: 'Crie as funções saudacao(nome) e dobro(numero). A primeira deve mostrar uma mensagem; a segunda deve retornar o dobro.',
      challenge: 'Refatore uma calculadora anterior separando leitura, cálculo e exibição em funções.',
      findError: 'Uma função chamada calcular_media() também imprime menu, pede nome e encerra o programa. Qual é o problema de organização?',
      common: 'Criar funções grandes demais, repetir código fora delas e usar nomes vagos como funcao1.',
      summary: 'Funções pequenas e com responsabilidades claras ajudam a organizar programas maiores e favorecem reutilização.',
      task: 'Refatorar um programa antigo usando pelo menos três funções com responsabilidades diferentes.', video: null,
      hint1: 'Comece identificando tarefas diferentes no programa.', hint2: 'Use return quando a função precisar devolver um resultado.', solution: 'def saudacao(nome):\n    print(f"Olá, {nome}!")\n\ndef dobro(numero):\n    return numero * 2'
    },
    {
      id: 22, module: 2, title: 'Módulos e import', time: '50–60 min',
      learn: ['O que é um módulo', 'import', 'Biblioteca padrão', 'Módulos próprios', 'Múltiplos arquivos'],
      importance: 'Dividir o código em arquivos facilita organização e reutilização quando o projeto começa a crescer.',
      before: 'Você já sabe criar funções e organizar responsabilidades.',
      explanation: 'Um módulo Python é, de forma simples, um arquivo .py que pode conter funções, variáveis e outros elementos reutilizáveis. import permite usar elementos de outro módulo. Python também possui uma biblioteca padrão com módulos prontos, como math.',
      everyday: 'É como separar materiais por pastas: cada arquivo tem um assunto e você abre o que precisa quando vai usar.',
      programming: 'Podemos colocar funções matemáticas em calculos.py e utilizá-las em main.py.',
      code: '# calculos.py\ndef somar(a, b):\n    return a + b\n\n# main.py\nimport calculos\n\nresultado = calculos.somar(10, 5)\nprint(resultado)',
      lineByLine: 'calculos.py define somar(). Em main.py, import calculos carrega o módulo. calculos.somar(...) chama a função usando o nome do módulo como referência.',
      guided: 'Crie dois arquivos, calculos.py e main.py, e teste uma função importada.',
      exercise: 'Crie um módulo mensagens.py com uma função boas_vindas(nome) e use essa função em outro arquivo.',
      challenge: 'Separe uma calculadora simples em um arquivo com funções e outro arquivo responsável pela execução.',
      findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nimport calculo\n# O arquivo existente se chama calculos.py. O que precisa ser corrigido?',
      common: 'Errar o nome do arquivo, misturar responsabilidades e achar que import copia visualmente o conteúdo de um arquivo para outro.',
      summary: 'Módulos ajudam a dividir programas em arquivos. import permite reutilizar código de módulos próprios e da biblioteca padrão.',
      task: 'Criar um pequeno projeto com main.py e pelo menos um módulo próprio.', video: null,
      hint1: 'O nome usado no import deve corresponder ao arquivo sem .py.', hint2: 'Mantenha as funções reutilizáveis no módulo e a execução principal em main.py.', solution: '# mensagens.py\ndef boas_vindas(nome):\n    print(f"Bem-vinda, {nome}!")\n\n# main.py\nimport mensagens\nmensagens.boas_vindas("Júlia")'
    },
    {
      id: 23, module: 2, title: 'Arquivos', time: '50–60 min',
      learn: ['Arquivos de texto', 'with open()', 'encoding UTF-8', 'Leitura e escrita', 'Modos r, w e a'],
      importance: 'Até aqui, os dados somem quando o programa termina. Arquivos permitem guardar informações de forma persistente.',
      before: 'Você já sabe trabalhar com strings, listas, funções e módulos.',
      explanation: 'open() abre um arquivo. Com with, o Python cuida do fechamento ao sair do bloco. O modo r lê, w escreve substituindo o conteúdo existente e a acrescenta ao final. encoding="utf-8" ajuda a lidar corretamente com acentos e caracteres do português.',
      everyday: 'É como um caderno: você pode ler o que já está escrito, substituir uma página ou acrescentar uma nova anotação.',
      programming: 'Podemos criar um arquivo de anotações e depois ler seu conteúdo.',
      code: 'with open("anotacoes.txt", "w", encoding="utf-8") as arquivo:\n    arquivo.write("Primeira anotação\\n")\n\nwith open("anotacoes.txt", "r", encoding="utf-8") as arquivo:\n    conteudo = arquivo.read()\n    print(conteudo)',
      lineByLine: 'O primeiro bloco abre anotacoes.txt para escrita. write() grava texto. O segundo bloco abre o mesmo arquivo para leitura, read() recupera o conteúdo e print() mostra na tela.',
      guided: 'Crie apenas um arquivo de exercício chamado anotacoes.txt e teste primeiro w, depois r e por fim a.',
      exercise: 'Grave seu nome em estudo.txt e depois acrescente uma segunda linha usando o modo a.',
      challenge: 'Crie um programa que registre três tarefas em um arquivo e depois mostre tudo na tela.',
      findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nwith open("anotacoes.txt", "w", encoding="utf-8") as arquivo:\n    print(arquivo.read())\nPor que esse modo não é adequado para leitura?',
      common: 'Usar w sem perceber que ele pode substituir conteúdo, esquecer encoding e tentar ler de um arquivo que não existe.',
      summary: 'r lê, w escreve substituindo e a acrescenta. with open(...) é a forma recomendada para abrir arquivos neste curso.',
      task: 'Criar um diário de estudo simples em arquivo de texto usando w, a e r. Use somente arquivos criados para este exercício.', video: null,
      hint1: 'Use w apenas na primeira gravação.', hint2: 'Para manter o conteúdo e acrescentar, use a.', solution: 'with open("estudo.txt", "w", encoding="utf-8") as arquivo:\n    arquivo.write("Júlia\\n")\n\nwith open("estudo.txt", "a", encoding="utf-8") as arquivo:\n    arquivo.write("Estudando arquivos em Python\\n")'
    },
    {
      id: 24, module: 2, title: 'JSON', time: '50–60 min',
      learn: ['O que é JSON', 'Serialização', 'Desserialização', 'json.dump()', 'json.load()', 'Dicionário Python ≠ JSON'],
      importance: 'JSON é um formato textual muito usado para guardar e trocar dados estruturados entre sistemas.',
      before: 'Você já sabe usar listas, dicionários, módulos e arquivos.',
      explanation: 'Um dicionário é uma estrutura que existe dentro do Python. JSON é um formato de texto. Serializar significa transformar dados do programa em uma representação que pode ser armazenada; desserializar é fazer o caminho de volta. O módulo json oferece dump() para gravar e load() para ler.',
      everyday: 'Pense em uma ficha de cadastro: no programa ela está organizada como estrutura Python; ao salvar em JSON, vira uma representação textual padronizada.',
      programming: 'Podemos salvar uma lista de contatos, cada um representado por um dicionário, em dados.json.',
      code: 'import json\n\ncontatos = [{"nome": "Ana", "telefone": "1234"}]\n\nwith open("dados.json", "w", encoding="utf-8") as arquivo:\n    json.dump(contatos, arquivo, ensure_ascii=False, indent=2)\n\nwith open("dados.json", "r", encoding="utf-8") as arquivo:\n    contatos_carregados = json.load(arquivo)\n\nprint(contatos_carregados)',
      lineByLine: 'import json carrega o módulo. dump() transforma e grava os dados no arquivo. ensure_ascii=False preserva caracteres legíveis. load() lê o JSON e recria estruturas Python equivalentes.',
      guided: 'Salve uma lista com dois dicionários simples em um arquivo JSON e carregue-a novamente.',
      exercise: 'Crie uma lista de livros com titulo e autor, salve em livros.json e depois leia o arquivo.',
      challenge: 'Adapte um cadastro simples para carregar os dados ao iniciar e salvar novamente depois de adicionar um item.',
      findError: 'Afirmação: “Um dicionário Python e um arquivo JSON são exatamente a mesma coisa.” Explique o erro.',
      common: 'Confundir formato JSON com dicionário Python, esquecer import json e tentar usar json.load() em conteúdo que não é JSON válido.',
      summary: 'Dicionário é estrutura Python; JSON é formato textual. dump() salva e load() recupera dados estruturados.',
      task: 'Criar uma lista de contatos e persistir os dados em contatos.json.', video: null,
      hint1: 'Use uma lista de dicionários.', hint2: 'Abra o arquivo com encoding="utf-8" e use json.dump() para salvar.', solution: 'import json\n\nlivros = [{"titulo": "Livro A", "autor": "Autora A"}]\nwith open("livros.json", "w", encoding="utf-8") as arquivo:\n    json.dump(livros, arquivo, ensure_ascii=False, indent=2)\nwith open("livros.json", "r", encoding="utf-8") as arquivo:\n    print(json.load(arquivo))'
    },
    {
      id: 25, module: 2, title: 'Erros e exceções', time: '50–60 min',
      learn: ['Erro e exceção', 'Traceback', 'try e except', 'else e finally', 'Tratamento específico'],
      importance: 'Programas reais recebem entradas inesperadas e encontram problemas. Tratar exceções permite responder de forma controlada sem esconder erros importantes.',
      before: 'Você já sabe receber dados com input(), converter tipos e trabalhar com arquivos.',
      explanation: 'Uma exceção acontece quando algo impede uma operação de continuar normalmente. O traceback mostra onde o problema ocorreu. try envolve o trecho que pode falhar; except trata uma exceção específica; else executa quando não houve exceção; finally executa ao final da tentativa, com ou sem erro.',
      everyday: 'Ao preencher um formulário de idade com letras, o sistema pode explicar que o valor é inválido em vez de simplesmente parar.',
      programming: 'Podemos tratar ValueError quando int() recebe algo que não representa um inteiro.',
      code: 'try:\n    numero = int(input("Digite um número: "))\nexcept ValueError:\n    print("Digite um número inteiro válido.")\nelse:\n    print(f"Você digitou {numero}.")\nfinally:\n    print("Fim da tentativa.")',
      lineByLine: 'O código dentro de try é tentado. Se ocorrer ValueError, o except correspondente é executado. Se não ocorrer, entra no else. finally executa ao final em ambos os casos.',
      guided: 'Execute o exemplo primeiro com 10 e depois com abc. Observe qual bloco roda em cada caso.',
      exercise: 'Crie um programa que peça um número inteiro e trate apenas ValueError com uma mensagem clara.',
      challenge: 'Crie uma divisão de dois números e trate ValueError e ZeroDivisionError separadamente.',
      findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\ntry:\n    idade = int(input("Idade: "))\nexcept:\n    print("Deu algum erro")\nPor que um except genérico não é uma boa escolha didática aqui?',
      common: 'Usar except genérico, esconder erros que deveriam ser investigados e achar que tratamento de exceção substitui validação e lógica correta.',
      summary: 'Exceções devem ser entendidas e, quando possível, tratadas especificamente. try, except, else e finally controlam caminhos diferentes da tentativa.',
      task: 'Fazer o checkpoint das Aulas 21–25 e criar um gerenciador de contatos simples com persistência em JSON e tratamento específico de erros.', video: 'https://www.youtube.com/watch?v=xz2B3bfNjEk',
      hint1: 'Para entrada inteira inválida, trate ValueError.', hint2: 'Na divisão, trate ZeroDivisionError separadamente de ValueError.', solution: 'try:\n    a = float(input("Primeiro número: "))\n    b = float(input("Segundo número: "))\n    resultado = a / b\nexcept ValueError:\n    print("Digite apenas números válidos.")\nexcept ZeroDivisionError:\n    print("Não é possível dividir por zero.")\nelse:\n    print(f"Resultado: {resultado}")'
    }
  ];

  window.PDZ_DATA.lessons.push(...lessons);
})();
