window.PDZ_DATA.lessons.push(
  {
    id: 111, module: 11, title: 'Tríade CIA e fundamentos de segurança', time: '50–60 min',
    learn: ['segurança da informação', 'ativo', 'confidencialidade', 'integridade', 'disponibilidade', 'controle', 'incidente'],
    importance: 'Segurança não é apenas impedir invasões. Também envolve proteger informações, evitar alterações indevidas e manter serviços disponíveis para quem precisa.',
    before: 'Você já estudou aplicações web, redes, Linux, deploy e bancos de dados.',
    explanation: 'A tríade CIA organiza três objetivos centrais da segurança da informação. Confidencialidade significa impedir acesso indevido a informações. Integridade significa evitar alteração ou destruição não autorizada e preservar a confiabilidade dos dados. Disponibilidade significa manter sistemas e informações acessíveis quando pessoas autorizadas precisam deles. Um ativo é algo de valor, como dados, código, credenciais ou um serviço. Controles são medidas usadas para reduzir riscos, e um incidente é um evento que compromete ou ameaça a segurança.',
    everyday: 'Em uma escola, notas devem ser vistas apenas por pessoas autorizadas, não podem ser alteradas indevidamente e precisam estar disponíveis no período de fechamento.',
    programming: 'Pense em um sistema escolar: controle de acesso protege confidencialidade; validações, histórico e restrições ajudam na integridade; backups, monitoramento e infraestrutura adequada ajudam na disponibilidade.',
    code: 'Confidencialidade → quem pode acessar?\nIntegridade       → os dados continuam corretos?\nDisponibilidade   → o serviço está acessível quando necessário?',
    lineByLine: 'As três perguntas representam objetivos diferentes. Uma aplicação pode estar disponível e ainda assim vazar dados; pode ser confidencial e sofrer alteração indevida; segurança exige considerar as três dimensões.',
    guided: 'Escolha um aplicativo e identifique um exemplo de confidencialidade, integridade e disponibilidade.',
    exercise: 'Uma pessoa sem permissão consegue ver dados privados de outro usuário. Qual objetivo da tríade foi violado principalmente?',
    challenge: 'Dê um exemplo em que disponibilidade e integridade entrem em tensão e explique como um projeto poderia equilibrar os dois objetivos.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se ninguém roubou a senha, então não existe problema de segurança.”',
    common: 'Reduzir segurança apenas a senhas ou ataques externos.',
    summary: 'Confidencialidade protege contra acesso indevido; integridade protege a correção e confiabilidade dos dados; disponibilidade garante acesso quando necessário.',
    task: 'Criar uma tabela com três ativos do seu projeto e relacionar cada um à tríade CIA.',
    video: '',
    hint1: 'Pergunte quem teve acesso ao dado.',
    hint2: 'Acesso indevido está ligado principalmente à confidencialidade.',
    solution: 'Principalmente confidencialidade, porque informação privada foi acessada por quem não tinha autorização.'
  },
  {
    id: 112, module: 11, title: 'Ativo, ameaça, vulnerabilidade, risco e controle', time: '50–60 min',
    learn: ['ativo', 'ameaça', 'vulnerabilidade', 'risco', 'controle', 'incidente'],
    importance: 'Pensar em segurança exige separar o que precisa ser protegido, o que pode dar errado, quais fraquezas existem e quais medidas reduzem o risco.',
    before: 'Você conhece a tríade CIA e o conceito de ativo.',
    explanation: 'Ativo é algo de valor. Ameaça é algo que pode causar dano. Vulnerabilidade é uma fraqueza que pode ser explorada ou contribuir para um problema. Risco combina a possibilidade de uma ameaça afetar um ativo e o impacto desse evento. Controle é uma medida preventiva, detectiva ou corretiva usada para reduzir o risco. Incidente é um evento real de segurança, não apenas uma possibilidade.',
    everyday: 'Um celular é um ativo; perda ou roubo é uma ameaça; ausência de bloqueio de tela é uma vulnerabilidade; exposição dos dados é um risco; senha forte, criptografia e backup são controles.',
    programming: 'Em uma aplicação, um banco com dados pessoais é um ativo. Uma configuração pública indevida pode ser uma vulnerabilidade. Um controle pode ser limitar acesso pela rede e exigir autenticação adequada.',
    code: 'Ativo → Banco de dados\nAmeaça → acesso indevido\nVulnerabilidade → configuração excessivamente permissiva\nRisco → exposição dos dados\nControle → restringir acesso + autenticação + monitoramento',
    lineByLine: 'O exemplo separa causa potencial, fraqueza e consequência. Essa separação ajuda a escolher controles adequados.',
    guided: 'Escolha um ativo do projeto e descreva uma ameaça, uma vulnerabilidade possível e um controle defensivo.',
    exercise: 'Qual é a diferença entre vulnerabilidade e incidente?',
    challenge: 'Explique por que risco não depende apenas da existência de uma vulnerabilidade, mas também de contexto e impacto.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Vulnerabilidade e incidente são exatamente a mesma coisa.”',
    common: 'Confundir fraqueza existente com evento de segurança já ocorrido.',
    summary: 'Ativos têm valor; ameaças podem causar dano; vulnerabilidades são fraquezas; riscos representam possíveis perdas; controles reduzem riscos.',
    task: 'Montar um mini registro de riscos com três linhas: ativo, risco e controle.',
    video: '',
    hint1: 'Vulnerabilidade é uma condição ou fraqueza.',
    hint2: 'Incidente é um evento que realmente ocorreu ou está ocorrendo.',
    solution: 'Vulnerabilidade é uma fraqueza que pode favorecer um problema. Incidente é um evento real que compromete ou ameaça a segurança.'
  },
  {
    id: 113, module: 11, title: 'Autenticação, autorização, sessões e tokens', time: '55–60 min',
    learn: ['autenticação', 'autorização', 'sessão', 'token', 'menor privilégio'],
    importance: 'Uma aplicação precisa saber quem é o usuário e, separadamente, decidir o que ele pode fazer.',
    before: 'Você já conhece HTTP, APIs e o conceito de usuário em aplicações.',
    explanation: 'Autenticação confirma a identidade apresentada por alguém, por exemplo após um login. Autorização verifica se uma identidade autenticada pode executar uma ação ou acessar um recurso. Sessões e tokens são mecanismos usados para manter ou representar estado de autenticação, mas sua implementação segura exige bibliotecas e padrões confiáveis. O princípio do menor privilégio diz que cada identidade deve receber apenas as permissões necessárias. A autorização deve ser verificada no servidor; esconder um botão no front-end não protege um endpoint.',
    everyday: 'Mostrar um crachá na entrada confirma quem você é; ter permissão para entrar em uma sala específica é uma decisão de autorização diferente.',
    programming: 'Em uma API de tarefas, um usuário autenticado deve poder alterar apenas suas próprias tarefas. O back-end precisa verificar o proprietário do recurso antes de autorizar PATCH ou DELETE.',
    code: 'Autenticação: “Quem é você?”\nAutorização: “Você pode fazer isto?”\n\nRegra defensiva:\nservidor verifica usuário + recurso + permissão',
    lineByLine: 'Primeiro a aplicação identifica a pessoa ou serviço. Depois, em cada operação sensível, verifica a permissão aplicável. O front-end pode melhorar a interface, mas não substitui a validação do servidor.',
    guided: 'Descreva a diferença entre login e permissão para excluir uma tarefa.',
    exercise: 'Um usuário está logado, mas tenta editar a tarefa de outra pessoa. O problema é de autenticação ou autorização?',
    challenge: 'Explique por que esconder o botão “Excluir” no navegador não é um controle suficiente.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se o usuário está autenticado, ele pode acessar qualquer recurso da aplicação.”',
    common: 'Tratar autenticação como autorização automática e confiar apenas no front-end.',
    summary: 'Autenticação identifica; autorização decide permissões; sessões/tokens ajudam a representar autenticação; o servidor deve aplicar autorização.',
    task: 'Desenhar o fluxo login → autenticação → requisição → autorização → recurso.',
    video: '',
    hint1: 'O usuário já está identificado.',
    hint2: 'A dúvida é se ele tem permissão para aquele recurso específico.',
    solution: 'É um problema de autorização: a identidade está autenticada, mas não deveria ter permissão para editar o recurso de outra pessoa.'
  },
  {
    id: 114, module: 11, title: 'Práticas de desenvolvimento seguro', time: '60 min',
    learn: ['validação', 'autorização no servidor', 'menor privilégio', 'segredos', 'dependências', 'logs', 'backups', 'erros seguros', 'SQL parametrizado', 'XSS'],
    importance: 'Muitos problemas de segurança são reduzidos por decisões de desenvolvimento e operação consistentes, não por uma única ferramenta.',
    before: 'Você entende riscos, autenticação e autorização.',
    explanation: 'Desenvolvimento seguro envolve várias camadas: validar entradas no servidor, aplicar autorização em cada operação sensível, conceder apenas permissões necessárias, manter segredos fora do código e do Git, atualizar dependências, registrar eventos úteis sem expor dados sensíveis, testar restauração de backups e retornar mensagens de erro que ajudem o usuário sem revelar detalhes internos. Consultas SQL devem usar parâmetros em vez de concatenar entrada do usuário. No navegador, conteúdo não confiável deve ser tratado com APIs e mecanismos de saída seguros para reduzir risco de XSS.',
    everyday: 'É como segurança de um prédio: fechadura, identificação, permissões, alarmes, manutenção e plano de recuperação atuam em conjunto.',
    programming: 'Ao buscar um aluno por email, passe o valor como parâmetro da consulta. Ao mostrar texto fornecido por usuário no navegador, prefira textContent quando você quer texto, em vez de montar HTML não confiável.',
    code: 'SQL parametrizado (conceito):\ncursor.execute("SELECT id, nome FROM usuarios WHERE email = %s", (email,))\n\nDOM para texto:\nelemento.textContent = textoDoUsuario;',
    lineByLine: 'No SQL, a entrada é enviada separadamente da estrutura da consulta. No DOM, textContent trata o valor como texto em vez de interpretá-lo como HTML.',
    guided: 'Revise um fluxo de cadastro e liste validações, autorização, proteção de segredos e logs necessários.',
    exercise: 'Por que concatenar diretamente entrada do usuário em uma consulta SQL é uma prática insegura?',
    challenge: 'Crie um checklist defensivo de dez itens para antes de publicar uma API.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nquery = "SELECT * FROM usuarios WHERE email = \'" + email + "\'"',
    common: 'Achar que validação do front-end é suficiente ou que logs devem registrar tudo, inclusive senhas e tokens.',
    summary: 'Segurança depende de validação, autorização, menor privilégio, proteção de segredos, dependências atualizadas, logs adequados, backups e tratamento seguro de dados.',
    task: 'Criar um checklist “antes do deploy” com práticas defensivas desta aula.',
    video: '',
    hint1: 'A entrada não confiável não deve virar parte da estrutura SQL.',
    hint2: 'Use parâmetros fornecidos pelo driver do banco.',
    solution: 'Concatenação pode fazer a entrada alterar a estrutura pretendida da consulta. Consultas parametrizadas separam dados da instrução SQL e são o padrão defensivo.'
  },
  {
    id: 115, module: 11, title: 'OWASP Top 10:2025', time: '60 min',
    learn: ['OWASP', 'Top 10', 'Broken Access Control', 'Security Misconfiguration', 'Supply Chain', 'Cryptographic Failures', 'Injection', 'Insecure Design', 'Authentication Failures', 'Integrity Failures', 'Logging and Alerting', 'Exceptional Conditions'],
    importance: 'O OWASP Top 10 é um documento de conscientização amplamente usado para organizar classes importantes de riscos em aplicações web.',
    before: 'Você já conhece fundamentos de risco e práticas defensivas.',
    explanation: 'A edição 2025 organiza dez categorias: A01 Broken Access Control; A02 Security Misconfiguration; A03 Software Supply Chain Failures; A04 Cryptographic Failures; A05 Injection; A06 Insecure Design; A07 Authentication Failures; A08 Software or Data Integrity Failures; A09 Security Logging and Alerting Failures; A10 Mishandling of Exceptional Conditions. O objetivo desta aula é reconhecer categorias de risco e pensar em prevenção, não aprender a explorar sistemas.',
    everyday: 'Uma lista de categorias ajuda uma equipe a lembrar áreas que precisam ser consideradas durante projeto, desenvolvimento, revisão e operação.',
    programming: 'Exemplos defensivos: verificar propriedade de recursos para reduzir Broken Access Control; configurar serviços com mínimos acessos necessários; manter dependências e origem de pacotes sob controle; usar criptografia por bibliotecas confiáveis; usar consultas parametrizadas; projetar autorização desde o início; proteger login; validar atualizações e artefatos; criar logs e alertas úteis; tratar falhas de forma previsível e segura.',
    code: 'A01 Acesso\nA02 Configuração\nA03 Cadeia de suprimentos\nA04 Criptografia\nA05 Injeção\nA06 Design inseguro\nA07 Autenticação\nA08 Integridade de software/dados\nA09 Logs e alertas\nA10 Condições excepcionais',
    lineByLine: 'Cada categoria agrupa uma família de problemas. A lista não substitui análise de risco nem garante segurança completa; ela funciona como referência de conscientização.',
    guided: 'Associe três práticas da Aula 114 a categorias do OWASP Top 10:2025.',
    exercise: 'Qual categoria está mais diretamente relacionada a um usuário conseguir acessar um recurso de outro usuário sem permissão?',
    challenge: 'Escolha três categorias e proponha controles defensivos para uma aplicação de tarefas.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se uma aplicação resolveu os dez itens do OWASP Top 10, então ela está completamente segura.”',
    common: 'Tratar o Top 10 como checklist completo de certificação ou como catálogo de técnicas ofensivas.',
    summary: 'OWASP Top 10:2025 reúne dez categorias importantes de risco. Use-o como referência defensiva junto com análise de risco, testes e boas práticas.',
    task: 'Criar uma tabela com as dez categorias e uma medida defensiva simples para cada uma.',
    video: '',
    hint1: 'Pense em quem pode acessar qual recurso.',
    hint2: 'A categoria A01 trata de controle de acesso quebrado.',
    solution: 'A01:2025 — Broken Access Control.'
  }
);