window.PDZ_DATA.lessons.push(
  {
    id: 36, module: 3, title: 'Como funciona uma página web', time: '50–60 min',
    learn: ['O que são navegador, página, site e aplicação web', 'O que significa front-end', 'O papel de HTML, CSS e JavaScript'],
    importance: 'Antes de criar páginas, você precisa entender o papel de cada tecnologia e como elas trabalham juntas no navegador.',
    before: 'Você já estudou lógica, Python, terminal, Git e GitHub. Agora começa a parte visual da web.',
    explanation: 'O navegador é o programa que interpreta e exibe páginas web. Uma página web é um documento acessado pelo navegador. Um site é um conjunto de páginas relacionadas. Uma aplicação web é um sistema acessado pelo navegador que oferece interação e funcionalidades. Front-end é a parte da aplicação com a qual a pessoa interage diretamente. HTML organiza a estrutura do conteúdo, CSS define a apresentação visual e JavaScript adiciona comportamento e interatividade. HTML e CSS não são linguagens de programação; JavaScript é uma linguagem de programação.',
    everyday: 'Pense em uma casa: a estrutura lembra o papel do HTML, a pintura e decoração lembram o CSS, e mecanismos como interruptores e portas automáticas lembram o JavaScript. É apenas uma analogia para separar responsabilidades.',
    programming: 'Uma página pode ter um título em HTML, receber cores e espaçamentos em CSS e responder a um clique de botão com JavaScript.',
    code: '<h1>Meu primeiro site</h1>\n<button>Continuar</button>',
    lineByLine: 'A primeira linha cria um título principal. A segunda cria um botão. Neste momento estamos apenas observando a estrutura HTML; estilo e comportamento serão estudados depois.',
    guided: 'Abra um site que você usa e tente identificar visualmente quais partes parecem conteúdo, quais parecem apresentação e quais dependem de interação.',
    exercise: 'Explique com suas palavras a diferença entre página web, site e aplicação web. Depois diga qual é o papel principal de HTML, CSS e JavaScript.',
    challenge: 'Desenhe em papel ou descreva uma página simples e separe o que seria estrutura, apresentação e interatividade.',
    findError: 'Afirmação: “HTML é uma linguagem de programação usada para criar toda a lógica de um site.” Corrija.',
    common: 'Confundir internet com navegador, site com uma única página e afirmar que HTML e CSS são linguagens de programação.',
    summary: 'O navegador exibe páginas. HTML estrutura, CSS apresenta e JavaScript adiciona comportamento. Juntos, eles formam a base do front-end web.',
    task: 'Criar um esquema com navegador → página web → HTML/CSS/JavaScript e explicar o papel de cada item.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'Pense em uma página como uma parte e em um site como um conjunto.',
    hint2: 'Associe estrutura a HTML, aparência a CSS e interação a JavaScript.',
    solution: 'Página web é um documento exibido no navegador. Site é um conjunto de páginas relacionadas. Aplicação web oferece funcionalidades e interação pelo navegador. HTML estrutura o conteúdo, CSS cuida da apresentação e JavaScript adiciona comportamento.'
  },
  {
    id: 37, module: 3, title: 'Estrutura de um documento HTML', time: '50–60 min',
    learn: ['DOCTYPE', 'html, head e body', 'meta e title', 'Tags, elementos e atributos'],
    importance: 'Uma estrutura correta torna o documento previsível para navegadores e cria uma base sólida para acessibilidade, estilo e interatividade.',
    before: 'Você já sabe que HTML organiza a estrutura de uma página web.',
    explanation: 'HTML significa HyperText Markup Language, uma linguagem de marcação. Tags são marcações como <h1>. Um elemento normalmente inclui tag de abertura, conteúdo e tag de fechamento. Atributos fornecem informações adicionais, como lang="pt-BR". <!doctype html> informa ao navegador o padrão moderno do HTML. <html> envolve o documento. <head> contém metadados e configurações que não são o conteúdo principal visível. <body> contém o conteúdo apresentado na página.',
    everyday: 'Pense em um documento acadêmico: há informações de identificação e configuração, além do conteúdo propriamente dito. O head e o body cumprem papéis diferentes de organização.',
    programming: 'Vamos criar o esqueleto mínimo de uma página com idioma, codificação, viewport, título e conteúdo.',
    code: '<!doctype html>\n<html lang="pt-BR">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Minha primeira página</title>\n</head>\n<body>\n  <h1>Olá, web!</h1>\n</body>\n</html>',
    lineByLine: 'DOCTYPE ativa o modo moderno do HTML. html lang="pt-BR" informa o idioma principal. charset="utf-8" permite representar corretamente caracteres como acentos. viewport prepara a página para diferentes larguras de tela. title define o título da aba. body contém o conteúdo visível, e h1 representa o título principal.',
    guided: 'Crie um arquivo index.html e digite o exemplo inteiro. Depois altere apenas o conteúdo de title e h1.',
    exercise: 'Explique a diferença entre head e body e diga para que servem lang, charset e viewport.',
    challenge: 'Crie um documento HTML do zero, sem copiar, contendo título da aba e um h1 com seu nome.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n<html>\n<head>\n<h1>Meu título visível</h1>\n</head>\n</html>',
    common: 'Colocar conteúdo principal visível dentro de head, esquecer o fechamento de elementos e confundir tag, elemento e atributo.',
    summary: 'Um documento HTML possui uma estrutura organizada. head contém metadados e configurações; body contém o conteúdo visível.',
    task: 'Criar e salvar um index.html completo com idioma, charset, viewport, title e h1.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'O conteúdo que aparece na página fica em body.',
    hint2: 'O idioma principal deve ser informado em html com lang.',
    solution: '<!doctype html>\n<html lang="pt-BR">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Página de Júlia</title>\n</head>\n<body>\n  <h1>Júlia</h1>\n</body>\n</html>'
  },
  {
    id: 38, module: 3, title: 'Textos, listas, links e imagens', time: '50–60 min',
    learn: ['Headings e parágrafos', 'Listas ordenadas e não ordenadas', 'Links', 'Imagens e texto alternativo'],
    importance: 'Esses elementos formam grande parte do conteúdo real de páginas e precisam ser usados com significado, não apenas por aparência.',
    before: 'Você já consegue criar um documento HTML completo.',
    explanation: 'Headings h1 a h6 representam níveis de títulos e devem seguir a hierarquia do conteúdo. p cria parágrafos. ul cria listas sem ordem numérica e ol cria listas ordenadas; li representa cada item. a cria links e usa href para indicar o destino. img insere imagens e alt fornece uma alternativa textual quando a imagem comunica informação. Para imagens puramente decorativas, alt="" pode ser apropriado para que tecnologias assistivas ignorem a imagem.',
    everyday: 'Um texto de estudo pode ter um título principal, subtítulos, parágrafos, uma lista de tópicos, referências em links e imagens explicativas com descrição equivalente.',
    programming: 'Vamos montar um pequeno bloco de perfil de estudos com título, parágrafo, lista, link e imagem.',
    code: '<h1>Meus estudos</h1>\n<p>Estou aprendendo desenvolvimento web.</p>\n<h2>Tecnologias</h2>\n<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>\n<a href="https://developer.mozilla.org/">Consultar referência</a>\n<img src="estudos.png" alt="Caderno aberto ao lado de um computador">',
    lineByLine: 'h1 define o título principal. p cria o parágrafo. h2 abre uma seção subordinada ao h1. ul contém uma lista não ordenada e cada li é um item. a cria um link usando href. img aponta para o arquivo em src e descreve a informação relevante em alt.',
    guided: 'Adicione ao seu index.html um parágrafo, uma lista com três itens e um link. Depois inclua uma imagem de exercício com alt descritivo.',
    exercise: 'Crie uma seção “O que estou aprendendo” com h2, um parágrafo, uma lista e um link para uma referência.',
    challenge: 'Explique quando usar ul e ol e escreva dois exemplos de alt: um para imagem informativa e outro para imagem decorativa.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n<img src="grafico.png" alt="imagem">',
    common: 'Escolher h3 só porque parece menor, usar alt genérico como “imagem” e abrir links sem indicar um destino válido.',
    summary: 'HTML oferece elementos específicos para textos, hierarquia, listas, links e imagens. O uso semântico melhora compreensão e acessibilidade.',
    task: 'Completar a página de estudos com títulos hierárquicos, parágrafo, lista, link e imagem com alt adequado.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'Use h2 para uma seção subordinada ao título principal.',
    hint2: 'Se a ordem dos itens importa, prefira ol; se não importa, use ul.',
    solution: '<section>\n  <h2>O que estou aprendendo</h2>\n  <p>Estou estudando a estrutura da web.</p>\n  <ul>\n    <li>HTML</li>\n    <li>Acessibilidade</li>\n    <li>Semântica</li>\n  </ul>\n  <a href="https://developer.mozilla.org/">MDN Web Docs</a>\n</section>'
  },
  {
    id: 39, module: 3, title: 'HTML semântico', time: '50–60 min',
    learn: ['header, nav e main', 'section, article e aside', 'footer', 'Semântica, acessibilidade e SEO introdutório'],
    importance: 'Semântica ajuda a comunicar a função de cada parte da página para pessoas, navegadores e tecnologias assistivas.',
    before: 'Você já conhece elementos de conteúdo como headings, parágrafos, listas, links e imagens.',
    explanation: 'HTML semântico usa elementos cujo nome expressa a função do conteúdo. header representa conteúdo introdutório, nav agrupa navegação principal ou relevante, main identifica o conteúdo principal, section organiza uma seção temática, article representa conteúdo que pode fazer sentido de forma independente, aside contém conteúdo complementar e footer representa informações de encerramento. Semântica pode contribuir para acessibilidade e compreensão por mecanismos de busca, mas não garante SEO sozinha.',
    everyday: 'Em um livro, capa, sumário, capítulos, caixas laterais e rodapé têm funções diferentes. Marcar essas funções ajuda a entender a estrutura sem depender apenas da aparência.',
    programming: 'Vamos reorganizar uma página simples usando elementos que expressem o papel de cada região.',
    code: '<header>\n  <h1>Python do Zero</h1>\n</header>\n<nav>\n  <a href="#curso">Curso</a>\n  <a href="#tarefas">Tarefas</a>\n</nav>\n<main>\n  <section id="curso">\n    <h2>Curso</h2>\n    <article>\n      <h3>Módulo 3</h3>\n      <p>Desenvolvimento Front-end.</p>\n    </article>\n  </section>\n</main>\n<footer>\n  <p>Projeto de estudos.</p>\n</footer>',
    lineByLine: 'header apresenta a página. nav agrupa links de navegação. main envolve o conteúdo principal. section organiza o tema Curso. article contém uma unidade de conteúdo. footer encerra a página.',
    guided: 'Pegue sua página da Aula 38 e substitua agrupamentos genéricos por elementos semânticos quando houver uma função clara.',
    exercise: 'Monte uma estrutura contendo header, nav, main, uma section com article e footer.',
    challenge: 'Explique por que não faz sentido trocar todo div por section apenas para “ficar semântico”.',
    findError: 'Afirmação: “Se eu usar header, nav e main, meu site automaticamente terá ótimo SEO.” Corrija.',
    common: 'Usar section para qualquer agrupamento visual, repetir main na mesma página sem necessidade e tratar semântica como garantia automática de SEO.',
    summary: 'Elementos semânticos descrevem a função do conteúdo. Eles ajudam a organizar a página e podem favorecer acessibilidade e compreensão estrutural.',
    task: 'Reorganizar sua página de estudos usando header, nav, main, section e footer de forma coerente.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'main deve envolver o conteúdo principal da página.',
    hint2: 'section deve representar uma seção temática, normalmente com um heading.',
    solution: '<header><h1>Meu estudo</h1></header>\n<nav><a href="#conteudo">Conteúdo</a></nav>\n<main>\n  <section id="conteudo">\n    <h2>Conteúdo</h2>\n    <article><h3>HTML</h3><p>Estrutura da web.</p></article>\n  </section>\n</main>\n<footer><p>Fim da página.</p></footer>'
  },
  {
    id: 40, module: 3, title: 'Formulários HTML', time: '50–60 min',
    learn: ['form, label e input', 'select e textarea', 'button', 'Associação entre rótulo e campo', 'Por que placeholder não substitui label'],
    importance: 'Formulários são a principal forma de receber dados do usuário em muitas aplicações web e precisam ser compreensíveis e acessíveis.',
    before: 'Você já sabe estruturar páginas HTML e usar elementos semânticos.',
    explanation: 'form agrupa campos relacionados ao envio de dados. label identifica um campo e deve estar associado a ele, normalmente com for no label e id no campo. input recebe diferentes tipos de dados. select oferece opções, textarea recebe textos maiores e button cria uma ação. Placeholder é apenas uma dica temporária dentro do campo; ele desaparece durante a digitação e não substitui um rótulo visível.',
    everyday: 'Um formulário de matrícula precisa dizer claramente o que cada espaço pede: nome, curso e observações. Não basta deixar pistas que desaparecem quando a pessoa começa a escrever.',
    programming: 'Vamos criar um formulário simples de interesse em estudos, sem ainda processar os dados com JavaScript ou servidor.',
    code: '<form>\n  <label for="nome">Nome</label>\n  <input id="nome" name="nome" type="text">\n\n  <label for="curso">Curso</label>\n  <select id="curso" name="curso">\n    <option>Python</option>\n    <option>Front-end</option>\n  </select>\n\n  <label for="mensagem">Mensagem</label>\n  <textarea id="mensagem" name="mensagem"></textarea>\n\n  <button type="submit">Enviar</button>\n</form>',
    lineByLine: 'form agrupa os controles. Cada label usa for para apontar ao id correspondente. input recebe o nome. select oferece opções. textarea aceita texto maior. button type="submit" representa o envio do formulário. O processamento do envio será estudado mais adiante.',
    guided: 'Adicione um formulário à sua página com nome, área de interesse, mensagem e botão. Teste clicar no texto do label e observe se o foco vai para o campo correspondente.',
    exercise: 'Crie um formulário com campos de nome e e-mail, cada um com label associado, e um botão de envio.',
    challenge: 'Explique por que placeholder não deve ser a única identificação de um campo.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n<input type="text" placeholder="Nome">\n<input type="email" placeholder="E-mail">',
    common: 'Usar apenas placeholder, repetir o mesmo id em campos diferentes e criar button sem entender seu tipo dentro do formulário.',
    summary: 'Formulários usam controles como input, select e textarea. Labels visíveis e associados tornam os campos mais claros e acessíveis.',
    task: 'Finalizar o projeto do bloco: página de perfil/estudo em HTML com estrutura semântica, texto, lista, link, imagem com alt e formulário acessível.',
    video: null,
    hint1: 'Crie um label para cada campo e use for igual ao id correspondente.',
    hint2: 'Para e-mail, use input type="email".',
    solution: '<form>\n  <label for="nome">Nome</label>\n  <input id="nome" name="nome" type="text">\n  <label for="email">E-mail</label>\n  <input id="email" name="email" type="email">\n  <button type="submit">Enviar</button>\n</form>'
  }
);