window.PDZ_DATA.lessons.push(
  {
    id: 16, module: 1, title: 'Listas', time: '50–60 min',
    learn: ['Lista', 'Elemento e índice', 'append()', 'remove()', 'len()', 'Percorrer listas'],
    importance: 'Listas permitem guardar vários valores relacionados em uma única estrutura e trabalhar com eles em conjunto.',
    before: 'Você já conhece variáveis, for e while.',
    explanation: 'Uma lista guarda vários elementos em ordem. Em Python, os índices começam em 0. append() adiciona um elemento ao final, remove() remove um valor existente e len() informa a quantidade de elementos. Um for pode percorrer os elementos da lista.',
    everyday: 'Uma lista de compras reúne vários itens em ordem. Você pode adicionar um item, retirar outro e contar quantos ainda faltam.',
    programming: 'Podemos guardar nomes de estudantes em uma lista e percorrer cada nome com for.',
    code: 'alunos = ["Ana", "Bruno", "Carla"]\nalunos.append("Diego")\nprint(alunos[0])\nprint(len(alunos))\n\nfor aluno in alunos:\n    print(aluno)',
    lineByLine: 'A primeira linha cria a lista. append() adiciona Diego. alunos[0] acessa o primeiro elemento. len() conta os elementos. O for percorre cada item.',
    guided: 'Crie uma lista com três matérias, adicione uma quarta e percorra a lista com for.',
    exercise: 'Crie uma lista com quatro frutas, remova uma delas e mostre a quantidade restante.',
    challenge: 'Crie uma lista de notas e use for para mostrar cada nota. Depois calcule manualmente a soma usando uma variável acumuladora.',
    findError: 'Uma lista tem três elementos e o código tenta acessar lista[3] esperando o terceiro item. Explique o erro.',
    common: 'Esquecer que o primeiro índice é 0 e tentar remover um valor que não existe.',
    summary: 'Listas guardam vários valores em ordem. Índices começam em 0. append(), remove(), len() e for são ferramentas básicas para trabalhar com elas.',
    task: 'Criar uma lista de estudos com pelo menos cinco itens e praticar adicionar, remover, contar e percorrer.', video: 'https://www.youtube.com/watch?v=N1hTsbW50eM',
    hint1: 'Lembre que o primeiro elemento está no índice 0.', hint2: 'Depois de remover um item, use len() para conferir o tamanho.', solution: 'frutas = ["maçã", "banana", "uva", "pera"]\nfrutas.remove("uva")\nprint(frutas)\nprint(len(frutas))'
  },
  {
    id: 17, module: 1, title: 'Tuplas e conjuntos', time: '50–60 min',
    learn: ['Tuplas', 'Imutabilidade', 'Conjuntos (set)', 'Elementos únicos', 'Diferenças entre lista, tupla e conjunto'],
    importance: 'Estruturas diferentes existem porque nem todo conjunto de dados precisa do mesmo comportamento.',
    before: 'Você já sabe trabalhar com listas.',
    explanation: 'Tuplas são sequências ordenadas que não podem ser alteradas depois de criadas. Sets são conjuntos sem elementos duplicados e não devem ser usados quando a posição dos itens é importante. Listas são mutáveis e mantêm ordem; tuplas mantêm ordem e são imutáveis; sets priorizam unicidade.',
    everyday: 'Uma data de nascimento pode ser pensada como um conjunto fixo de valores; já uma lista de tarefas muda com frequência. Um conjunto de matrículas únicas é um exemplo de informação em que duplicatas não fazem sentido.',
    programming: 'Podemos usar uma tupla para coordenadas e um set para remover duplicatas de uma coleção simples.',
    code: 'coordenada = (10, 20)\nnomes = {"Ana", "Bruno", "Ana"}\nprint(coordenada)\nprint(nomes)',
    lineByLine: 'A tupla guarda 10 e 20 em ordem e não deve ser alterada. O set recebe Ana duas vezes, mas mantém apenas um valor Ana.',
    guided: 'Crie uma tupla com três cores e um set com valores repetidos. Observe o resultado.',
    exercise: 'Explique qual estrutura escolheria para: lista de compras, coordenadas fixas e conjunto de códigos únicos.',
    challenge: 'Crie uma lista com valores repetidos e transforme em set para observar quais duplicatas desaparecem.',
    findError: 'Uma pessoa tenta alterar diretamente o primeiro elemento de uma tupla. Explique por que isso não funciona.',
    common: 'Pensar que set possui posições confiáveis como uma lista e esquecer que tupla é imutável.',
    summary: 'Lista é mutável e ordenada; tupla é ordenada e imutável; set mantém valores únicos e não deve ser tratado como sequência indexada.',
    task: 'Criar um exemplo útil de lista, tupla e set e explicar por que escolheu cada estrutura.', video: null,
    hint1: 'Pense primeiro se os dados precisam mudar.', hint2: 'Depois pergunte se a ordem ou a unicidade é importante.', solution: 'Lista de compras → lista, pois muda.\nCoordenadas fixas → tupla, pois representam um conjunto estável.\nCódigos únicos → set, pois duplicatas não são desejadas.'
  },
  {
    id: 18, module: 1, title: 'Dicionários', time: '50–60 min',
    learn: ['Chave e valor', 'Acesso e alteração', 'Inclusão de dados', 'Lista de dicionários'],
    importance: 'Dicionários permitem organizar informações por significado, usando chaves como nome, idade ou nota.',
    before: 'Você já conhece listas e outros tipos básicos.',
    explanation: 'Um dicionário guarda pares chave: valor. Em vez de usar apenas posições numéricas, acessamos um dado pela chave. É possível alterar um valor existente ou adicionar uma nova chave. Uma lista pode guardar vários dicionários para representar registros.',
    everyday: 'Uma ficha de estudante tem campos como nome, idade e turma. Cada campo funciona como uma chave associada a um valor.',
    programming: 'Podemos representar um aluno com um dicionário e depois colocar vários alunos em uma lista.',
    code: 'aluno = {"nome": "Ana", "idade": 10, "nota": 8.5}\nprint(aluno["nome"])\naluno["nota"] = 9.0\naluno["turma"] = "5A"\nprint(aluno)',
    lineByLine: 'O dicionário começa com três pares. aluno["nome"] acessa o nome. A nota é atualizada e turma é adicionada como nova chave.',
    guided: 'Crie um dicionário para um livro com título, autor e ano. Depois altere o ano.',
    exercise: 'Crie um dicionário produto com nome, preço e estoque. Mostre o preço e depois adicione a chave categoria.',
    challenge: 'Crie dois dicionários de alunos e coloque ambos dentro de uma lista. Percorra a lista e mostre o nome de cada aluno.',
    findError: 'O código tenta acessar aluno["endereco"] quando essa chave não existe. Explique o problema.',
    common: 'Confundir chave com índice e digitar uma chave diferente da que foi criada.',
    summary: 'Dicionários organizam dados em pares chave: valor. Eles são úteis para representar registros com campos nomeados.',
    task: 'Criar uma lista com três dicionários representando estudantes, cada um com nome e nota.', video: null,
    hint1: 'Monte primeiro um único dicionário.', hint2: 'Depois coloque os dicionários separados por vírgula dentro de uma lista.', solution: 'produto = {"nome": "Caderno", "preco": 15.0, "estoque": 10}\nprint(produto["preco"])\nproduto["categoria"] = "Papelaria"\nprint(produto)'
  },
  {
    id: 19, module: 1, title: 'Funções', time: '50–60 min',
    learn: ['def', 'Parâmetros e argumentos', 'return', 'Escopo introdutório', 'Diferença entre print() e return'],
    importance: 'Funções ajudam a organizar o programa em partes menores, reutilizáveis e com responsabilidades claras.',
    before: 'Você já consegue escrever pequenos programas com dados, decisões, repetições e estruturas de dados.',
    explanation: 'Uma função é um bloco de código com nome. def inicia a definição. Parâmetros são nomes usados na definição da função; argumentos são os valores enviados na chamada. return devolve um resultado para quem chamou a função. print() apenas mostra algo na tela e não substitui return.',
    everyday: 'Uma função é como uma pequena máquina: recebe informações, realiza uma tarefa e pode devolver um resultado.',
    programming: 'Podemos criar uma função somar que recebe dois números e devolve a soma.',
    code: 'def somar(a, b):\n    resultado = a + b\n    return resultado\n\ntotal = somar(10, 5)\nprint(total)',
    lineByLine: 'def cria a função. a e b são parâmetros. resultado existe dentro da função. return entrega o valor calculado. Na chamada, 10 e 5 são argumentos.',
    guided: 'Crie uma função dobro(numero) que devolva numero * 2 e teste com diferentes valores.',
    exercise: 'Crie uma função calcular_media(nota1, nota2) que retorne a média das duas notas.',
    challenge: 'Crie uma função que receba um nome e uma idade e retorne uma frase usando f-string.',
    findError: 'Uma função calcula resultado = a + b, usa print(resultado), mas o programa tenta guardar retorno = somar(2, 3). Explique por que retorno será None se não houver return.',
    common: 'Confundir parâmetro com argumento, usar print() quando precisa devolver um valor e tentar usar fora da função uma variável criada apenas dentro dela.',
    summary: 'Funções são definidas com def, podem receber parâmetros e devolver valores com return. Elas ajudam a organizar e reutilizar código.',
    task: 'Criar três funções simples: dobro, soma e média.', video: null,
    hint1: 'A média de duas notas é a soma dividida por 2.', hint2: 'Use return para devolver o resultado, não apenas print().', solution: 'def calcular_media(nota1, nota2):\n    return (nota1 + nota2) / 2\n\nmedia = calcular_media(8, 6)\nprint(media)'
  },
  {
    id: 20, module: 1, title: 'Projeto do Módulo 1 — Sistema Escolar no Terminal', time: '50–60 min',
    learn: ['Combinar os conceitos do Módulo 1', 'Organizar o programa com funções', 'Usar lista de dicionários', 'Criar um menu interativo'],
    importance: 'O projeto final transforma conceitos isolados em um programa completo, mas ainda dentro do nível que você já estudou.',
    before: 'Você concluiu as Aulas 1–19. Não use classes, arquivos, JSON, banco de dados, APIs ou frameworks neste projeto.',
    explanation: 'O sistema escolar deve manter os dados apenas enquanto o programa estiver em execução. Use uma lista de dicionários para guardar alunos e funções para cadastrar, listar, buscar, adicionar notas, calcular média e excluir. O menu pode ser controlado com while e if/elif/else.',
    everyday: 'Pense em uma secretaria escolar temporária: enquanto o sistema está aberto, você mantém uma lista de fichas de alunos e executa ações sobre elas.',
    programming: 'Uma lista chamada alunos pode guardar dicionários como {"nome": "Ana", "notas": [8, 7]}. Funções operam sobre essa lista.',
    code: 'alunos = []\n\ndef cadastrar_aluno():\n    nome = input("Nome: ")\n    aluno = {"nome": nome, "notas": []}\n    alunos.append(aluno)\n\ndef listar_alunos():\n    for aluno in alunos:\n        print(aluno["nome"])',
    lineByLine: 'alunos é a lista principal. cadastrar_aluno() cria um dicionário com nome e lista vazia de notas e o adiciona. listar_alunos() percorre os registros e mostra os nomes.',
    guided: 'Construa primeiro cadastrar e listar. Teste. Depois adicione buscar aluno, notas, média e exclusão uma função por vez.',
    exercise: 'Crie uma função buscar_aluno(nome) que percorra a lista e retorne o dicionário do aluno encontrado ou None.',
    challenge: 'Concluir o sistema com menu: cadastrar aluno, listar alunos, buscar aluno, adicionar notas, calcular média, excluir aluno e sair.',
    findError: 'Um projeto tenta salvar os alunos em JSON nesta aula. Explique por que isso deve ser evitado agora.',
    common: 'Tentar usar conceitos do Módulo 2 antes da hora, escrever todo o sistema sem testar partes menores e misturar responsabilidades em uma única função enorme.',
    summary: 'O Módulo 1 termina com um sistema escolar em Python puro, usando apenas conceitos já estudados. A revisão final deve confirmar que você entende programação, dados, decisões, repetições, coleções e funções.',
    task: 'Finalizar o Sistema Escolar no Terminal e fazer uma revisão completa das Aulas 1–20 antes de avançar para o Módulo 2.', video: null,
    hint1: 'Use uma lista de dicionários como estrutura principal e uma função para cada responsabilidade.', hint2: 'Faça o menu por último, depois que cadastrar, listar e buscar já estiverem funcionando.', solution: 'def buscar_aluno(nome):\n    for aluno in alunos:\n        if aluno["nome"] == nome:\n            return aluno\n    return None\n\n# O sistema completo deve ser construído por etapas usando esta ideia, sem classes, arquivos ou banco de dados.'
  }
);
