window.PDZ_DATA.lessons.push(
  {
    id: 46, module: 3, title: 'JavaScript para quem conhece Python', time: '50–60 min',
    learn: ['let e const', 'Tipos básicos', 'Arrays e objetos', 'Condições, loops e funções', 'Diferenças iniciais entre Python e JavaScript'],
    importance: 'JavaScript é a linguagem de programação executada pelo navegador e será usada para tornar as páginas interativas.',
    before: 'Você já aprendeu lógica com Python e construiu páginas com HTML e CSS.',
    explanation: 'JavaScript possui ideias que você já conhece, como variáveis, condições, repetições e funções, mas sua sintaxe é diferente. Para começar, use const quando a variável não precisar receber outro valor e let quando ela precisar mudar. Arrays lembram listas de Python. Objetos JavaScript lembram dicionários, mas não são JSON. Evite usar var como abordagem inicial. Use === para comparação estrita sempre que possível.',
    everyday: 'Você já conhece a ideia de guardar valores em caixas chamadas variáveis. Em JavaScript, a ideia continua a mesma; o que muda principalmente é a forma de escrever.',
    programming: 'Vamos reescrever em JavaScript uma lógica simples já conhecida de Python.',
    code: 'const nome = "Júlia";\nlet idade = 20;\n\nif (idade >= 18) {\n  console.log(`${nome} é maior de idade.`);\n}\n\nfor (let i = 0; i < 3; i++) {\n  console.log(i);\n}',
    lineByLine: 'const cria uma variável que não será reatribuída. let cria uma variável que pode mudar. if usa parênteses na condição e chaves no bloco. console.log exibe valores no console. O for tradicional controla início, condição e atualização do contador.',
    guided: 'Abra o console do navegador e teste const, let, if e um pequeno for.',
    exercise: 'Crie duas variáveis, uma com seu nome e outra com sua linguagem favorita, e mostre uma frase no console usando template string.',
    challenge: 'Explique duas diferenças de sintaxe entre Python e JavaScript sem dizer que uma linguagem é melhor que a outra.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nconst idade = 20;\nidade = 21;',
    common: 'Usar var por hábito, confundir objeto JavaScript com JSON e esquecer que const impede reatribuição da variável, não necessariamente mutação interna de objetos.',
    summary: 'JavaScript reaproveita conceitos de lógica que você já conhece, mas possui sintaxe própria. Comece com const e let, não com var.',
    task: 'Criar um arquivo script.js e escrever exemplos com const, let, array, objeto, if, for e função.',
    video: 'https://www.youtube.com/watch?v=vEwPnjqWQ-g',
    hint1: 'Use const para valores que não serão reatribuídos.',
    hint2: 'Template strings usam crases e ${...}.',
    solution: 'const nome = "Júlia";\nconst linguagem = "JavaScript";\nconsole.log(`${nome} está aprendendo ${linguagem}.`);'
  },
  {
    id: 47, module: 3, title: 'DOM', time: '50–60 min',
    learn: ['Document Object Model', 'document', 'Seleção de elementos', 'querySelector', 'textContent'],
    importance: 'O DOM é a ponte entre JavaScript e os elementos da página. É por ele que o código encontra e modifica o HTML exibido no navegador.',
    before: 'Você já conhece HTML e os fundamentos iniciais de JavaScript.',
    explanation: 'Quando o navegador carrega uma página HTML, ele cria uma representação em objetos chamada DOM, ou Document Object Model. O objeto document representa o documento atual. document.querySelector() encontra o primeiro elemento que corresponde a um seletor CSS. A propriedade textContent permite ler ou alterar o conteúdo textual de um elemento.',
    everyday: 'Imagine que o HTML é uma lista de itens em uma sala e o DOM é um mapa que permite ao JavaScript localizar cada item para ler ou alterar seu conteúdo.',
    programming: 'Vamos selecionar um título da página e alterar seu texto.',
    code: 'const titulo = document.querySelector("h1");\ntitulo.textContent = "JavaScript alterou este título";',
    lineByLine: 'document.querySelector("h1") procura o primeiro h1 do documento. O resultado é guardado em titulo. Depois, textContent substitui o texto visível desse elemento.',
    guided: 'Crie um h1 no HTML, conecte script.js e altere o texto com querySelector e textContent.',
    exercise: 'Selecione um parágrafo com uma classe e altere seu texto usando JavaScript.',
    challenge: 'Explique por que document.querySelector(".mensagem") usa a mesma sintaxe básica de seletor que você já viu no CSS.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nconst titulo = document.querySelector("h1");\ntitulo = "Novo título";',
    common: 'Confundir o elemento encontrado com seu texto e tentar alterar a variável em vez de usar uma propriedade como textContent.',
    summary: 'O DOM representa a página para o JavaScript. querySelector encontra elementos e textContent permite trabalhar com texto.',
    task: 'Selecionar e alterar com JavaScript pelo menos três elementos da página de estudos.',
    video: '',
    hint1: 'Use document.querySelector com um seletor CSS válido.',
    hint2: 'Depois de encontrar o elemento, altere sua propriedade textContent.',
    solution: 'const mensagem = document.querySelector(".mensagem");\nmensagem.textContent = "Texto atualizado pelo JavaScript";'
  },
  {
    id: 48, module: 3, title: 'Eventos', time: '50–60 min',
    learn: ['Eventos de click, submit e input', 'addEventListener', 'Callback introdutório'],
    importance: 'Eventos permitem que a página responda às ações da pessoa usuária, como clicar em um botão, digitar ou enviar um formulário.',
    before: 'Você já consegue selecionar elementos no DOM.',
    explanation: 'Um evento é algo que acontece no navegador. addEventListener registra uma função para ser executada quando um evento específico ocorrer. Essa função é chamada de callback nesse contexto. Eventos comuns incluem click em botões, input durante digitação e submit no envio de formulários.',
    everyday: 'Um interruptor reage quando alguém o pressiona. Na web, um botão pode reagir a um clique chamando uma função.',
    programming: 'Vamos fazer um botão alterar uma mensagem quando for clicado.',
    code: 'const botao = document.querySelector("#meu-botao");\nconst mensagem = document.querySelector("#mensagem");\n\nbotao.addEventListener("click", () => {\n  mensagem.textContent = "Você clicou no botão!";\n});',
    lineByLine: 'Primeiro selecionamos o botão e a mensagem. addEventListener recebe o nome do evento e uma função. Quando ocorre click, o callback executa e atualiza textContent.',
    guided: 'Crie um botão e uma mensagem no HTML e conecte o evento de click do exemplo.',
    exercise: 'Crie um botão que altere o texto de um parágrafo ao ser clicado.',
    challenge: 'Explique por que passar uma função para addEventListener é diferente de executar a função imediatamente.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nbotao.addEventListener("click", mudarTexto());',
    common: 'Executar a função na hora em vez de passá-la como callback e escrever o nome incorreto do evento.',
    summary: 'Eventos conectam ações da pessoa usuária a funções JavaScript. addEventListener registra o callback que será executado.',
    task: 'Adicionar à página um botão com evento de click e um campo com evento de input.',
    video: '',
    hint1: 'Passe uma função, não o resultado dela.',
    hint2: 'Use () => { ... } como callback simples.',
    solution: 'const botao = document.querySelector("button");\nconst texto = document.querySelector("p");\nbotao.addEventListener("click", () => {\n  texto.textContent = "Clique reconhecido";\n});'
  },
  {
    id: 49, module: 3, title: 'Formulários e validação', time: '50–60 min',
    learn: ['value', 'trim()', 'preventDefault()', 'Validação no navegador', 'Limites da validação front-end'],
    importance: 'Ler e validar entradas é necessário para criar interfaces úteis, mas validação no navegador não substitui validação e autorização no servidor.',
    before: 'Você já estudou formulários HTML, DOM e eventos.',
    explanation: 'Campos de formulário possuem valores que podem ser lidos pela propriedade value. trim() remove espaços no início e no fim de uma string. No evento submit, event.preventDefault() pode impedir temporariamente o envio padrão para que o JavaScript trate os dados. A validação front-end melhora a experiência, mas não é uma barreira de segurança confiável: qualquer dado importante também deve ser validado no back-end quando houver servidor.',
    everyday: 'Um formulário pode avisar imediatamente que um campo está vazio, mas um sistema real ainda precisa conferir os dados novamente antes de confiar neles.',
    programming: 'Vamos impedir o envio quando o nome estiver vazio após remover espaços.',
    code: 'const form = document.querySelector("form");\nconst nome = document.querySelector("#nome");\nconst mensagem = document.querySelector("#mensagem");\n\nform.addEventListener("submit", (event) => {\n  event.preventDefault();\n  const valor = nome.value.trim();\n\n  if (valor === "") {\n    mensagem.textContent = "Digite seu nome.";\n    return;\n  }\n\n  mensagem.textContent = `Olá, ${valor}!`;\n});',
    lineByLine: 'O submit dispara o callback. preventDefault impede o comportamento padrão nesse exemplo. value lê o conteúdo do campo e trim remove espaços externos. O if verifica se restou texto válido. return encerra o callback quando o campo está vazio.',
    guided: 'Crie um formulário com label, input, botão e área de mensagem. Depois implemente a validação.',
    exercise: 'Valide um campo de tarefa e impeça a criação quando ele estiver vazio.',
    challenge: 'Explique por que uma validação em JavaScript no navegador não pode ser tratada como mecanismo suficiente de segurança.',
    findError: 'Afirmação: “Se o formulário valida no JavaScript, o servidor pode confiar em qualquer dado recebido.” Corrija.',
    common: 'Confiar apenas no front-end, esquecer trim e usar placeholder no lugar de label.',
    summary: 'value lê campos, trim ajuda a validar texto e preventDefault permite tratar submit com JavaScript. Segurança exige validação também no servidor.',
    task: 'Criar um formulário acessível que valide campo obrigatório antes de adicionar uma tarefa.',
    video: '',
    hint1: 'Leia o campo com .value.',
    hint2: 'Use .trim() antes de comparar com string vazia.',
    solution: 'const tarefa = document.querySelector("#tarefa");\nconst valor = tarefa.value.trim();\nif (valor === "") {\n  console.log("Digite uma tarefa.");\n}'
  },
  {
    id: 50, module: 3, title: 'Projeto Front-end: Gerenciador de tarefas', time: '50–60 min',
    learn: ['Integrar HTML, CSS e JavaScript', 'Criar, listar, editar, concluir, excluir e filtrar tarefas', 'Usar localStorage com responsabilidade', 'Revisar DOM, eventos e validação'],
    importance: 'Este projeto reúne todo o Módulo 3 em uma aplicação funcional no navegador antes de você estudar servidores e APIs.',
    before: 'Você já estudou HTML, CSS, responsividade, JavaScript, DOM, eventos e formulários.',
    explanation: 'O projeto final do módulo será um gerenciador de tarefas executado inteiramente no navegador. As tarefas podem ser mantidas em um array de objetos e salvas no localStorage para persistirem após recarregar a página. localStorage pertence ao navegador e não é um banco de dados de servidor. Ele não deve armazenar senhas, tokens, chaves ou outros segredos.',
    everyday: 'É como uma pequena lista de afazeres pessoal guardada naquele navegador específico, não em uma conta central disponível em qualquer dispositivo.',
    programming: 'Estruture tarefas como objetos com id, titulo e concluida. Renderize a lista no DOM e salve o array no localStorage usando JSON.stringify e recupere com JSON.parse.',
    code: 'let tarefas = JSON.parse(localStorage.getItem("tarefas")) || [];\n\nfunction salvarTarefas() {\n  localStorage.setItem("tarefas", JSON.stringify(tarefas));\n}\n\nfunction adicionarTarefa(titulo) {\n  tarefas.push({\n    id: Date.now(),\n    titulo,\n    concluida: false\n  });\n  salvarTarefas();\n}',
    lineByLine: 'getItem busca o texto salvo. JSON.parse transforma esse texto em dados JavaScript. Se não houver nada, usamos array vazio. salvarTarefas converte o array para texto JSON com JSON.stringify. adicionarTarefa cria um objeto, adiciona ao array e salva novamente.',
    guided: 'Construa primeiro criar e listar. Depois implemente concluir e excluir. Por último, adicione editar e filtros.',
    exercise: 'Implemente a função que alterna o valor concluida de uma tarefa pelo id e depois salve novamente.',
    challenge: 'Implemente filtros para todas, pendentes e concluídas sem duplicar a lista original de dados.',
    findError: 'Afirmação: “localStorage é um banco de dados seguro para guardar senhas porque fica no navegador.” Corrija.',
    common: 'Misturar os dados com o HTML gerado, esquecer de salvar após alterações e armazenar informações sensíveis no localStorage.',
    summary: 'O projeto integra HTML, CSS, DOM, eventos, validação e persistência local. Ele funciona no navegador e ainda não possui back-end.',
    task: 'Finalizar o Gerenciador de Tarefas com criar, listar, editar, concluir, excluir, filtrar e persistir no localStorage.',
    video: 'https://www.youtube.com/watch?v=vEwPnjqWQ-g',
    hint1: 'Encontre a tarefa pelo id antes de alterar concluida.',
    hint2: 'Depois de mudar o array, chame salvarTarefas() e renderize novamente.',
    solution: 'function alternarTarefa(id) {\n  const tarefa = tarefas.find(item => item.id === id);\n  if (!tarefa) return;\n  tarefa.concluida = !tarefa.concluida;\n  salvarTarefas();\n  renderizarTarefas();\n}'
  }
);