window.PDZ_DATA.lessons.push(
  {
    id: 71, module: 6, title: 'Banco de dados, SGBD e persistência', time: '50–60 min',
    learn: ['O que é dado', 'Banco de dados', 'SGBD', 'Persistência', 'Memória temporária versus armazenamento persistente'],
    importance: 'Até aqui você já trabalhou com dados em memória. Agora é hora de entender como aplicações guardam informações de forma persistente para que elas continuem existindo depois que o programa é encerrado.',
    before: 'No Módulo 5, a API CRUD de alunos usava uma lista em memória. Ao reiniciar o servidor, aqueles dados poderiam desaparecer.',
    explanation: 'Dado é uma informação representada de alguma forma, como nome, idade ou nota. Um banco de dados organiza conjuntos de dados para armazenamento e consulta. SGBD significa Sistema de Gerenciamento de Banco de Dados: é o software responsável por armazenar, consultar, alterar, controlar acesso e manter os dados organizados. Persistência significa que os dados continuam armazenados além da execução atual do programa. Memória RAM é temporária; um banco de dados normalmente grava dados em armazenamento persistente.',
    everyday: 'Anotar uma informação apenas em uma lousa é como mantê-la em memória: quando a lousa é apagada, ela some. Registrar a informação em um arquivo organizado e guardado é mais parecido com persistência.',
    programming: 'Uma lista Python criada dentro do programa existe enquanto o processo está rodando. Um banco permite recuperar registros depois de reiniciar a aplicação.',
    code: 'alunos = [\n  {"id": 1, "nome": "Ana"}\n]\n\n# Se o programa encerrar, essa lista em memória não é um banco de dados.',
    lineByLine: 'alunos recebe uma lista com um dicionário. O dado existe na memória do processo. O comentário destaca que isso não cria persistência automática.',
    guided: 'Pense no CRUD de alunos do módulo anterior e liste quais informações precisariam continuar existindo após reiniciar o servidor.',
    exercise: 'Explique com suas palavras a diferença entre memória temporária, banco de dados e SGBD.',
    challenge: 'Uma aplicação guarda tarefas apenas em uma lista Python. O servidor reinicia e as tarefas somem. Identifique o problema e diga qual conceito resolve isso.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Banco de dados e SGBD são exatamente a mesma coisa.”\nCorreção: banco de dados é o conjunto organizado de dados; SGBD é o software que os gerencia.',
    common: 'Confundir os dados armazenados com o software que os gerencia e pensar que uma variável em memória já é persistência.',
    summary: 'Banco de dados organiza dados; SGBD gerencia o banco; persistência mantém os dados disponíveis depois que a execução atual termina.',
    task: 'Escrever três exemplos de dados que o aplicativo Python do Zero precisaria persistir em um sistema real.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Pense no que acontece quando o programa fecha.',
    hint2: 'SGBD é o software que gerencia os dados armazenados.',
    solution: 'O problema é falta de persistência. Os dados ficam apenas em memória e desaparecem com o processo. Um banco de dados gerenciado por um SGBD permite armazená-los de forma persistente.'
  },
  {
    id: 72, module: 6, title: 'PostgreSQL e SQL', time: '50–60 min',
    learn: ['O que é PostgreSQL', 'O que é SQL', 'SGBD relacional', 'Servidor e cliente de banco', 'SQL não é PostgreSQL'],
    importance: 'Diferenciar linguagem e sistema de banco evita uma confusão muito comum e prepara você para entender as ferramentas usadas no restante do módulo.',
    before: 'Você já sabe por que aplicações precisam de persistência e o que significa SGBD.',
    explanation: 'PostgreSQL é um sistema de gerenciamento de banco de dados relacional. SQL, sigla de Structured Query Language, é uma linguagem usada para definir, consultar e modificar dados em bancos relacionais. PostgreSQL entende SQL e também possui recursos próprios. Um servidor de banco executa o SGBD e recebe operações. Um cliente de banco é um programa que se conecta ao servidor para enviar comandos e visualizar resultados.',
    everyday: 'Pense em PostgreSQL como uma biblioteca organizada e no SQL como a linguagem usada para pedir ao bibliotecário que encontre, registre ou altere informações.',
    programming: 'Você escreverá instruções SQL e o PostgreSQL irá interpretá-las e executar as operações sobre o banco.',
    code: 'SELECT nome\nFROM alunos;',
    lineByLine: 'SELECT indica que queremos consultar dados. nome é a coluna solicitada. FROM informa de qual tabela os dados serão lidos. O ponto e vírgula encerra a instrução.',
    guided: 'Leia o comando do exemplo em português: “selecione a coluna nome da tabela alunos”.',
    exercise: 'Explique a diferença entre PostgreSQL e SQL sem usar a frase “são a mesma coisa”.',
    challenge: 'Classifique cada item como linguagem, SGBD ou dado: SQL, PostgreSQL, nome de um aluno.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Vou instalar o SQL para guardar meus dados.”\nCorreção: SQL é uma linguagem; um SGBD como PostgreSQL é o software que gerencia o banco.',
    common: 'Chamar PostgreSQL de linguagem ou SQL de banco de dados.',
    summary: 'SQL é linguagem. PostgreSQL é um SGBD relacional que entende SQL e gerencia bancos de dados.',
    task: 'Criar no caderno uma comparação curta entre SQL, PostgreSQL, banco de dados e SGBD.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Uma linguagem descreve comandos; um SGBD executa e gerencia.',
    hint2: 'PostgreSQL é software; SQL é linguagem.',
    solution: 'SQL = linguagem. PostgreSQL = SGBD relacional. Nome de um aluno = dado.'
  },
  {
    id: 73, module: 6, title: 'Tabelas, linhas, colunas e tipos', time: '50–60 min',
    learn: ['Tabela', 'Linha ou registro', 'Coluna ou campo', 'Esquema', 'Tipos de dados básicos'],
    importance: 'Bancos relacionais organizam dados em estruturas que precisam ser compreendidas antes de criar consultas e relacionamentos.',
    before: 'Você já sabe que PostgreSQL é um SGBD relacional e SQL é a linguagem usada para conversar com ele.',
    explanation: 'Em um banco relacional, uma tabela organiza dados em linhas e colunas. Cada linha representa um registro, como um aluno. Cada coluna representa uma característica, como nome ou idade. O esquema descreve a estrutura esperada. Tipos de dados ajudam o banco a saber que tipo de valor uma coluna aceita. Exemplos comuns incluem INTEGER, VARCHAR ou TEXT, BOOLEAN, DATE e TIMESTAMP.',
    everyday: 'Uma planilha simples ajuda a visualizar a ideia: cada linha pode representar uma pessoa e cada coluna uma informação sobre ela. Um banco relacional vai além da planilha, oferecendo regras, relações, consultas e controle de dados.',
    programming: 'Uma tabela alunos pode ter colunas id, nome, ativo e criado_em, cada uma com um tipo adequado.',
    code: 'alunos\n--------------------------------\nid | nome  | ativo | criado_em\n1  | Ana   | true  | 2026-09-09\n2  | Bruno | false | 2026-09-10',
    lineByLine: 'id identifica o registro neste exemplo. nome armazena texto. ativo representa um valor booleano. criado_em representa uma data ou data e hora, conforme o tipo definido no banco.',
    guided: 'Desenhe uma tabela cursos com pelo menos quatro colunas e indique um tipo possível para cada uma.',
    exercise: 'Associe os dados a tipos adequados: idade, nome completo, matrícula ativa, data de nascimento.',
    challenge: 'Explique por que armazenar idade como texto pode dificultar operações numéricas.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Cada coluna representa um aluno e cada linha representa uma característica.”\nCorreção: cada linha representa um registro; cada coluna representa um atributo.',
    common: 'Confundir linha com coluna e escolher tipos sem considerar o tipo real da informação.',
    summary: 'Tabelas possuem linhas e colunas. Linhas representam registros; colunas representam atributos com tipos definidos.',
    task: 'Modelar em papel uma tabela alunos com pelo menos cinco colunas e seus tipos.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'INTEGER é adequado para números inteiros; BOOLEAN para verdadeiro/falso.',
    hint2: 'DATE representa data; TEXT/VARCHAR representam texto.',
    solution: 'idade → INTEGER; nome completo → TEXT ou VARCHAR; matrícula ativa → BOOLEAN; data de nascimento → DATE.'
  },
  {
    id: 74, module: 6, title: 'Chave primária e chave estrangeira', time: '50–60 min',
    learn: ['Primary key', 'Foreign key', 'Identidade de registro', 'Referência entre tabelas', 'Integridade referencial'],
    importance: 'Chaves permitem identificar registros e conectar tabelas sem repetir informações desnecessariamente.',
    before: 'Você já entende tabelas, linhas, colunas e tipos.',
    explanation: 'Uma chave primária, ou primary key, identifica de forma única cada registro de uma tabela. Ela não precisa ser obrigatoriamente um número inteiro sequencial; existem outras estratégias válidas. Uma chave estrangeira, ou foreign key, é uma coluna ou conjunto de colunas que referencia uma chave de outra tabela. Isso permite criar relações entre registros. Integridade referencial significa, em nível introdutório, manter referências válidas entre tabelas.',
    everyday: 'Imagine uma ficha de aluno com um identificador único. Em outra tabela, uma matrícula pode guardar esse identificador para indicar de qual aluno ela é, sem repetir todos os dados pessoais.',
    programming: 'A tabela matriculas pode ter aluno_id como chave estrangeira apontando para alunos.id.',
    code: 'alunos\n----------------\nid | nome\n1  | Ana\n\nmatriculas\n------------------------\nid | aluno_id | curso_id\n10 | 1        | 3',
    lineByLine: 'alunos.id identifica Ana de forma única. matriculas.aluno_id guarda o valor 1 e referencia esse aluno. Dessa forma, a matrícula aponta para Ana sem duplicar seu nome.',
    guided: 'Marque no exemplo qual é a chave primária de alunos e qual coluna em matriculas pode funcionar como chave estrangeira.',
    exercise: 'Explique a diferença entre chave primária e chave estrangeira.',
    challenge: 'Por que seria ruim usar apenas o nome do aluno como identificação única em todos os relacionamentos?',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Toda chave primária precisa ser um número inteiro 1, 2, 3, 4...”\nCorreção: uma chave primária precisa identificar unicamente o registro, mas pode usar outras estratégias.',
    common: 'Confundir chave primária com posição da linha e pensar que toda primary key precisa ser autoincremental.',
    summary: 'Primary key identifica registros de forma única. Foreign key cria referências entre tabelas.',
    task: 'Desenhar duas tabelas relacionadas e indicar PK e FK.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'PK responde “qual registro é este?”.',
    hint2: 'FK responde “a qual registro de outra tabela este valor se refere?”.',
    solution: 'A chave primária identifica unicamente um registro na própria tabela. A chave estrangeira referencia uma chave de outra tabela para criar uma relação.'
  },
  {
    id: 75, module: 6, title: 'Relacionamentos entre tabelas', time: '50–60 min',
    learn: ['Relacionamento 1:1', 'Relacionamento 1:N', 'Relacionamento N:N', 'Tabela associativa', 'Alunos, cursos e matrículas'],
    importance: 'Relacionamentos permitem modelar situações reais de forma organizada, evitando colocar tudo em uma única tabela.',
    before: 'Você já sabe identificar chaves primárias e estrangeiras.',
    explanation: 'No relacionamento 1:1, um registro de uma tabela se relaciona com no máximo um registro correspondente da outra. No 1:N, um registro de um lado pode se relacionar com vários do outro; por exemplo, um curso pode ter muitos módulos. No N:N, vários registros de uma tabela podem se relacionar com vários registros de outra. Em bancos relacionais, N:N costuma ser representado por uma tabela associativa. No exemplo escolar, um aluno pode cursar vários cursos e um curso pode ter vários alunos; a tabela matriculas conecta os dois lados.',
    everyday: 'Uma pessoa pode ter um perfil complementar exclusivo em um sistema (1:1); uma turma pode ter muitos alunos (1:N); alunos podem participar de vários cursos e cada curso pode ter vários alunos (N:N).',
    programming: 'Para alunos e cursos, usamos uma tabela matriculas contendo aluno_id e curso_id.',
    code: 'alunos(id, nome)\ncursos(id, titulo)\nmatriculas(id, aluno_id, curso_id)\n\nAna → Python\nAna → Git\nBruno → Python',
    lineByLine: 'alunos e cursos são tabelas principais. matriculas funciona como tabela associativa. Cada linha em matriculas conecta um aluno a um curso.',
    guided: 'Classifique: pessoa e passaporte do sistema (1:1), curso e módulos (1:N), alunos e cursos (N:N).',
    exercise: 'Explique por que alunos e cursos formam naturalmente uma relação N:N em muitos sistemas escolares.',
    challenge: 'Desenhe um exemplo de tabela associativa matriculas com três linhas e identifique quais chaves estrangeiras ela precisa.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Em N:N basta colocar vários IDs dentro de uma única célula da tabela alunos.”\nCorreção: relações N:N normalmente são modeladas com uma tabela associativa.',
    common: 'Tentar guardar listas de IDs em uma coluna comum em vez de modelar a relação e confundir o lado “um” com o lado “muitos”.',
    summary: 'Relacionamentos podem ser 1:1, 1:N e N:N. Relações N:N normalmente usam uma tabela associativa.',
    task: 'Modelar em papel alunos, cursos e matriculas, marcando PKs e FKs.',
    video: 'https://www.youtube.com/watch?v=9cAKQWodpvM',
    hint1: 'Pergunte quantos registros de cada lado podem se relacionar.',
    hint2: 'No N:N, uma tabela intermediária conecta os dois lados.',
    solution: 'A tabela matriculas pode ter id como PK e aluno_id e curso_id como FKs, criando uma linha para cada vínculo entre aluno e curso.'
  }
);