window.PDZ_DATA.lessons.push(
  {
    id: 91, module: 8, title: 'Máscara, CIDR e sub-redes', time: '50–60 min',
    learn: ['máscara de rede', 'CIDR', 'prefixo', 'sub-rede', '/24', 'parte de rede e parte de host'],
    importance: 'CIDR e sub-redes ajudam a entender como endereços IP são agrupados e quais máquinas pertencem à mesma rede lógica.',
    before: 'Você já conhece IPv4, IPv6, IP público, IP privado, localhost, gateway e NAT.',
    explanation: 'Em IPv4, a máscara de rede indica quais bits do endereço identificam a rede e quais podem variar entre os hosts. A notação CIDR escreve isso com uma barra e a quantidade de bits da parte de rede. Por exemplo, /24 significa 24 bits para identificar a rede. Em um exemplo didático como 192.168.1.0/24, os primeiros 24 bits representam a rede e o último octeto varia entre endereços daquela sub-rede. Neste momento o foco é compreender a ideia, sem fazer cálculos avançados de subnetting.',
    everyday: 'Pense em um endereço com cidade, rua e número da casa. Parte do endereço identifica a região comum; outra parte identifica o destino específico dentro dela.',
    programming: 'Interprete o exemplo 192.168.1.0/24 e identifique o que o /24 informa.',
    code: 'Rede de exemplo: 192.168.1.0/24\nPrefixo CIDR: /24\nIdeia: 24 bits identificam a parte de rede.',
    lineByLine: '192.168.1.0 é o endereço usado no exemplo. /24 é o prefixo CIDR. Ele informa quantos bits são considerados parte da rede.',
    guided: 'Compare /8, /16 e /24 apenas pela quantidade de bits reservados à parte de rede.',
    exercise: 'Em uma notação /24, quantos bits pertencem à parte de rede?',
    challenge: 'Explique por que uma máscara de rede não é a mesma coisa que um endereço IP.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“/24 significa que o endereço IP possui apenas 24 bits.”',
    common: 'Confundir o tamanho do prefixo com o tamanho total do endereço IPv4 e tentar memorizar cálculos antes de compreender o conceito.',
    summary: 'CIDR indica o tamanho da parte de rede. Em IPv4, /24 significa 24 bits usados como prefixo de rede.',
    task: 'Criar três exemplos de redes usando /8, /16 e /24 e explicar apenas o significado do prefixo.',
    video: '',
    hint1: 'IPv4 continua tendo 32 bits no total.',
    hint2: 'O número depois da barra informa quantos bits pertencem ao prefixo de rede.',
    solution: 'Em /24, 24 bits pertencem à parte de rede; os demais 8 bits ficam disponíveis para a parte de host no endereço IPv4.'
  },
  {
    id: 92, module: 8, title: 'Portas e sockets', time: '50–60 min',
    learn: ['porta', 'socket', 'processo', 'IP + porta', '22 SSH', '53 DNS', '80 HTTP', '443 HTTPS'],
    importance: 'O endereço IP identifica a máquina/interface na rede, enquanto a porta ajuda a direcionar a comunicação para um serviço ou processo específico.',
    before: 'Você já entende endereçamento IP e sub-redes em nível introdutório.',
    explanation: 'Uma porta é um número usado pelos protocolos de transporte para identificar o destino lógico de uma comunicação dentro de um host. Um socket representa, de forma simplificada, um ponto de comunicação usado por programas. Alguns números de porta são tradicionalmente associados a serviços conhecidos: 22 SSH, 53 DNS, 80 HTTP e 443 HTTPS. DNS pode usar UDP e TCP na porta 53, dependendo da situação.',
    everyday: 'O IP é como o endereço de um prédio; a porta é como o número de uma sala onde funciona um serviço específico.',
    programming: 'Associe uma API HTTPS publicada no servidor ao endereço do host e à porta 443.',
    code: 'SSH   → 22\nDNS   → 53 (UDP e TCP)\nHTTP  → 80\nHTTPS → 443',
    lineByLine: 'Cada linha relaciona um serviço conhecido a uma porta convencional. Essas associações ajudam clientes a localizar o serviço esperado.',
    guided: 'Diferencie IP e porta e explique por que dois serviços diferentes podem existir no mesmo servidor.',
    exercise: 'Qual porta é tradicionalmente associada ao HTTPS? E qual é associada ao SSH?',
    challenge: 'Explique por que dizer que DNS usa somente UDP é incorreto.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“DNS usa exclusivamente UDP e nunca utiliza TCP.”',
    common: 'Confundir IP com porta e acreditar que um número de porta identifica sozinho uma máquina na Internet.',
    summary: 'IP identifica o host/interface; a porta identifica um destino lógico de serviço. Um socket é um ponto de comunicação usado por programas.',
    task: 'Montar uma tabela com SSH, DNS, HTTP e HTTPS, suas portas e uma frase sobre cada serviço.',
    video: '',
    hint1: 'HTTPS usa a porta convencional 443.',
    hint2: 'SSH usa a porta convencional 22.',
    solution: 'HTTPS: 443. SSH: 22.'
  },
  {
    id: 93, module: 8, title: 'TCP versus UDP', time: '50–60 min',
    learn: ['TCP', 'UDP', 'conexão', 'confiabilidade', 'ordem', 'datagramas', 'trade-offs'],
    importance: 'TCP e UDP são protocolos de transporte com características diferentes. Compreender essas diferenças ajuda a entender como aplicações trocam dados.',
    before: 'Você conhece portas e sabe que TCP e UDP pertencem à camada de Transporte.',
    explanation: 'TCP é orientado à conexão e fornece mecanismos para entrega ordenada e confiável de um fluxo de bytes. UDP é baseado em datagramas e não oferece, por si só, as mesmas garantias de entrega, ordem e retransmissão. Isso não significa que UDP seja sempre mais rápido em qualquer situação; desempenho depende do protocolo de aplicação, rede e objetivo.',
    everyday: 'TCP se parece com uma conversa em que há controle para garantir sequência e confirmação. UDP se parece mais com enviar mensagens independentes sem exigir esse mesmo controle em cada envio.',
    programming: 'Compare uma transferência que precisa preservar todos os dados com uma aplicação que tolera algumas perdas e prioriza baixa sobrecarga.',
    code: 'TCP: conexão + ordem + confiabilidade\nUDP: datagramas + sem garantia própria de entrega/ordem\n\nEscolha depende da aplicação.',
    lineByLine: 'TCP adiciona mecanismos de controle para o fluxo. UDP oferece uma interface mais simples de datagramas. Nenhum deles é universalmente melhor.',
    guided: 'Crie duas situações hipotéticas e justifique qual protocolo de transporte faria mais sentido em cada uma.',
    exercise: 'Qual dos dois fornece entrega ordenada como parte do próprio protocolo: TCP ou UDP?',
    challenge: 'Explique por que a frase “UDP é sempre mais rápido que TCP” é simplista.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“UDP é sempre mais rápido e por isso sempre deve ser escolhido.”',
    common: 'Transformar diferenças de características em uma regra absoluta de desempenho.',
    summary: 'TCP fornece conexão e garantias de ordem/confiabilidade. UDP usa datagramas e não fornece essas mesmas garantias por si só.',
    task: 'Criar um quadro TCP × UDP com vantagens, limitações e exemplos de uso sem tratar um como sempre superior.',
    video: '',
    hint1: 'Pense em qual protocolo controla ordem e retransmissão.',
    hint2: 'Esse protocolo é o TCP.',
    solution: 'TCP fornece entrega ordenada e mecanismos de confiabilidade como parte do protocolo.'
  },
  {
    id: 94, module: 8, title: 'HTTP, HTTPS, DNS e ICMP', time: '50–60 min',
    learn: ['HTTP', 'HTTPS', 'DNS', 'ICMP', 'ping', 'protocolos de aplicação e rede'],
    importance: 'Esses protocolos aparecem diariamente no desenvolvimento web e no diagnóstico básico de conectividade.',
    before: 'Você conhece IP, portas, TCP e UDP.',
    explanation: 'HTTP é usado para comunicação web em nível de aplicação. HTTPS é HTTP protegido por TLS. DNS traduz nomes de domínio em informações como endereços IP. ICMP é usado para mensagens de controle e diagnóstico na rede IP. O comando ping normalmente usa ICMP Echo Request e Echo Reply; ping não é uma conexão TCP.',
    everyday: 'Ao abrir um site, o nome pode ser resolvido por DNS, a comunicação web pode usar HTTPS e ferramentas de diagnóstico podem usar ICMP para verificar alcance básico.',
    programming: 'Descreva o caminho conceitual: domínio → DNS → endereço IP → conexão web por HTTPS.',
    code: 'DNS → resolve nomes\nHTTPS → HTTP protegido por TLS\nICMP → controle/diagnóstico\nping → normalmente ICMP Echo',
    lineByLine: 'DNS ajuda a localizar o endereço associado a um nome. HTTPS protege a comunicação HTTP em trânsito com TLS. ICMP transporta mensagens de controle; ping normalmente usa mensagens Echo.',
    guided: 'Explique o papel de DNS, HTTPS e ICMP sem tratá-los como a mesma coisa.',
    exercise: 'O comando ping normalmente usa TCP, UDP ou ICMP?',
    challenge: 'Explique por que um ping falhar não prova necessariamente que um servidor web está fora do ar.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“ping abre uma conexão TCP com o servidor para testar o site.”',
    common: 'Confundir DNS com HTTP, achar que HTTPS substitui DNS ou tratar ping como teste completo de uma aplicação web.',
    summary: 'HTTP/HTTPS atendem comunicação web; DNS resolve nomes; ICMP auxilia controle e diagnóstico; ping normalmente usa ICMP.',
    task: 'Desenhar um fluxo simples mostrando DNS e HTTPS ao acessar um site e ICMP em um diagnóstico separado.',
    video: '',
    hint1: 'ping usa mensagens Echo.',
    hint2: 'Echo Request e Echo Reply pertencem ao ICMP.',
    solution: 'ping normalmente usa ICMP, não TCP.'
  },
  {
    id: 95, module: 8, title: 'SSH, FTP, SFTP e Telnet', time: '50–60 min',
    learn: ['SSH', 'FTP', 'SFTP', 'FTPS', 'Telnet', 'acesso remoto', 'transferência de arquivos', 'segurança'],
    importance: 'Esses protocolos aparecem em administração de servidores e transferência de arquivos. É essencial não confundir protocolos seguros com alternativas antigas ou diferentes.',
    before: 'Você já estudou portas, TCP/UDP, HTTP/HTTPS, DNS e ICMP.',
    explanation: 'SSH permite acesso remoto seguro e também serve de base para outros recursos. SFTP é um protocolo de transferência de arquivos que funciona sobre SSH; não é a mesma coisa que FTPS. FTP tradicional não protege credenciais e dados por criptografia de forma nativa. Telnet transmite dados sem proteção adequada para administração sensível e não deve ser usado para acesso remoto seguro.',
    everyday: 'É a diferença entre conversar por um canal protegido e enviar informações sensíveis por um meio em que terceiros poderiam lê-las.',
    programming: 'Associe SSH ao acesso remoto seguro e SFTP à transferência de arquivos sobre SSH.',
    code: 'SSH    → acesso remoto seguro (porta convencional 22)\nSFTP   → transferência de arquivos sobre SSH\nFTP    → protocolo tradicional de transferência de arquivos\nFTPS   → FTP protegido com TLS, diferente de SFTP\nTelnet → acesso remoto sem proteção adequada para uso sensível',
    lineByLine: 'SSH oferece um canal seguro. SFTP usa SSH como base. FTPS pertence à família FTP com TLS e não deve ser confundido com SFTP. Telnet não é apropriado para administração remota sensível.',
    guided: 'Faça uma tabela comparando propósito e segurança de SSH, FTP, SFTP, FTPS e Telnet.',
    exercise: 'SFTP funciona sobre SSH ou é apenas outro nome para FTPS?',
    challenge: 'Explique por que Telnet não é recomendado para administração remota com informações sensíveis.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“SFTP e FTPS são dois nomes para o mesmo protocolo.”',
    common: 'Confundir SFTP com FTPS e usar Telnet em situações que exigem confidencialidade.',
    summary: 'SSH fornece acesso remoto seguro. SFTP funciona sobre SSH. FTPS é FTP com TLS. Telnet é inadequado para administração sensível.',
    task: 'Criar um quadro comparativo dos cinco protocolos e destacar quais não devem ser usados para transmitir informações sensíveis sem proteção adicional.',
    video: '',
    hint1: 'O S de SFTP não significa simplesmente “FTP com TLS”.',
    hint2: 'SFTP é baseado em SSH.',
    solution: 'SFTP funciona sobre SSH e é diferente de FTPS.'
  }
);