window.PDZ_DATA.lessons.push(
  {
    id: 31, module: 2, title: 'Introdução ao terminal', time: '50–60 min',
    learn: ['O que são terminal e shell', 'Diretório e caminho', 'Comandos pwd, cd e ls', 'Como navegar com segurança por uma pasta de estudos'],
    importance: 'O terminal aparece em desenvolvimento, Git, servidores e Linux. Aprender a navegar por diretórios ajuda você a entender onde os arquivos estão e onde os comandos são executados.',
    before: 'Você já trabalhou com arquivos Python e múltiplos arquivos no VS Code. Agora vai aprender a enxergar e navegar por essas pastas pelo terminal.',
    explanation: 'Terminal é a interface de texto usada para interagir com o sistema. Shell é o programa que interpreta os comandos digitados. Um diretório é uma pasta. Caminho é a localização de um arquivo ou diretório. Em ambientes Unix-like, pwd mostra o diretório atual, ls lista itens e cd muda de diretório. No Windows, o terminal e alguns comandos podem variar conforme PowerShell, Prompt de Comando, Git Bash ou WSL.',
    everyday: 'Imagine um prédio com vários corredores e salas. O caminho informa em qual sala você está. pwd responde “onde estou?”, ls mostra “o que há aqui?” e cd permite entrar em outra sala.',
    programming: 'Antes de executar um arquivo ou iniciar um repositório Git, você precisa estar na pasta correta. O terminal ajuda a confirmar isso.',
    code: 'pwd\nls\ncd estudos\npwd\ncd ..\npwd',
    lineByLine: 'pwd mostra o caminho atual. ls lista arquivos e pastas. cd estudos entra na pasta chamada estudos. O segundo pwd confirma a nova localização. cd .. volta um nível. O último pwd confirma a volta.',
    guided: 'Crie ou escolha uma pasta de laboratório específica para o curso. Abra o terminal nessa pasta e pratique somente pwd, ls e cd. No Windows, use os equivalentes disponíveis no terminal escolhido.',
    exercise: 'Você está em uma pasta chamada projetos e existe dentro dela uma pasta python-do-zero. Qual comando usaria para entrar nela? Depois, qual comando usaria para voltar para projetos?',
    challenge: 'Navegue por três níveis de pastas de laboratório e escreva a sequência de comandos usada para ir e voltar, confirmando a localização com pwd quando disponível.',
    findError: 'Uma pessoa executa um comando para abrir um arquivo e recebe “arquivo não encontrado”, mas o arquivo existe em outra pasta. Qual é a primeira coisa que ela deve verificar?',
    common: 'Executar comandos na pasta errada, confundir terminal com shell e decorar comandos sem observar o caminho atual.',
    summary: 'Terminal é a interface textual; shell interpreta comandos. pwd mostra onde você está, ls lista conteúdo e cd muda de diretório. Sempre confirme a pasta antes de executar comandos importantes.',
    task: 'Criar uma pasta de laboratório do curso e praticar navegação com pwd, ls e cd sem mexer em arquivos pessoais importantes.', video: null,
    hint1: 'Para entrar em uma pasta usamos cd seguido do nome.', hint2: 'Para voltar um nível em ambientes Unix-like usamos cd ..', solution: 'cd python-do-zero\ncd ..'
  },
  {
    id: 32, module: 2, title: 'Arquivos pelo terminal', time: '50–60 min',
    learn: ['mkdir, touch, cp e mv', 'rm e seus riscos', 'Criar, copiar, mover e remover itens em ambiente de laboratório', 'Boas práticas antes de excluir arquivos'],
    importance: 'Manipular arquivos pelo terminal é útil em desenvolvimento, mas alguns comandos podem apagar conteúdo de forma direta. A prioridade desta aula é aprender com segurança.',
    before: 'Você já sabe navegar por diretórios e deve usar somente uma pasta de laboratório criada para esta aula.',
    explanation: 'mkdir cria diretórios. touch cria um arquivo vazio em muitos ambientes Unix-like. cp copia arquivos. mv move ou renomeia. rm remove arquivos e pode não enviá-los para a lixeira. Por isso, antes de usar rm, confirme com pwd onde você está e com ls qual arquivo será afetado. No Windows, os comandos podem variar conforme o terminal usado.',
    everyday: 'É como organizar uma mesa: você pode criar uma pasta, copiar uma folha, mover um documento ou descartar algo. A diferença é que, no terminal, o descarte pode ser imediato.',
    programming: 'Você pode criar uma pasta aula32, criar um arquivo teste.txt, copiá-lo, renomear a cópia e remover somente esse arquivo de teste.',
    code: 'mkdir aula32\ncd aula32\ntouch teste.txt\ncp teste.txt copia.txt\nmv copia.txt exemplo.txt\nls\nrm exemplo.txt',
    lineByLine: 'mkdir cria a pasta. cd entra nela. touch cria o arquivo de laboratório. cp cria uma cópia. mv renomeia a cópia. ls permite conferir os itens. rm remove somente exemplo.txt. ATENÇÃO: pratique rm apenas em arquivos de laboratório que você acabou de criar.',
    guided: 'Crie uma pasta exclusiva para a aula, faça um arquivo de teste, copie-o, renomeie a cópia e confira tudo com ls. Só depois, se estiver seguro e dentro da pasta de laboratório, remova a cópia criada.',
    exercise: 'Explique a diferença entre cp e mv. Depois diga quais duas verificações você deve fazer antes de usar rm.',
    challenge: 'Monte uma sequência segura que crie uma pasta chamada treino, crie dois arquivos de teste, renomeie um deles e liste o resultado final.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nrm arquivo_importante.txt\nA pessoa não verificou a pasta nem o nome do arquivo antes. O que deveria ter feito?',
    common: 'Usar rm em pasta errada, copiar comandos sem entender, presumir que todo terminal usa exatamente os mesmos comandos e testar exclusão em arquivos pessoais.',
    summary: 'mkdir cria pasta, touch cria arquivo vazio em muitos ambientes, cp copia, mv move/renomeia e rm remove. Exclusão deve ser praticada somente em laboratório e depois de confirmar caminho e arquivo.',
    task: 'Criar uma pasta de laboratório e praticar mkdir, touch, cp e mv. Usar rm apenas em um arquivo descartável criado especificamente para o exercício.', video: null,
    hint1: 'cp mantém o original e cria uma cópia.', hint2: 'Antes de rm, confirme onde está e o nome do alvo.', solution: 'cp copia um arquivo e mantém o original. mv move ou renomeia. Antes de rm: confirme o diretório atual com pwd e confira o alvo com ls.'
  },
  {
    id: 33, module: 2, title: 'Git e controle de versão', time: '50–60 min',
    learn: ['O que é Git', 'Repositório, working tree e staging', 'git init, status, add, commit e log', 'Como registrar versões compreensíveis do projeto'],
    importance: 'Git permite registrar a evolução do código e voltar a estados anteriores. É uma ferramenta central no trabalho de desenvolvimento.',
    before: 'Você já consegue navegar até a pasta correta pelo terminal e manipular arquivos de laboratório.',
    explanation: 'Git é um sistema de controle de versão. Um repositório Git acompanha mudanças de um projeto. Working tree é o estado atual dos arquivos. Staging é a área de preparação do que entrará no próximo commit. Commit é um registro de uma versão. git init inicia um repositório, git status mostra o estado, git add prepara mudanças, git commit registra e git log mostra o histórico.',
    everyday: 'Pense em versões de um trabalho acadêmico: rascunho 1, revisão 2, versão final. Git faz algo parecido, mas de forma estruturada e com histórico das alterações.',
    programming: 'Em uma pasta de exercício, você pode iniciar Git, criar um arquivo, verificar o estado, adicioná-lo ao staging e registrar um commit com uma mensagem clara.',
    code: 'git init\ngit status\ngit add app.py\ngit status\ngit commit -m "adiciona programa inicial"\ngit log',
    lineByLine: 'git init cria a estrutura local do repositório. git status mostra arquivos e mudanças. git add app.py envia esse arquivo para staging. O segundo status permite conferir. git commit registra a versão preparada com uma mensagem. git log mostra o histórico.',
    guided: 'Use uma pasta de laboratório vazia. Inicie um repositório, crie um arquivo simples, veja o status, adicione o arquivo, confira novamente e faça um commit com mensagem que explique a mudança.',
    exercise: 'Explique com suas palavras a diferença entre working tree, staging e commit. Em qual etapa o git add atua?',
    challenge: 'Faça dois commits pequenos e separados em um projeto de laboratório: um para criar o arquivo e outro para alterar uma mensagem dentro dele. Depois veja os dois no git log.',
    findError: 'A pessoa altera três arquivos, executa git commit imediatamente e estranha porque nada foi registrado. O que pode ter faltado?',
    common: 'Confundir salvar arquivo com criar commit, não conferir git status, usar mensagens vagas como “mudança” e pensar que Git depende do GitHub para funcionar.',
    summary: 'Git controla versões localmente. Working tree contém o estado atual, staging prepara mudanças e commit registra uma versão. status ajuda a entender cada etapa.',
    task: 'Criar um repositório Git de laboratório com pelo menos dois commits claros e conferir o histórico com git log.', video: 'https://www.youtube.com/watch?v=xEKo29OWILE',
    hint1: 'git add atua antes do commit.', hint2: 'O staging é a seleção do que será incluído no próximo registro.', solution: 'Working tree = arquivos atuais; staging = mudanças preparadas; commit = registro permanente daquela versão no histórico local. git add coloca mudanças no staging.'
  },
  {
    id: 34, module: 2, title: 'GitHub', time: '50–60 min',
    learn: ['Diferença entre Git e GitHub', 'Repositório local e remoto', 'origin, push, pull e clone', 'Uso de .gitignore e proteção de segredos'],
    importance: 'GitHub permite hospedar repositórios Git, sincronizar trabalho entre máquinas e colaborar. Também é onde muitos projetos profissionais são compartilhados e revisados.',
    before: 'Você já criou commits localmente com Git. Agora vai entender como um repositório remoto se relaciona com esse histórico.',
    explanation: 'Git é o sistema de controle de versão. GitHub é uma plataforma que hospeda repositórios Git. Repositório local fica no seu computador; remoto fica em um serviço como GitHub. origin é um nome convencional para o remoto principal. push envia commits locais ao remoto; pull traz mudanças e integra ao repositório local; clone cria uma cópia local de um repositório remoto. .gitignore lista arquivos que não devem ser versionados.',
    everyday: 'Git é como o sistema que organiza as versões do seu caderno. GitHub é como um lugar externo onde uma cópia dessas versões pode ser guardada e compartilhada.',
    programming: 'Você pode conectar um repositório local a um remoto, fazer push dos commits e depois clonar esse projeto em outro ambiente. Arquivos com segredos devem ficar fora do versionamento.',
    code: 'git remote add origin URL_DO_REPOSITORIO\ngit push -u origin main\ngit pull origin main\ngit clone URL_DO_REPOSITORIO\n\n# exemplo de .gitignore\n.env\n__pycache__/\n*.pyc',
    lineByLine: 'git remote add origin associa um endereço remoto ao nome origin. push envia commits. -u cria o vínculo padrão entre a branch local e remota. pull busca e integra mudanças. clone cria uma cópia local. O .gitignore evita que padrões de arquivos sejam adicionados por engano.',
    guided: 'Em um repositório de exercício, identifique o que está apenas local e o que está no GitHub. Crie um .gitignore que ignore .env e __pycache__ antes de versionar qualquer arquivo sensível.',
    exercise: 'Explique por que Git e GitHub não são a mesma coisa. Depois associe: push, pull e clone às ações corretas.',
    challenge: 'Escreva um pequeno plano de sincronização: criar commit local, conferir status, enviar ao remoto e depois explicar como outra máquina obteria o projeto.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nUma pessoa adicionou senha.txt e .env ao repositório e fez push. Por que isso é um problema e o que deveria ter sido feito antes?',
    common: 'Pensar que GitHub substitui Git, confundir push com pull, versionar .env e outros segredos, e copiar tokens ou senhas para arquivos do projeto.',
    summary: 'Git controla versões; GitHub hospeda repositórios. push envia, pull traz e integra, clone copia um remoto para o computador. Segredos não devem ser versionados e .gitignore ajuda a prevenir isso.',
    task: 'Criar um .gitignore seguro para um projeto Python de laboratório e explicar, em texto, o fluxo local → commit → push → GitHub.', video: null,
    hint1: 'Git funciona mesmo sem GitHub.', hint2: 'push vai para o remoto; pull vem do remoto; clone cria a cópia local.', solution: 'Git é o sistema de controle de versão; GitHub é a plataforma de hospedagem. push envia commits, pull busca e integra mudanças, clone cria uma cópia local. Senhas, tokens, chaves privadas e .env não devem ser versionados.'
  },
  {
    id: 35, module: 2, title: 'Branches, merge e projeto do módulo', time: '50–60 min',
    learn: ['O que são branch e main', 'Criar e trocar de branch com git switch', 'Fazer merge', 'Entender conflitos em nível introdutório', 'Versionar o Sistema de Contatos com Git e GitHub'],
    importance: 'Branches permitem desenvolver mudanças sem misturar imediatamente tudo com a linha principal do projeto. Merge reúne históricos quando a alteração está pronta.',
    before: 'Você já sabe criar commits e entende a diferença entre repositório local e remoto.',
    explanation: 'Branch é uma linha de desenvolvimento dentro do repositório. main costuma ser a branch principal, mas o nome pode variar. git switch -c cria e já troca para uma nova branch. git switch muda entre branches existentes. git merge combina a história de outra branch na branch atual. Um conflito acontece quando o Git não consegue decidir sozinho como combinar mudanças; nesse caso, a pessoa precisa revisar o arquivo e escolher a versão correta antes de concluir o merge.',
    everyday: 'Imagine fazer uma cópia de um capítulo para testar uma nova versão sem alterar o original. Quando você aprova a revisão, incorpora essa versão ao documento principal.',
    programming: 'Você pode criar uma branch para melhorar o Sistema de Contatos, fazer um commit nessa branch, voltar para main e então mesclar a alteração.',
    code: 'git switch -c feature/busca-contato\n# faça uma pequena alteração e salve o arquivo\ngit add .\ngit commit -m "adiciona busca de contato"\ngit switch main\ngit merge feature/busca-contato',
    lineByLine: 'git switch -c cria e entra na nova branch. Depois você altera o projeto, prepara e registra o commit. git switch main volta à principal. git merge feature/busca-contato incorpora a história da branch na branch atual.',
    guided: 'Em um projeto de laboratório, crie uma branch de exercício, faça uma alteração pequena, registre um commit, volte à main e faça o merge. Use git status entre as etapas para conferir o estado.',
    exercise: 'Explique por que é útil trabalhar em uma branch antes de alterar main. Qual branch precisa estar ativa quando você executa git merge feature/exemplo para incorporar feature/exemplo na main?',
    challenge: 'Conclua o Sistema de Contatos do módulo usando funções e módulos, persistência em JSON e tratamento básico de exceções. Versione com commits claros, use pelo menos uma branch de trabalho e faça o merge final. Depois conecte ao GitHub sem versionar segredos.',
    findError: 'Uma pessoa está na branch feature/teste e executa git merge main pensando que isso vai colocar feature/teste dentro de main. O que ela entendeu errado?',
    common: 'Não conferir qual branch está ativa, fazer mudanças grandes sem commits intermediários, confundir a direção do merge e editar marcadores de conflito sem entender o resultado final.',
    summary: 'Branches isolam linhas de desenvolvimento. git switch troca de branch; git merge incorpora outra branch na branch atual. O projeto final reúne funções, módulos, JSON, exceções, Git, GitHub e uma branch de trabalho.',
    task: 'Finalizar o Sistema de Contatos versionado: funções e módulos, persistência em JSON, exceções específicas, commits claros, uma branch de trabalho, merge final, remoto GitHub e .gitignore quando necessário. Não incluir credenciais ou segredos.', video: null,
    hint1: 'O merge acontece na branch em que você está.', hint2: 'Para trazer feature/exemplo para main, primeiro entre em main e depois execute o merge.', solution: 'git switch main\ngit merge feature/exemplo\n\nNo projeto final, mantenha o código organizado em funções e módulos, dados em JSON, tratamento específico de exceções e histórico Git com commits compreensíveis. Não antecipe HTML, CSS, JavaScript, APIs ou banco de dados.'
  }
);