window.PDZ_DATA.lessons.push(
  {
    id: 61, module: 5, title: 'O papel do back-end', time: '50–60 min',
    learn: ['O que é back-end', 'Servidor e regra de negócio', 'Validação', 'Persistência como conceito', 'Relação entre front-end, API e back-end'],
    importance: 'Depois de aprender front-end e HTTP, você precisa entender onde ficam as regras e o processamento que não devem depender apenas do navegador.',
    before: 'Você já sabe como um cliente faz requisições HTTP e como uma API pode responder.',
    explanation: 'Back-end é a parte da aplicação executada no servidor. Ele pode receber requisições, validar dados, aplicar regras de negócio, acessar dados persistidos e devolver respostas. Regra de negócio é uma regra específica do funcionamento do sistema, como impedir uma matrícula duplicada. Persistência é a capacidade de manter dados mesmo depois que o programa termina; neste módulo vamos falar do conceito, mas ainda não usaremos banco de dados.',
    everyday: 'Em um sistema escolar, a tela onde a pessoa digita os dados é front-end. A verificação de regras e o processamento dos dados ficam no back-end.',
    programming: 'Um navegador pode enviar dados de um aluno para uma API. O back-end recebe, verifica e decide como responder.',
    code: 'Cliente → requisição HTTP → API/back-end → validação e regras → resposta HTTP',
    lineByLine: 'O cliente inicia a requisição. A API é a interface exposta pelo back-end. O back-end processa regras e validações. Ao final, envia uma resposta HTTP ao cliente.',
    guided: 'Escolha uma função do seu gerenciador de tarefas e diga o que pertence ao front-end e o que deveria pertencer ao back-end.',
    exercise: 'Explique por que uma regra importante de autorização ou validação não deve existir somente no navegador.',
    challenge: 'Dê três exemplos de regras de negócio para um sistema escolar.',
    findError: 'Afirmação: “Back-end é apenas o banco de dados.” Corrija.',
    common: 'Confundir back-end com banco de dados, servidor com computador físico e validação de interface com segurança completa.',
    summary: 'O back-end roda no servidor, recebe requisições, aplica regras e validações e devolve respostas. Banco de dados é apenas uma possível parte dessa arquitetura.',
    task: 'Desenhar o fluxo front-end → HTTP → back-end → resposta e incluir dois exemplos de regra de negócio.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'Pense no que não pode ser confiado somente ao navegador.',
    hint2: 'Back-end inclui lógica e regras, não apenas armazenamento.',
    solution: 'Uma regra importante não deve ficar apenas no navegador porque o cliente pode ser alterado ou contornado. O servidor precisa validar novamente os dados e aplicar as regras relevantes.'
  },
  {
    id: 62, module: 5, title: 'Primeiros passos com FastAPI', time: '50–60 min',
    learn: ['O que é framework', 'O que é FastAPI', 'Ambiente virtual', 'Dependências', 'Instalação', 'main.py', 'Servidor de desenvolvimento'],
    importance: 'Um ambiente isolado reduz conflitos entre projetos, e FastAPI fornece uma base organizada para criar APIs em Python.',
    before: 'Você já conhece Python, módulos, terminal, Git e conceitos de HTTP/API.',
    explanation: 'Framework é um conjunto de ferramentas e convenções que oferece uma estrutura para desenvolver aplicações. FastAPI é um framework Python voltado à criação de APIs. Um ambiente virtual isola dependências do projeto. A documentação atual recomenda o uv como fluxo principal. Ele pode criar o ambiente automaticamente e registrar as dependências. Também é possível usar python -m venv e pip manualmente.',
    everyday: 'Pense em cada projeto como uma caixa separada de materiais. O ambiente virtual evita misturar versões e pacotes de projetos diferentes.',
    programming: 'Fluxo atual recomendado: criar um projeto, adicionar FastAPI e iniciar o servidor de desenvolvimento.',
    code: 'uv init meu-projeto --bare\ncd meu-projeto\nuv add "fastapi[standard]"\n\n# depois de criar main.py\nuv run fastapi dev',
    lineByLine: 'uv init cria a base do projeto. cd entra na pasta. uv add instala FastAPI e registra a dependência, criando o ambiente do projeto. uv run fastapi dev executa o servidor de desenvolvimento dentro desse ambiente.',
    guided: 'Crie uma pasta de estudo separada e identifique quais arquivos pertencem ao projeto. Não coloque senhas ou tokens no repositório.',
    exercise: 'Explique o que é um ambiente virtual e por que ele ajuda quando dois projetos precisam de versões diferentes de uma biblioteca.',
    challenge: 'Compare em palavras o fluxo com uv e o fluxo manual com python -m venv + pip.',
    findError: 'Afirmação: “Instalar FastAPI globalmente é sempre igual a usar um ambiente virtual.” Corrija.',
    common: 'Misturar dependências globais com as do projeto, esquecer em qual pasta está e copiar comandos sem entender sua finalidade.',
    summary: 'FastAPI é um framework para APIs em Python. Ambientes virtuais isolam dependências; o fluxo atual recomendado pela documentação usa uv.',
    task: 'Criar a estrutura inicial de um projeto FastAPI e registrar no Obsidian para que serve cada comando.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'Ambiente virtual serve para isolamento.',
    hint2: 'Dependência é um pacote externo usado pelo projeto.',
    solution: 'Um ambiente virtual mantém os pacotes de um projeto separados dos demais. Assim, dois projetos podem usar dependências ou versões diferentes sem depender da mesma instalação global.'
  },
  {
    id: 63, module: 5, title: 'Primeira rota GET', time: '50–60 min',
    learn: ['Instância FastAPI', 'Rota', 'Path', 'Decorator @app.get()', 'Função de rota', 'Resposta JSON'],
    importance: 'Criar uma primeira rota transforma conceitos de HTTP em uma API funcionando de verdade.',
    before: 'Você já sabe o que é GET e já preparou um projeto FastAPI.',
    explanation: 'A aplicação começa criando uma instância da classe FastAPI. Uma rota associa um path e um método HTTP a uma função Python. O decorator @app.get("/") registra uma operação GET para o path /. Quando essa rota é acessada, a função é executada. Ao retornar um dicionário Python, FastAPI gera uma resposta apropriada, normalmente serializada como JSON.',
    everyday: 'É como cadastrar um balcão específico: quando alguém chega ao endereço certo e faz o tipo de pedido esperado, aquela função atende a solicitação.',
    programming: 'Vamos criar uma rota raiz que devolve uma mensagem simples.',
    code: 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\ndef inicio():\n    return {"mensagem": "Olá, API!"}',
    lineByLine: 'A primeira linha importa FastAPI. app = FastAPI() cria a aplicação. @app.get("/") registra uma rota GET no path /. def inicio() define a função executada nessa rota. return devolve um dicionário Python que será enviado na resposta.',
    guided: 'Digite o exemplo em main.py, execute o servidor de desenvolvimento e acesse a rota raiz no navegador.',
    exercise: 'Crie uma rota GET /status que devolva {"status": "ok"}.',
    challenge: 'Crie duas rotas GET diferentes e explique por que elas podem devolver conteúdos diferentes.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n@app.get("/status")\nreturn {"status": "ok"}',
    common: 'Esquecer de criar a instância app, colocar return fora de uma função e confundir path com URL completa.',
    summary: 'Uma rota liga método HTTP + path a uma função Python. FastAPI executa a função e monta a resposta.',
    task: 'Criar as rotas / e /status e testar as duas.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'Toda rota precisa estar ligada a uma função.',
    hint2: 'Use @app.get("/status") acima da função.',
    solution: '@app.get("/status")\ndef status():\n    return {"status": "ok"}'
  },
  {
    id: 64, module: 5, title: 'Parâmetros de path e query', time: '50–60 min',
    learn: ['Path parameter', 'Query parameter', 'Anotações de tipo', 'Conversão e validação automática introdutória'],
    importance: 'Parâmetros permitem que uma mesma rota trabalhe com diferentes recursos e filtros sem criar uma função nova para cada valor.',
    before: 'Você já consegue criar rotas GET simples.',
    explanation: 'Path parameter é uma parte variável do caminho, como /alunos/10. Em FastAPI, usamos chaves no path e um parâmetro correspondente na função. Query parameter aparece depois de ? na URL, como ?ativo=true. Se um parâmetro da função não estiver no path, ele pode ser interpretado como query. Anotações de tipo como int e bool ajudam FastAPI a converter e validar valores recebidos.',
    everyday: 'O número de uma sala pode fazer parte do endereço principal; já um filtro como “somente alunos ativos” funciona como uma opção adicional da consulta.',
    programming: 'Uma rota pode receber o ID no path e um filtro ativo na query.',
    code: '@app.get("/alunos/{aluno_id}")\ndef buscar_aluno(aluno_id: int, ativo: bool = True):\n    return {"id": aluno_id, "ativo": ativo}',
    lineByLine: '{aluno_id} marca a parte variável do path. aluno_id: int informa que esperamos um inteiro. ativo: bool = True cria um parâmetro de query opcional com valor padrão True. O return mostra os valores interpretados.',
    guided: 'Teste mentalmente /alunos/5?ativo=false e identifique path parameter e query parameter.',
    exercise: 'Crie GET /cursos/{curso_id} com um query parameter chamado detalhes, do tipo bool e padrão False.',
    challenge: 'Explique o que deve acontecer se alguém enviar texto onde a rota espera um inteiro.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n@app.get("/alunos/{id}")\ndef aluno(aluno_id: int):\n    return {"id": aluno_id}',
    common: 'Usar nomes diferentes entre o placeholder do path e o parâmetro esperado, confundir query com path e esquecer tipos.',
    summary: 'Path parameters identificam partes variáveis do caminho; query parameters adicionam opções ou filtros à URL. FastAPI usa tipos para conversão e validação.',
    task: 'Criar uma rota com um parâmetro de path e um de query e registrar três URLs de teste.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'O nome dentro de { } deve corresponder ao parâmetro da função.',
    hint2: 'O parâmetro que não aparece no path pode funcionar como query.',
    solution: '@app.get("/cursos/{curso_id}")\ndef curso(curso_id: int, detalhes: bool = False):\n    return {"id": curso_id, "detalhes": detalhes}'
  },
  {
    id: 65, module: 5, title: 'Corpo da requisição e Pydantic', time: '50–60 min',
    learn: ['Request body', 'Modelo de dados', 'Pydantic', 'BaseModel', 'Validação de tipos', 'Modelo de entrada não é tabela'],
    importance: 'APIs frequentemente recebem dados estruturados. Modelos ajudam a descrever o formato esperado e rejeitar entradas incompatíveis.',
    before: 'Você já conhece path/query parameters, JSON e requisições HTTP.',
    explanation: 'Request body é o conteúdo enviado no corpo da requisição. Em FastAPI, classes baseadas em Pydantic BaseModel podem descrever e validar os dados esperados. Se o endpoint declara um parâmetro cujo tipo é um modelo Pydantic, FastAPI interpreta os dados do body, valida tipos e cria um objeto do modelo. Esse modelo não é uma tabela de banco de dados: ele representa uma estrutura de dados da aplicação.',
    everyday: 'Um formulário de matrícula possui campos esperados. O modelo funciona como uma ficha de regras: nome precisa existir, idade precisa ser número, e assim por diante.',
    programming: 'Crie um modelo simples para receber nome e idade de um aluno.',
    code: 'from pydantic import BaseModel\n\nclass AlunoEntrada(BaseModel):\n    nome: str\n    idade: int\n\n@app.post("/alunos")\ndef criar_aluno(aluno: AlunoEntrada):\n    return aluno',
    lineByLine: 'BaseModel é importado do Pydantic. AlunoEntrada herda de BaseModel. nome e idade definem os campos e tipos esperados. Na rota POST, aluno: AlunoEntrada informa que o body deve seguir esse modelo. O objeto validado é devolvido na resposta.',
    guided: 'Compare um body válido {"nome":"Ana","idade":20} com um body sem o campo nome e identifique por que o segundo não segue o modelo.',
    exercise: 'Crie um modelo CursoEntrada com nome: str e carga_horaria: int.',
    challenge: 'Explique por que um modelo Pydantic não deve ser chamado automaticamente de “tabela do banco”.',
    findError: 'Afirmação: “Toda classe BaseModel cria automaticamente uma tabela PostgreSQL.” Corrija.',
    common: 'Confundir modelo de validação com modelo de banco, esquecer tipos dos campos e assumir que front-end dispensa validação no servidor.',
    summary: 'Pydantic descreve e valida dados. Em FastAPI, um modelo BaseModel pode representar o body de uma requisição sem ser uma tabela de banco de dados.',
    task: 'Criar AlunoEntrada e CursoEntrada e escrever dois exemplos de body válido para cada modelo.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'Comece importando BaseModel.',
    hint2: 'Cada campo é escrito como nome: tipo.',
    solution: 'class CursoEntrada(BaseModel):\n    nome: str\n    carga_horaria: int'
  }
);