window.PDZ_DATA = {
  modules: [
    { id: 1, title: 'Fundamentos de Programação e Python', lessons: '1–20', description: 'Base para compreender programação e criar pequenos programas em Python.' },
    { id: 2, title: 'Python Intermediário, Arquivos, POO, Terminal e Git', lessons: '21–35', description: 'Organização de programas, persistência, orientação a objetos e versionamento.' },
    { id: 3, title: 'Desenvolvimento Front-end', lessons: '36–50', description: 'HTML, CSS e JavaScript para interfaces web.' },
    { id: 4, title: 'Internet, HTTP e APIs', lessons: '51–60', description: 'Como cliente, servidor, HTTP e APIs se conectam.' },
    { id: 5, title: 'FastAPI', lessons: '61–70', description: 'Construção de APIs back-end com Python e FastAPI.' },
    { id: 6, title: 'PostgreSQL e SQL', lessons: '71–80', description: 'Banco de dados relacional, SQL e modelagem.' },
    { id: 7, title: 'Full Stack', lessons: '81–85', description: 'Integração entre front-end, API e banco de dados.' },
    { id: 8, title: 'Redes', lessons: '86–95', description: 'OSI, TCP/IP, IP, portas e protocolos essenciais.' },
    { id: 9, title: 'Linux', lessons: '96–100', description: 'Diretórios, comandos, permissões e processos.' },
    { id: 10, title: 'Deploy, Domínios e DNS', lessons: '101–110', description: 'Publicação de aplicações e fundamentos de DNS.' },
    { id: 11, title: 'Segurança', lessons: '111–115', description: 'Princípios defensivos de segurança de aplicações.' },
    { id: 12, title: 'Criptografia e Projeto Final', lessons: '116–120', description: 'Criptografia conceitual e projeto Full Stack final.' }
  ],
  lessons: [
    {
      id: 1, module: 1, title: 'O que é programação?', time: '50–60 min',
      learn: ['O que são computador, hardware e software', 'O que significam programa, programação e código-fonte', 'O que é uma linguagem de programação', 'Como pensar em algoritmo, entrada, processamento e saída'],
      importance: 'Antes de escrever código, você precisa entender o que está pedindo ao computador e como organizar instruções de forma lógica.',
      before: 'Nenhum conhecimento prévio é necessário.',
      explanation: 'Programar significa criar instruções que podem ser executadas pelo computador. Hardware é a parte física; software é o conjunto de programas e dados. Um programa é uma sequência organizada de instruções. O código-fonte é a forma escrita dessas instruções em uma linguagem de programação. Um algoritmo é uma sequência de passos para resolver um problema.',
      everyday: 'Pense no preparo de café: existe uma ordem de passos. Se você mudar etapas importantes de lugar, o resultado pode sair errado. Um algoritmo funciona de forma parecida: passos claros, em uma sequência adequada.',
      programming: 'Uma calculadora pode receber 10 e 5 como entrada, realizar 10 + 5 como processamento e mostrar 15 como saída.',
      code: 'print("Olá, mundo!")',
      lineByLine: 'Por enquanto, observe apenas que essa instrução pede ao Python para mostrar um texto na tela. A sintaxe será explicada com calma na Aula 4.',
      guided: 'Escolha uma situação cotidiana, como usar um caixa eletrônico, e identifique o que entra, o que é processado e o que sai.',
      exercise: 'Explique com suas palavras a diferença entre hardware e software. Depois identifique entrada, processamento e saída em uma calculadora.',
      challenge: 'Escreva um algoritmo, em passos numerados, para uma tarefa simples do seu dia.',
      findError: 'Sequência: 1) beber o café; 2) colocar água para aquecer; 3) preparar o café. O que está fora de ordem?',
      common: 'Confundir programa com programação e pensar que algoritmo precisa ser escrito em uma linguagem de programação.',
      summary: 'Programar é criar instruções. Algoritmo organiza os passos. Muitos problemas podem ser entendidos como entrada → processamento → saída.',
      task: 'Criar um algoritmo cotidiano com pelo menos 5 passos.', video: null,
      hint1: 'Pense em algo que você faz sempre na mesma ordem.', hint2: 'Comece pelo estado inicial e termine no resultado desejado.', solution: 'Exemplo possível: preparar um sanduíche — separar ingredientes, abrir o pão, colocar recheio, fechar o pão e servir.'
    },
    {
      id: 2, module: 1, title: 'Como o computador executa um programa', time: '50–60 min',
      learn: ['CPU, memória RAM e armazenamento', 'Sistema operacional, programa e processo', 'Instrução e interpretador'],
      importance: 'Entender o caminho do código até a execução ajuda você a compreender erros, desempenho e o papel do Python.',
      before: 'Lembre da diferença entre hardware, software e programa.',
      explanation: 'A CPU executa instruções. A RAM guarda temporariamente dados em uso. O armazenamento mantém arquivos mesmo após desligar o computador. O sistema operacional gerencia recursos e programas. Quando um programa está rodando, ele é um processo. O interpretador Python lê e executa o código Python.',
      everyday: 'Imagine uma cozinha: a receita representa instruções, a bancada é um espaço de trabalho temporário e a despensa guarda itens por mais tempo. É apenas uma analogia para ajudar a visualizar os papéis.',
      programming: 'Ao executar um arquivo Python, o sistema operacional inicia um processo e o interpretador Python lê as instruções do arquivo para que elas sejam executadas.',
      code: 'print("Programa em execução")',
      lineByLine: 'O interpretador Python lê essa instrução e solicita que o texto seja exibido. A CPU participa da execução das operações necessárias.',
      guided: 'Classifique: processador, memória RAM, SSD e Windows/Linux entre CPU, memória, armazenamento e sistema operacional.',
      exercise: 'Explique a diferença entre RAM e armazenamento e diga o que significa um programa estar em execução.',
      challenge: 'Descreva em 4 passos o que acontece entre executar um arquivo Python e ver uma mensagem na tela.',
      findError: 'Afirmação: “A RAM é o lugar onde seus arquivos ficam salvos permanentemente.” Corrija.',
      common: 'Pensar que CPU guarda arquivos ou que RAM e armazenamento são a mesma coisa.',
      summary: 'CPU executa, RAM guarda temporariamente, armazenamento persiste, sistema operacional gerencia e o interpretador executa código Python.',
      task: 'Fazer um pequeno esquema com CPU, RAM, armazenamento e sistema operacional.', video: null,
      hint1: 'Pense em temporário versus permanente.', hint2: 'Depois inclua o papel do interpretador.', solution: 'Uma sequência possível: o sistema operacional inicia o processo → o interpretador abre o código → as instruções são executadas → a saída aparece na tela.'
    },
    {
      id: 3, module: 1, title: 'Preparando o Python', time: '50–60 min',
      learn: ['O que é Python e o interpretador', 'O papel do VS Code', 'Arquivos .py', 'Terminal e execução de um programa'],
      importance: 'Você precisa de um ambiente simples e confiável para praticar o código do curso.',
      before: 'Você já sabe que o interpretador executa o código Python.',
      explanation: 'Python é a linguagem principal do início do curso. O interpretador executa programas Python. VS Code é um editor de código. Arquivos Python normalmente usam a extensão .py. O terminal é uma interface textual para executar comandos.',
      everyday: 'Pense no VS Code como a mesa onde você escreve, no arquivo .py como a folha que guarda o texto e no interpretador como quem lê as instruções para executá-las.',
      programming: 'Você cria uma pasta de estudos, salva um arquivo como aula03.py e executa esse arquivo com o Python.',
      code: 'python aula03.py',
      lineByLine: 'python chama o interpretador; aula03.py indica qual arquivo deve ser executado. O comando exato pode variar conforme a instalação do sistema.',
      guided: 'Crie uma pasta para o curso e um arquivo chamado aula03.py. Abra-o no VS Code.',
      exercise: 'Associe cada item à sua função: Python, interpretador, VS Code, arquivo .py e terminal.',
      challenge: 'Crie outro arquivo .py com um nome escolhido por você e execute-o.',
      findError: 'Você tenta executar aula03.py, mas o arquivo foi salvo como aula03.txt. Qual é o problema?',
      common: 'Salvar o arquivo com extensão errada ou executar o comando em uma pasta diferente da que contém o arquivo.',
      summary: 'VS Code edita, .py guarda o código, o terminal envia comandos e o interpretador executa Python.',
      task: 'Preparar uma pasta de estudos e deixar um arquivo .py pronto para a próxima aula.', video: null,
      hint1: 'Confira a extensão do arquivo.', hint2: 'Confira também em qual pasta o terminal está.', solution: 'O arquivo precisa estar salvo com extensão .py e o terminal deve apontar para a pasta correta antes da execução.'
    },
    {
      id: 4, module: 1, title: 'Primeiro programa em Python', time: '50–60 min',
      learn: ['print()', 'Strings e aspas', 'Comentários', 'Sintaxe inicial e erros simples'],
      importance: 'Aqui você começa a escrever e executar código Python de verdade.',
      before: 'Tenha um arquivo .py pronto no VS Code.',
      explanation: 'print() mostra informações na tela. Textos são strings e normalmente ficam entre aspas simples ou duplas. Comentários começam com # e servem para explicar o código sem serem executados. Sintaxe é o conjunto de regras de escrita da linguagem.',
      everyday: 'Uma string é como uma etiqueta de texto que você quer mostrar. As aspas indicam ao Python onde o texto começa e termina.',
      programming: 'Você pode usar várias chamadas de print() para mostrar mensagens diferentes.',
      code: 'print("Olá, mundo!")\nprint(\'Bom dia\')\n# Este é um comentário\nprint("Python")',
      lineByLine: 'Cada print() pede uma saída. As aspas delimitam o texto. A linha começando com # é comentário e não gera saída.',
      guided: 'Crie um programa que mostre seu nome, uma mensagem de boas-vindas e uma frase sobre por que você quer aprender programação.',
      exercise: 'Escreva três print() diferentes. Depois explique o que acontece quando uma aspa não é fechada.',
      challenge: 'Crie uma pequena apresentação pessoal usando apenas print(), strings e comentários.',
      findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nprint("Olá)',
      common: 'Esquecer de fechar aspas ou parênteses e misturar caracteres sem perceber.',
      summary: 'print() exibe informações, strings são textos entre aspas, comentários começam com # e a sintaxe precisa estar correta.',
      task: 'Criar um arquivo com pelo menos 4 mensagens usando print() e 2 comentários.', video: 'https://www.youtube.com/watch?v=31llNGKWDdo',
      hint1: 'Comece com uma linha por mensagem.', hint2: 'Use comentários para separar partes do programa.', solution: '# Apresentação\nprint("Meu nome é Júlia")\nprint("Estou começando em Python")\n# Objetivo\nprint("Quero aprender a criar aplicações")'
    },
    {
      id: 5, module: 1, title: 'Algoritmos e pensamento computacional', time: '50–60 min',
      learn: ['Decomposição de problemas', 'Sequência', 'Entrada, processamento e saída', 'Pseudocódigo e resolução de problemas'],
      importance: 'Organizar o raciocínio antes de escrever código reduz confusão e ajuda a resolver problemas maiores.',
      before: 'Você já viu algoritmo e entrada → processamento → saída na Aula 1.',
      explanation: 'Pensamento computacional envolve decompor um problema em partes menores, organizar uma sequência de passos e identificar dados de entrada, processamento e resultado. Pseudocódigo descreve a lógica de forma estruturada sem depender da sintaxe de uma linguagem específica.',
      everyday: 'A tarefa “preparar-se para sair de casa” pode ser dividida em etapas menores: escolher roupa, se arrumar, separar itens necessários, verificar horário e sair.',
      programming: 'Para calcular uma média, precisamos receber as notas, somá-las, dividir pela quantidade e mostrar o resultado.',
      code: 'INÍCIO\n  receber nota 1\n  receber nota 2\n  somar as notas\n  dividir a soma por 2\n  mostrar a média\nFIM',
      lineByLine: 'O pseudocódigo começa, recebe os dados, realiza o cálculo, apresenta o resultado e termina. Ainda não precisamos usar input(), pois isso será ensinado depois.',
      guided: 'Escolha um problema simples e escreva entrada, processamento e saída antes de detalhar os passos.',
      exercise: 'Monte o pseudocódigo de um cálculo de dobro de um número, sem usar sintaxe Python.',
      challenge: 'Criar o algoritmo completo para cálculo de média escolar usando entrada → processamento → saída.',
      findError: 'Um algoritmo tenta mostrar a média antes de receber as notas. Explique por que a ordem está errada.',
      common: 'Pular etapas, misturar solução com código antes de organizar a lógica e usar conceitos ainda não estudados.',
      summary: 'Decompor, ordenar e identificar entrada, processamento e saída ajuda a transformar problemas em algoritmos claros.',
      task: 'Finalizar o projeto da semana: algoritmo de média escolar em pseudocódigo.', video: null,
      hint1: 'Liste primeiro quais dados são necessários.', hint2: 'Depois escreva o cálculo e, por último, a saída.', solution: 'INÍCIO\n  receber nota 1\n  receber nota 2\n  calcular soma = nota 1 + nota 2\n  calcular média = soma / 2\n  mostrar média\nFIM'
    }
  ]
};
