window.PDZ_DATA.lessons.push(
  {
    id: 41, module: 3, title: 'Introdução ao CSS', time: '50–60 min',
    learn: ['O que é CSS', 'Seletor, propriedade e valor', 'Classes e IDs', 'Cascade', 'Stylesheet externo'],
    importance: 'HTML organiza o conteúdo; CSS controla sua apresentação. Separar estrutura e estilo deixa a página mais organizada e fácil de manter.',
    before: 'Você já consegue criar páginas HTML com conteúdo semântico e formulários.',
    explanation: 'CSS significa Cascading Style Sheets. Uma regra CSS possui um seletor e um bloco de declarações. Cada declaração normalmente contém uma propriedade e um valor. Seletores podem atingir elementos, classes e IDs. Classes podem ser reutilizadas; IDs devem identificar um elemento de forma única na página. A cascade é o conjunto de regras que o navegador usa para decidir qual estilo prevalece quando mais de uma regra pode afetar o mesmo elemento. Para projetos, vamos priorizar um arquivo CSS externo ligado ao HTML com link.',
    everyday: 'O HTML é como o conteúdo de um cartaz; o CSS define fonte, tamanho, espaçamento e organização visual sem mudar a mensagem do cartaz.',
    programming: 'Crie styles.css e conecte-o ao HTML com <link rel="stylesheet" href="styles.css">.',
    code: '/* styles.css */\nbody {\n  font-family: Arial, sans-serif;\n}\n\n.titulo {\n  font-size: 2rem;\n}\n\n#conteudo {\n  max-width: 800px;\n}',
    lineByLine: 'body é o seletor do elemento. font-family é a propriedade e Arial, sans-serif é o valor. .titulo seleciona elementos com class="titulo". #conteudo seleciona o elemento com id="conteudo". As chaves agrupam as declarações.',
    guided: 'Crie styles.css, conecte-o ao index.html e aplique uma classe ao título principal.',
    exercise: 'Crie uma classe .destaque e aplique duas propriedades visuais a um parágrafo.',
    challenge: 'Explique por que uma classe costuma ser mais adequada que um ID quando o mesmo estilo será usado em vários elementos.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n.titulo {\n  font-size = 2rem;\n}',
    common: 'Esquecer ponto antes de classe, # antes de ID, usar = no lugar de : e colocar estilos espalhados no HTML sem necessidade.',
    summary: 'CSS define apresentação. Regras combinam seletor, propriedades e valores; a cascade determina quais estilos prevalecem.',
    task: 'Criar styles.css externo e estilizar título, parágrafo e uma classe reutilizável.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'Uma declaração CSS usa propriedade: valor;.',
    hint2: 'Classes começam com ponto no seletor.',
    solution: '.destaque {\n  font-weight: bold;\n  font-size: 1.1rem;\n}'
  },
  {
    id: 42, module: 3, title: 'Box Model', time: '50–60 min',
    learn: ['Content', 'Padding', 'Border', 'Margin', 'box-sizing: border-box'],
    importance: 'Entender o Box Model evita confusão com tamanhos e espaçamentos e é essencial para construir layouts previsíveis.',
    before: 'Você já sabe criar regras CSS e usar seletores.',
    explanation: 'O navegador trata muitos elementos como caixas. Content é a área do conteúdo. Padding é o espaço interno entre conteúdo e borda. Border contorna a caixa. Margin cria espaço externo entre a caixa e outros elementos. Por padrão, width normalmente se refere à área de conteúdo; com box-sizing: border-box, padding e border passam a ser incluídos no tamanho declarado, o que facilita prever dimensões.',
    everyday: 'Imagine um quadro: a imagem é o content, o espaço entre a imagem e a moldura lembra o padding, a moldura é o border e a distância até outros quadros lembra a margin.',
    programming: 'Vamos criar um cartão com largura, padding, border e margin usando border-box.',
    code: '* {\n  box-sizing: border-box;\n}\n\n.card {\n  width: 300px;\n  padding: 16px;\n  border: 1px solid;\n  margin: 20px;\n}',
    lineByLine: 'O seletor * atinge todos os elementos e define border-box. .card recebe largura total de 300px considerando padding e border. padding cria espaço interno; border cria a borda; margin cria espaço externo.',
    guided: 'Crie um div com class="card", adicione um título e um parágrafo e aplique o CSS do exemplo.',
    exercise: 'Explique a diferença entre padding e margin e altere cada um separadamente para observar o efeito.',
    challenge: 'Se um elemento usa width: 300px com border-box, explique por que adicionar padding não aumenta sua largura total declarada.',
    findError: 'Afirmação: “margin cria espaço entre o texto e a borda do próprio elemento.” Corrija.',
    common: 'Confundir margin com padding e calcular larguras sem considerar o box-sizing.',
    summary: 'O Box Model é formado por content, padding, border e margin. border-box torna dimensões mais previsíveis.',
    task: 'Criar dois cartões e testar diferentes valores de padding e margin.',
    video: '',
    hint1: 'Padding fica dentro da borda.',
    hint2: 'Margin fica fora da borda.',
    solution: 'Padding é o espaço interno entre conteúdo e borda. Margin é o espaço externo que separa o elemento de outros elementos.'
  },
  {
    id: 43, module: 3, title: 'Tipografia, cores e unidades', time: '50–60 min',
    learn: ['Fontes e legibilidade', 'Cores', 'px, %, rem, vh e vw', 'Escolha de unidades conforme o contexto'],
    importance: 'Uma interface precisa ser legível e adaptar tamanhos de forma coerente; unidades diferentes resolvem necessidades diferentes.',
    before: 'Você conhece regras CSS e o Box Model.',
    explanation: 'CSS permite controlar família tipográfica, tamanho, peso, altura de linha e cores. px é uma unidade CSS prática para vários detalhes, mas não deve ser a única escolha. rem é relativa ao tamanho da fonte do elemento raiz e é útil para tipografia e espaçamentos escaláveis. % é relativa a um valor de referência do contexto. vh e vw representam porcentagens da altura e largura da viewport. Não existe uma unidade universalmente melhor: a escolha depende do que precisa ser dimensionado. Legibilidade e capacidade de zoom devem ser preservadas.',
    everyday: 'Um texto de estudo precisa de hierarquia visual: título destacado, corpo confortável para leitura e contraste suficiente entre texto e fundo.',
    programming: 'Vamos definir uma base tipográfica simples e um contêiner com largura flexível.',
    code: 'body {\n  font-family: Arial, sans-serif;\n  font-size: 1rem;\n  line-height: 1.5;\n}\n\nh1 {\n  font-size: 2rem;\n}\n\n.container {\n  width: 90%;\n  max-width: 900px;\n}',
    lineByLine: '1rem acompanha o tamanho-base configurado no navegador. line-height melhora o espaçamento vertical. O h1 usa duas vezes o tamanho raiz. width: 90% torna o contêiner flexível e max-width impede crescimento excessivo.',
    guided: 'Aplique uma hierarquia tipográfica à página das aulas anteriores e teste o zoom do navegador.',
    exercise: 'Crie estilos para h1, h2 e p usando rem e explique por que escolheu tamanhos diferentes.',
    challenge: 'Explique uma situação em que % é mais adequada que px e outra em que rem ajuda na tipografia.',
    findError: 'Afirmação: “vw é sempre a melhor unidade para tamanho de texto porque se adapta à tela.” Corrija.',
    common: 'Usar unidades sem entender a referência, reduzir texto demais em telas pequenas e depender apenas de cor para comunicar informação.',
    summary: 'Tipografia e cores precisam priorizar legibilidade. px, %, rem, vh e vw têm referências e usos diferentes.',
    task: 'Melhorar a tipografia da página e criar um contêiner com width percentual e max-width.',
    video: '',
    hint1: 'rem usa como referência o tamanho de fonte do elemento raiz.',
    hint2: '% depende do contexto; vw e vh dependem da viewport.',
    solution: 'Exemplo: .conteudo { width: 90%; } acompanha o espaço disponível; h1 { font-size: 2rem; } mantém uma relação clara com o tamanho-base do texto.'
  },
  {
    id: 44, module: 3, title: 'Flexbox e Grid', time: '50–60 min',
    learn: ['Flexbox como ferramenta principalmente unidimensional', 'Grid como ferramenta principalmente bidimensional', 'Alinhamento e distribuição', 'Escolha da ferramenta conforme o layout'],
    importance: 'Flexbox e Grid são ferramentas centrais do CSS moderno para organizar elementos sem depender de técnicas antigas de posicionamento.',
    before: 'Você já entende caixas, tamanhos e espaçamentos.',
    explanation: 'Flexbox é especialmente adequado para organizar itens principalmente em uma dimensão por vez: linha ou coluna. Grid é especialmente adequado para layouts em linhas e colunas ao mesmo tempo. Essa distinção é uma orientação, não uma proibição: ambos podem resolver diferentes layouts. Em Flexbox, display: flex cria o contexto flexível; gap define espaçamento; justify-content atua no eixo principal e align-items no eixo transversal. Em Grid, display: grid cria a grade e grid-template-columns define colunas.',
    everyday: 'Uma barra de navegação em uma linha combina naturalmente com Flexbox. Uma galeria organizada em várias linhas e colunas combina naturalmente com Grid.',
    programming: 'Crie uma navegação flexível e uma grade de cartões.',
    code: '.menu {\n  display: flex;\n  gap: 1rem;\n  align-items: center;\n}\n\n.grade {\n  display: grid;\n  grid-template-columns: repeat(2, 1fr);\n  gap: 1rem;\n}',
    lineByLine: '.menu ativa Flexbox e cria espaço entre itens. align-items alinha no eixo transversal. .grade ativa Grid. repeat(2, 1fr) cria duas colunas que dividem o espaço disponível. gap separa as células.',
    guided: 'Organize os links da navegação com Flexbox e dois cartões com Grid.',
    exercise: 'Crie uma linha com três botões usando Flexbox e uma grade com quatro cartões usando duas colunas.',
    challenge: 'Escolha Flexbox ou Grid para uma barra de navegação e para uma galeria de cartões e justifique.',
    findError: 'Afirmação: “Flexbox só funciona horizontalmente e Grid só pode ser usado em páginas inteiras.” Corrija.',
    common: 'Tratar Flexbox e Grid como concorrentes absolutos e decorar propriedades sem identificar eixos e estrutura do layout.',
    summary: 'Flexbox é principalmente unidimensional; Grid é principalmente bidimensional. Eles podem ser combinados no mesmo projeto.',
    task: 'Criar um menu com Flexbox e uma seção de cartões com Grid.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'Para uma única linha de itens, comece pensando em Flexbox.',
    hint2: 'Para linhas e colunas organizadas juntas, Grid costuma ser natural.',
    solution: '.botoes { display: flex; gap: 1rem; }\n.cards { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }'
  },
  {
    id: 45, module: 3, title: 'Responsividade', time: '50–60 min',
    learn: ['Viewport', 'Larguras flexíveis', 'max-width', 'Media queries', 'Mobile-first'],
    importance: 'Pessoas acessam páginas em telas de tamanhos diferentes. Responsividade permite que conteúdo e controles continuem utilizáveis sem criar uma página separada para cada dispositivo.',
    before: 'Você já sabe criar layouts com Box Model, Flexbox e Grid.',
    explanation: 'Responsividade é a capacidade de uma interface se adaptar a diferentes espaços disponíveis. A meta viewport no HTML ajuda o navegador móvel a usar corretamente a largura do dispositivo. Larguras flexíveis e max-width reduzem dependência de tamanhos fixos. Media queries aplicam regras quando determinadas condições são atendidas. Mobile-first significa começar com uma base adequada a telas menores e acrescentar mudanças para espaços maiores, quando necessário.',
    everyday: 'O mesmo conteúdo precisa continuar legível no celular e no computador: cartões podem ficar em uma coluna no celular e em várias colunas quando houver espaço.',
    programming: 'Comece com uma coluna e, a partir de uma largura adequada ao conteúdo, altere a grade para duas colunas.',
    code: '.grade {\n  display: grid;\n  grid-template-columns: 1fr;\n  gap: 1rem;\n}\n\n@media (min-width: 768px) {\n  .grade {\n    grid-template-columns: repeat(2, 1fr);\n  }\n}',
    lineByLine: 'A regra-base usa uma coluna e funciona em telas estreitas. A media query entra quando a viewport possui pelo menos 768px. Nesse espaço, a grade passa a duas colunas. O ponto de quebra deve ser escolhido conforme o conteúdo e o layout, não por um modelo específico de aparelho.',
    guided: 'Abra as ferramentas do navegador ou redimensione a janela e observe quando seu conteúdo começa a precisar de outra organização.',
    exercise: 'Faça uma grade ficar em uma coluna em telas menores e duas colunas quando houver espaço suficiente.',
    challenge: 'Explique por que responsividade não significa apenas “diminuir tudo” em uma tela pequena.',
    findError: 'Afirmação: “Mobile-first significa desenvolver somente para celulares.” Corrija.',
    common: 'Usar larguras fixas excessivas, escolher breakpoints apenas por nomes de aparelhos e reduzir controles a tamanhos difíceis de usar.',
    summary: 'Responsividade combina viewport, dimensões flexíveis, max-width e media queries. Mobile-first começa pela base menor e amplia conforme necessário.',
    task: 'Transformar a página de estudos em uma página responsiva e verificar leitura e navegação em larguras diferentes.',
    video: 'https://www.youtube.com/watch?v=jgQjeqGRdgA',
    hint1: 'Comece com uma coluna como regra-base.',
    hint2: 'Use min-width para acrescentar o layout de telas com mais espaço.',
    solution: '.cards { display: grid; grid-template-columns: 1fr; }\n@media (min-width: 768px) { .cards { grid-template-columns: repeat(2, 1fr); } }'
  }
);