window.PDZ_DATA.lessons.push(
  {
    id: 96, module: 9, title: 'Estrutura de diretórios do Linux', time: '50–60 min',
    learn: ['sistema de arquivos', 'diretório raiz /', '/home', '/etc', '/var', '/usr', '/tmp'],
    importance: 'Conhecer a estrutura de diretórios ajuda a entender onde ficam arquivos pessoais, configurações, programas, logs e arquivos temporários.',
    before: 'Você já estudou terminal e caminhos básicos no Módulo 2. Agora vai organizar esse conhecimento dentro do Linux.',
    explanation: 'No Linux, o sistema de arquivos é organizado como uma árvore. O ponto inicial é /. A partir dele existem diretórios como /home, onde normalmente ficam pastas pessoais; /etc, com muitos arquivos de configuração do sistema; /var, usado para dados que mudam com frequência, como logs; /usr, que contém muitos programas, bibliotecas e arquivos compartilhados; e /tmp, destinado a arquivos temporários. / não é a mesma coisa que sua pasta pessoal.',
    everyday: 'Imagine um prédio com um hall principal. O / é esse ponto inicial. A partir dele você entra em diferentes setores, cada um com uma função.',
    programming: 'Observe caminhos como /home/julia/projetos/app e identifique qual parte representa a raiz e quais são os diretórios abaixo dela.',
    code: '/\n├── home\n├── etc\n├── var\n├── usr\n└── tmp',
    lineByLine: '/ é a raiz do sistema de arquivos. home, etc, var, usr e tmp aparecem abaixo dela na hierarquia.',
    guided: 'Escreva uma frase sobre a função geral de /home, /etc, /var, /usr e /tmp.',
    exercise: 'Qual diretório costuma concentrar as pastas pessoais dos usuários? E qual é a raiz de todo o sistema de arquivos?',
    challenge: 'Explique por que dizer que “/ é a pasta pessoal do usuário” está errado.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“No Linux, / e /home são exatamente a mesma coisa.”',
    common: 'Confundir / com /home ou pensar que todos os arquivos do sistema ficam na pasta pessoal.',
    summary: 'O Linux organiza arquivos em uma hierarquia iniciada por /. Diretórios importantes têm finalidades diferentes.',
    task: 'Criar um pequeno mapa dos diretórios /, /home, /etc, /var, /usr e /tmp com suas funções.',
    video: '',
    hint1: 'A raiz é representada por uma barra.',
    hint2: 'As pastas pessoais normalmente ficam dentro de /home.',
    solution: '/ é a raiz. /home normalmente contém diretórios pessoais dos usuários.'
  },
  {
    id: 97, module: 9, title: 'Caminhos absolutos e relativos', time: '50–60 min',
    learn: ['caminho absoluto', 'caminho relativo', '.', '..', '~', 'cd'],
    importance: 'Caminhos corretos são essenciais para abrir arquivos, executar comandos e navegar em projetos sem se perder no sistema.',
    before: 'Você conhece a estrutura hierárquica do sistema de arquivos Linux.',
    explanation: 'Um caminho absoluto começa na raiz / e indica a localização completa, como /home/julia/projetos. Um caminho relativo parte do diretório atual, como projetos/app. O símbolo . representa o diretório atual, .. representa o diretório pai e ~ normalmente representa a pasta pessoal do usuário atual. O comando cd muda o diretório atual.',
    everyday: 'Um endereço completo com cidade, rua e número se parece com um caminho absoluto. Dizer “a sala ao lado” depende de onde você está, como um caminho relativo.',
    programming: 'Se você está em /home/julia, cd projetos leva a /home/julia/projetos; cd .. volta para /home.',
    code: 'pwd\ncd /home/julia/projetos\ncd ..\ncd .\ncd ~',
    lineByLine: 'pwd mostra o diretório atual. cd com caminho absoluto vai diretamente ao destino. cd .. sobe um nível. cd . permanece no diretório atual. cd ~ vai para a pasta pessoal.',
    guided: 'Partindo de /home/julia/projetos, descreva o resultado de cd .. e depois cd ~.',
    exercise: 'Qual é a diferença entre /home/julia/documentos e documentos quando o diretório atual é /home/julia?',
    challenge: 'Explique por que o mesmo caminho relativo pode apontar para lugares diferentes dependendo do diretório atual.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Todo caminho que não começa com / aponta sempre para o mesmo lugar.”',
    common: 'Confundir .. com ., ou pensar que ~ significa a raiz /.',
    summary: 'Caminho absoluto parte de /. Caminho relativo depende do diretório atual. ., .. e ~ ajudam na navegação.',
    task: 'Praticar exemplos de caminhos absolutos e relativos em uma estrutura fictícia de projeto.',
    video: '',
    hint1: 'Absoluto começa na raiz.',
    hint2: 'Relativo depende de onde você está.',
    solution: '/home/julia/documentos é absoluto. documentos é relativo e, nesse exemplo, aponta para /home/julia/documentos porque o diretório atual é /home/julia.'
  },
  {
    id: 98, module: 9, title: 'Navegação e manipulação de arquivos', time: '50–60 min',
    learn: ['pwd', 'ls', 'cd', 'mkdir', 'touch', 'cp', 'mv', 'rm', 'cat', 'less'],
    importance: 'Esses comandos formam a base para trabalhar com projetos, arquivos de configuração e servidores Linux.',
    before: 'Você sabe interpretar caminhos absolutos e relativos.',
    explanation: 'pwd mostra onde você está. ls lista itens. cd muda de diretório. mkdir cria diretórios. touch pode criar um arquivo vazio. cp copia. mv move ou renomeia. rm remove. cat mostra conteúdo curto diretamente no terminal e less permite leitura paginada. Com rm é preciso cuidado: a remoção pode não passar por uma lixeira.',
    everyday: 'É como organizar uma pasta de estudos: criar subpastas, copiar arquivos, mover documentos, renomear e excluir apenas quando tiver certeza.',
    programming: 'Crie uma pasta laboratorio, entre nela, crie notas.txt, faça uma cópia e liste os arquivos.',
    code: 'mkdir laboratorio\ncd laboratorio\ntouch notas.txt\ncp notas.txt copia-notas.txt\nls\npwd',
    lineByLine: 'mkdir cria o diretório. cd entra nele. touch cria o arquivo. cp faz uma cópia. ls confirma os itens. pwd mostra a localização atual.',
    guided: 'Em uma pasta de teste, pratique mkdir, touch, cp e mv. Use rm apenas em um arquivo descartável criado para o exercício.',
    exercise: 'Qual comando você usaria para renomear notas.txt para resumo.txt?',
    challenge: 'Explique por que executar rm sem conferir o caminho pode causar perda de dados.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“rm sempre envia o arquivo para a lixeira e pode ser desfeito facilmente.”',
    common: 'Usar rm no caminho errado, esquecer origem/destino em cp ou mv e não conferir pwd antes de operações sensíveis.',
    summary: 'Comandos básicos permitem navegar, criar, copiar, mover, ler e remover arquivos. rm exige atenção especial.',
    task: 'Montar uma pasta de laboratório com três arquivos, copiar um, renomear outro e conferir tudo com ls e pwd.',
    video: '',
    hint1: 'mv também serve para renomear.',
    hint2: 'Use origem primeiro e novo nome depois.',
    solution: 'mv notas.txt resumo.txt'
  },
  {
    id: 99, module: 9, title: 'Permissões no Linux', time: '50–60 min',
    learn: ['dono', 'grupo', 'outros', 'r', 'w', 'x', 'chmod simbólico', 'chmod numérico', '4, 2, 1', '755'],
    importance: 'Permissões controlam quem pode ler, modificar ou executar arquivos e acessar diretórios.',
    before: 'Você já sabe navegar e manipular arquivos no terminal.',
    explanation: 'As permissões são organizadas para dono, grupo e outros. r significa leitura, w escrita e x execução. Em diretórios, x também está ligado à possibilidade de atravessar/acessar entradas do diretório. chmod altera permissões. Na forma numérica, r vale 4, w vale 2 e x vale 1. Somamos os valores de cada conjunto. Em 755, o dono recebe 7 = 4+2+1, enquanto grupo e outros recebem 5 = 4+1.',
    everyday: 'Imagine um armário compartilhado: uma pessoa pode ler documentos, outra pode alterar, e outra pode apenas consultar. Permissões definem essas capacidades.',
    programming: 'Compare chmod u+x script.sh e chmod 755 script.sh e explique o efeito geral de cada comando.',
    code: 'chmod u+x script.sh\nchmod 755 script.sh',
    lineByLine: 'u+x adiciona permissão de execução ao dono. Em 755, o dono recebe rwx e grupo/outros recebem r-x.',
    guided: 'Converta rwx, r-x e r-- para valores numéricos usando 4, 2 e 1.',
    exercise: 'O que significa chmod 755 arquivo em termos de permissões do dono, grupo e outros?',
    challenge: 'Explique por que a permissão x tem significado especial quando aplicada a diretórios.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“chmod 777 é sempre a melhor escolha porque evita erros de permissão.”',
    common: 'Dar permissões excessivas para “resolver rápido” e decorar números sem entender r, w e x.',
    summary: 'Permissões se aplicam a dono, grupo e outros. chmod pode usar notação simbólica ou numérica.',
    task: 'Montar uma tabela com r=4, w=2, x=1 e interpretar 644, 755 e 700 em um exercício teórico.',
    video: '',
    hint1: '7 = 4+2+1.',
    hint2: '5 = 4+1.',
    solution: '755 significa dono rwx; grupo r-x; outros r-x.'
  },
  {
    id: 100, module: 9, title: 'Usuários, processos e ambiente', time: '50–60 min',
    learn: ['chown', 'processo', 'PID', 'ps', 'top', 'kill', 'variável de ambiente', 'PATH'],
    importance: 'Aplicações em Linux rodam como processos, pertencem a usuários e dependem de variáveis de ambiente e caminhos de executáveis.',
    before: 'Você já entende arquivos, diretórios e permissões.',
    explanation: 'chown altera o dono de um arquivo ou diretório quando você tem permissão para isso. Um processo é um programa em execução e recebe um identificador chamado PID. ps lista processos, top mostra uma visão dinâmica e kill envia um sinal a um processo. Não use kill -9 como primeira opção: sinais mais suaves normalmente devem ser tentados antes. Variáveis de ambiente armazenam valores disponíveis ao processo. PATH é uma variável que lista diretórios nos quais o sistema procura comandos executáveis. Credenciais e segredos não devem ser gravados no código ou no repositório.',
    everyday: 'Um processo é como uma tarefa em andamento com um número de identificação. O PATH funciona como uma lista de lugares onde o sistema procura as ferramentas pedidas.',
    programming: 'Use ps em um ambiente seguro para observar processos e echo $PATH para visualizar a variável PATH. Não altere processos críticos do sistema.',
    code: 'ps\necho $PATH\n\n# Exemplo conceitual de variável de ambiente:\nexport MODO_APP=desenvolvimento\necho $MODO_APP',
    lineByLine: 'ps mostra processos. echo $PATH exibe os diretórios usados na busca de comandos. export define uma variável no ambiente atual; echo $MODO_APP mostra seu valor.',
    guided: 'Explique o que é PID, o que ps mostra e por que PATH facilita executar comandos sem digitar o caminho completo.',
    exercise: 'Qual é a função geral da variável PATH?',
    challenge: 'Explique por que permissões, usuários, processos e variáveis de ambiente aparecem com frequência em deploys.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Quando um processo não responde, a primeira solução deve ser sempre sudo kill -9.”',
    common: 'Usar sudo sem necessidade, encerrar processos errados ou colocar segredos diretamente em scripts versionados.',
    summary: 'Linux organiza execução por usuários e processos. ps/top ajudam a observar processos; PATH e outras variáveis de ambiente influenciam como aplicações rodam.',
    task: 'Criar um resumo relacionando usuário, processo, PID, permissões e PATH com um futuro deploy de aplicação.',
    video: '',
    hint1: 'PATH contém uma lista de diretórios.',
    hint2: 'O shell procura executáveis nesses diretórios.',
    solution: 'PATH indica ao sistema em quais diretórios procurar comandos executáveis quando você digita um comando sem o caminho completo.'
  }
);