window.PDZ_DATA.lessons.push(
  {
    id: 66, module: 5, title: 'POST e criação de recursos', time: '50–60 min',
    learn: ['POST', 'Criação de recursos', '201 Created', 'status_code no FastAPI', 'Retorno de dados criados'],
    importance: 'Criar recursos é uma das operações centrais de uma API. Nesta aula, você liga o método POST à ideia de receber dados, validar e produzir um novo recurso.',
    before: 'Você já sabe criar uma aplicação FastAPI, rotas GET, parâmetros e modelos Pydantic.',
    explanation: 'POST é um método HTTP normalmente usado quando o cliente envia dados para que o servidor processe uma ação que pode resultar na criação de um novo recurso. Em APIs REST, é comum usar POST em uma coleção, como /alunos, para criar um novo aluno. Quando a criação é concluída, 201 Created é um status apropriado. Isso não significa que POST seja um comando de banco de dados: aqui ainda usaremos uma lista em memória.',
    everyday: 'É como preencher uma ficha de matrícula e entregá-la à secretaria. A ficha contém os dados; o sistema valida e cria um novo cadastro.',
    programming: 'Vamos receber um AlunoEntrada, gerar um id simples e guardar o aluno em uma lista em memória.',
    code: 'from fastapi import FastAPI, status\nfrom pydantic import BaseModel\n\napp = FastAPI()\nalunos = []\n\nclass AlunoEntrada(BaseModel):\n    nome: str\n    idade: int\n\n@app.post("/alunos", status_code=status.HTTP_201_CREATED)\ndef criar_aluno(aluno: AlunoEntrada):\n    novo = {"id": len(alunos) + 1, **aluno.model_dump()}\n    alunos.append(novo)\n    return novo',
    lineByLine: 'status fornece constantes legíveis para códigos HTTP. A rota POST recebe um modelo validado. model_dump() transforma os dados do modelo em dicionário Python. Criamos um id simples, adicionamos o recurso à lista e devolvemos o novo aluno com status 201.',
    guided: 'Crie uma rota POST /alunos que receba nome e idade e devolva o recurso criado com id.',
    exercise: 'Adicione o campo curso ao modelo e faça o POST incluir esse campo no recurso criado.',
    challenge: 'Explique por que devolver 201 Created é mais informativo do que devolver 200 em uma criação bem-sucedida.',
    findError: 'EXEMPLO COM ERRO CONCEITUAL — “POST sempre significa INSERT no banco de dados.” Corrija essa afirmação.',
    common: 'Confundir método HTTP com operação de banco, esquecer validação do body ou devolver status inadequado.',
    summary: 'POST pode ser usado para criar recursos; no FastAPI, status_code permite declarar 201 Created de forma explícita.',
    task: 'Criar POST /alunos com validação Pydantic e retorno 201.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'A rota deve ser @app.post("/alunos").',
    hint2: 'Use status.HTTP_201_CREATED para deixar o código legível.',
    solution: '@app.post("/alunos", status_code=status.HTTP_201_CREATED)\ndef criar_aluno(aluno: AlunoEntrada):\n    novo = {"id": len(alunos) + 1, **aluno.model_dump()}\n    alunos.append(novo)\n    return novo'
  },
  {
    id: 67, module: 5, title: 'PUT e PATCH', time: '50–60 min',
    learn: ['Atualização de recursos', 'PUT', 'PATCH', 'Atualização completa versus parcial', 'model_dump(exclude_unset=True)'],
    importance: 'APIs precisam permitir alterações. Entender a diferença conceitual entre PUT e PATCH ajuda a escolher uma interface mais clara.',
    before: 'Você já sabe criar recursos com POST.',
    explanation: 'PUT costuma representar a substituição ou atualização completa da representação de um recurso. PATCH costuma representar uma atualização parcial, enviando apenas os campos que mudam. Essas são semânticas HTTP; não são regras de banco de dados. No FastAPI, um modelo específico de atualização parcial pode ter campos opcionais, e exclude_unset=True ajuda a obter somente os campos realmente enviados pelo cliente.',
    everyday: 'PUT lembra substituir uma ficha inteira por uma nova versão; PATCH lembra corrigir apenas o telefone em uma ficha já existente.',
    programming: 'Vamos criar uma atualização parcial de aluno com PATCH.',
    code: 'from pydantic import BaseModel\n\nclass AlunoAtualizacao(BaseModel):\n    nome: str | None = None\n    idade: int | None = None\n\n@app.patch("/alunos/{aluno_id}")\ndef atualizar_aluno(aluno_id: int, dados: AlunoAtualizacao):\n    alteracoes = dados.model_dump(exclude_unset=True)\n    return {"id": aluno_id, "alteracoes": alteracoes}',
    lineByLine: 'Os campos opcionais permitem enviar apenas parte do recurso. exclude_unset=True ignora campos que não vieram na requisição. A rota PATCH recebe o id pelo path e os campos pelo body.',
    guided: 'Crie AlunoAtualizacao e envie apenas um campo em uma requisição PATCH.',
    exercise: 'Inclua curso como campo opcional de atualização.',
    challenge: 'Explique por que PATCH não significa “UPDATE do SQL” e PUT não significa “substituir uma linha do banco” obrigatoriamente.',
    findError: 'EXEMPLO COM ERRO CONCEITUAL — “PUT e PATCH são exatamente iguais e não possuem diferença semântica.” Corrija.',
    common: 'Usar o mesmo modelo de criação como se todos os campos fossem obrigatórios em PATCH e confundir semântica HTTP com SQL.',
    summary: 'PUT é normalmente usado para atualização completa; PATCH, para parcial. A diferença é de semântica HTTP.',
    task: 'Criar um modelo de atualização parcial e uma rota PATCH.',
    video: '',
    hint1: 'Campos opcionais podem usar tipo | None com valor padrão None.',
    hint2: 'exclude_unset=True ajuda a pegar somente o que foi enviado.',
    solution: 'class AlunoAtualizacao(BaseModel):\n    nome: str | None = None\n    idade: int | None = None\n    curso: str | None = None'
  },
  {
    id: 68, module: 5, title: 'DELETE e remoção de recursos', time: '50–60 min',
    learn: ['DELETE', 'Remoção de recurso', '204 No Content', 'Resposta sem body', 'Busca por id'],
    importance: 'Remover recursos exige cuidado com a existência do item e com o tipo de resposta retornada ao cliente.',
    before: 'Você já sabe criar e atualizar recursos.',
    explanation: 'DELETE é o método HTTP normalmente usado para solicitar a remoção de um recurso. Uma resposta 204 No Content indica sucesso sem corpo de resposta. Se o recurso não existe, 404 pode ser mais adequado. Nesta fase, os dados continuam em memória.',
    everyday: 'É como pedir a exclusão de um cadastro. O sistema precisa localizar o registro antes de removê-lo.',
    programming: 'Vamos procurar um aluno pelo id, removê-lo da lista e responder com 204.',
    code: 'from fastapi import HTTPException, Response, status\n\n@app.delete("/alunos/{aluno_id}", status_code=status.HTTP_204_NO_CONTENT)\ndef excluir_aluno(aluno_id: int):\n    for aluno in alunos:\n        if aluno["id"] == aluno_id:\n            alunos.remove(aluno)\n            return Response(status_code=status.HTTP_204_NO_CONTENT)\n    raise HTTPException(status_code=404, detail="Aluno não encontrado")',
    lineByLine: 'Percorremos a lista procurando o id. Se encontrarmos, removemos o aluno e retornamos uma resposta sem body com status 204. Se não encontrarmos, levantamos HTTPException com 404.',
    guided: 'Implemente DELETE /alunos/{aluno_id} em sua lista em memória.',
    exercise: 'Teste mentalmente o que deve acontecer ao excluir um id existente e depois tentar excluir o mesmo id novamente.',
    challenge: 'Explique por que uma resposta 204 não deve carregar um corpo de conteúdo.',
    findError: 'EXEMPLO COM ERRO — retornar {"mensagem": "apagado"} junto com status 204. Explique a inconsistência.',
    common: 'Retornar body com 204, remover sem verificar existência ou usar 200 por hábito sem refletir sobre a resposta desejada.',
    summary: 'DELETE solicita remoção; 204 é apropriado quando o servidor quer confirmar sucesso sem devolver conteúdo.',
    task: 'Criar DELETE /alunos/{id} com 204 e 404.',
    video: '',
    hint1: 'Primeiro procure o aluno pelo id.',
    hint2: 'Se não encontrar, use HTTPException com 404.',
    solution: '@app.delete("/alunos/{aluno_id}", status_code=status.HTTP_204_NO_CONTENT)\ndef excluir_aluno(aluno_id: int):\n    for aluno in alunos:\n        if aluno["id"] == aluno_id:\n            alunos.remove(aluno)\n            return Response(status_code=status.HTTP_204_NO_CONTENT)\n    raise HTTPException(status_code=404, detail="Aluno não encontrado")'
  },
  {
    id: 69, module: 5, title: 'Erros e códigos de status no FastAPI', time: '50–60 min',
    learn: ['HTTPException', '400 Bad Request', '404 Not Found', '422 Unprocessable Content', '500 Internal Server Error', 'Mensagens de erro'],
    importance: 'Uma API precisa comunicar falhas de forma previsível. Status corretos ajudam cliente e servidor a entender o que aconteceu.',
    before: 'Você já viu códigos HTTP no Módulo 4 e usou 201, 204 e 404 nas rotas anteriores.',
    explanation: 'FastAPI permite interromper uma operação de rota com HTTPException e devolver um status e uma mensagem detail. 404 indica que o recurso solicitado não foi encontrado. 400 pode representar uma requisição inválida por regra da aplicação. Erros de validação de dados podem gerar 422 automaticamente. 500 representa falha interna inesperada do servidor e não deve ser usado como resposta planejada para qualquer erro.',
    everyday: 'Se você procura uma matrícula que não existe, o problema é diferente de enviar dados em formato inválido ou de o servidor apresentar uma falha interna.',
    programming: 'Crie uma função de busca que devolve o aluno ou lança 404.',
    code: 'from fastapi import HTTPException\n\ndef obter_aluno(aluno_id: int):\n    for aluno in alunos:\n        if aluno["id"] == aluno_id:\n            return aluno\n    raise HTTPException(\n        status_code=404,\n        detail="Aluno não encontrado"\n    )',
    lineByLine: 'A função percorre os dados. Quando encontra o id, retorna o recurso. Se terminar sem encontrar, HTTPException encerra o fluxo e o FastAPI monta a resposta de erro.',
    guided: 'Reaproveite obter_aluno em GET, PATCH e DELETE.',
    exercise: 'Crie uma regra que rejeite idade negativa com status 400 e uma mensagem clara.',
    challenge: 'Explique a diferença entre 404, 422 e 500 usando exemplos de uma API escolar.',
    findError: 'EXEMPLO COM ERRO CONCEITUAL — “Todo erro da API deve retornar 500.” Corrija.',
    common: 'Usar 500 para erros esperados, devolver mensagens vagas ou repetir lógica de busca em todas as rotas.',
    summary: 'HTTPException ajuda a expressar erros esperados com status e detail apropriados.',
    task: 'Criar função de busca reutilizável e tratar 404 de forma centralizada.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: '404 é apropriado quando um recurso não existe.',
    hint2: 'HTTPException recebe status_code e detail.',
    solution: 'if idade < 0:\n    raise HTTPException(status_code=400, detail="Idade não pode ser negativa")'
  },
  {
    id: 70, module: 5, title: 'Projeto: CRUD de alunos em memória', time: '50–60 min',
    learn: ['CRUD completo', 'GET coleção', 'GET por id', 'POST', 'PATCH', 'DELETE', 'Validação', 'Erros e status'],
    importance: 'Este projeto integra tudo o que você estudou no módulo em uma única API funcional antes da entrada em banco de dados.',
    before: 'Você já conhece rotas, parâmetros, Pydantic, POST, PATCH, DELETE e HTTPException.',
    explanation: 'CRUD significa Create, Read, Update e Delete: criar, ler, atualizar e excluir. O projeto terá uma lista em memória como armazenamento temporário. Ao reiniciar o servidor, os dados são perdidos; isso é esperado aqui. O objetivo é dominar a estrutura da API antes de usar PostgreSQL.',
    everyday: 'Pense em um pequeno sistema escolar: cadastrar aluno, listar todos, consultar um aluno, alterar seus dados e excluir um cadastro.',
    programming: 'Implemente os cinco endpoints definidos no currículo do módulo.',
    code: 'GET    /alunos\nGET    /alunos/{id}\nPOST   /alunos\nPATCH  /alunos/{id}\nDELETE /alunos/{id}\n\n# Armazenamento temporário\nalunos = []',
    lineByLine: 'GET /alunos lista a coleção. GET /alunos/{id} busca um recurso. POST cria. PATCH altera parcialmente. DELETE remove. A lista é apenas memória do processo, não banco de dados.',
    guided: 'Monte o projeto em etapas: modelos Pydantic, lista em memória, função obter_aluno, GETs, POST, PATCH e DELETE.',
    exercise: 'Teste cada rota pela documentação interativa do FastAPI e anote o status recebido em cada cenário.',
    challenge: 'Adicione uma regra de negócio simples, como impedir idade negativa, sem usar banco de dados ou autenticação.',
    findError: 'EXEMPLO COM ERRO CONCEITUAL — “Como os dados estão em uma lista, a API já possui persistência permanente.” Corrija.',
    common: 'Misturar conceitos de banco antes da hora, repetir busca por id, esquecer status e alterar diretamente dados sem validação.',
    summary: 'Você concluiu uma API CRUD de alunos em memória com FastAPI, Pydantic, rotas, validação, erros e códigos de status.',
    task: 'Finalizar o CRUD de alunos e fazer uma revisão do Módulo 5.',
    video: 'https://www.youtube.com/watch?v=R26iojTwUv8',
    hint1: 'Comece pelos modelos e pela lista em memória.',
    hint2: 'Crie uma função obter_aluno para evitar repetir a busca por id.',
    solution: 'Estrutura mínima concluída quando existem GET /alunos, GET /alunos/{id}, POST /alunos, PATCH /alunos/{id} e DELETE /alunos/{id}, todos usando validação e erros/status apropriados.'
  }
);