window.PDZ_DATA.lessons.push(
  {
    id: 11, module: 1, title: 'Condições com if', time: '50–60 min',
    learn: ['Condição e expressão booleana', 'Estrutura if', 'Blocos de código', 'Indentação em Python'],
    importance: 'Condições permitem que o programa tome decisões e execute um bloco somente quando uma regra for verdadeira.',
    before: 'Você já sabe criar comparações e expressões booleanas com operadores lógicos.',
    explanation: 'A instrução if verifica uma condição. Se a expressão for True, o bloco indentado abaixo do if é executado. A indentação não é apenas visual em Python: ela define quais instruções pertencem ao bloco.',
    everyday: 'Pense em uma regra: “se estiver chovendo, leve guarda-chuva”. A ação acontece somente quando a condição é verdadeira.',
    programming: 'Podemos verificar se uma pessoa tem 18 anos ou mais antes de mostrar uma mensagem.',
    code: 'idade = int(input("Digite sua idade: "))\n\nif idade >= 18:\n    print("Maior de idade")',
    lineByLine: 'A primeira linha recebe e converte a idade. O if testa idade >= 18. Os dois-pontos iniciam o bloco e a linha indentada é executada somente quando a condição é verdadeira.',
    guided: 'Crie uma variável nota com valor numérico. Use if para mostrar “Aprovado” quando nota for maior ou igual a 7.',
    exercise: 'Escreva um programa que receba um número e mostre “Número positivo” somente quando ele for maior que zero.',
    challenge: 'Peça uma idade e mostre uma mensagem somente se a pessoa tiver idade entre 18 e 60 anos, usando and.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nif idade >= 18:\nprint("Maior de idade")',
    common: 'Esquecer os dois-pontos, errar a indentação e confundir a condição com a ação que deve ocorrer.',
    summary: 'if executa um bloco quando uma condição é verdadeira. Em Python, a indentação define o bloco.',
    task: 'Criar três exemplos de if usando comparações diferentes.', video: 'https://www.youtube.com/watch?v=K10u3XIf1-Q',
    hint1: 'Primeiro escreva a comparação que produz True ou False.', hint2: 'Depois coloque a ação em uma linha indentada abaixo do if.', solution: 'numero = int(input("Digite um número: "))\nif numero > 0:\n    print("Número positivo")'
  },
  {
    id: 12, module: 1, title: 'elif e else', time: '50–60 min',
    learn: ['else', 'elif', 'Decisões alternativas', 'Fluxo condicional com várias possibilidades'],
    importance: 'Nem todo problema tem apenas uma situação. elif e else permitem escolher entre diferentes caminhos.',
    before: 'Você já sabe usar if e entende que o bloco executa somente quando a condição é verdadeira.',
    explanation: 'if testa a primeira condição. elif permite testar outra condição quando as anteriores foram falsas. else representa o caminho restante, sem precisar de uma nova condição. Em uma cadeia if/elif/else, apenas o primeiro bloco cuja condição for satisfeita é executado.',
    everyday: 'Uma escola pode classificar uma nota como aprovado, recuperação ou reprovado. Cada faixa leva a um caminho diferente.',
    programming: 'Podemos classificar uma nota usando if, elif e else.',
    code: 'nota = float(input("Digite a nota: "))\n\nif nota >= 7:\n    print("Aprovado")\nelif nota >= 5:\n    print("Recuperação")\nelse:\n    print("Reprovado")',
    lineByLine: 'Primeiro é testado nota >= 7. Se for falso, o elif testa nota >= 5. Se também for falso, o else executa o último bloco.',
    guided: 'Crie uma classificação simples para temperatura: quente, amena ou fria, escolhendo faixas claras.',
    exercise: 'Receba uma idade e mostre “criança” para menos de 12, “adolescente” para menos de 18 e “adulto” nos demais casos.',
    challenge: 'Crie uma classificação de desempenho com quatro faixas de nota sem repetir condições desnecessárias.',
    findError: 'Um programa usa três if independentes quando deveria escolher somente uma classificação. Explique por que uma cadeia if/elif/else pode ser mais adequada.',
    common: 'Colocar condições em ordem errada e criar faixas que se sobrepõem de forma confusa.',
    summary: 'if inicia a decisão, elif testa alternativas e else trata o restante. A ordem das condições importa.',
    task: 'Criar um classificador de notas com pelo menos três resultados possíveis.', video: 'https://www.youtube.com/watch?v=K10u3XIf1-Q',
    hint1: 'Comece testando a faixa mais específica ou mais alta.', hint2: 'Depois use elif para a faixa seguinte e else para o restante.', solution: 'idade = int(input("Idade: "))\nif idade < 12:\n    print("Criança")\nelif idade < 18:\n    print("Adolescente")\nelse:\n    print("Adulto")'
  },
  {
    id: 13, module: 1, title: 'Repetições com for', time: '50–60 min',
    learn: ['Repetição', 'for', 'range()', 'Contador e iteração básica'],
    importance: 'Laços evitam repetir manualmente a mesma instrução várias vezes e permitem percorrer sequências de valores.',
    before: 'Você já sabe criar instruções, variáveis e condições.',
    explanation: 'for repete um bloco para cada valor de uma sequência. range() pode gerar uma sequência de números. Em range(inicio, limite), o limite final não é incluído.',
    everyday: 'Em vez de dizer cinco vezes “escreva o nome”, você pode dizer “repita esta ação cinco vezes”.',
    programming: 'Um for com range(1, 6) percorre os números 1, 2, 3, 4 e 5.',
    code: 'for numero in range(1, 6):\n    print(numero)',
    lineByLine: 'range(1, 6) produz valores de 1 até 5. A cada repetição, numero recebe o próximo valor e print(numero) o mostra.',
    guided: 'Use for e range() para mostrar os números de 1 a 10.',
    exercise: 'Use for para mostrar os números de 2 a 8, um por linha.',
    challenge: 'Peça um número e mostre a tabuada dele de 1 a 10 usando for.',
    findError: 'Uma pessoa espera que range(1, 5) mostre também o número 5. Explique o que realmente acontece.',
    common: 'Esquecer que o limite final de range() é exclusivo e errar a indentação do bloco.',
    summary: 'for percorre valores; range() ajuda a gerar sequências numéricas; o limite final não é incluído.',
    task: 'Criar uma pequena tabuada com for.', video: null,
    hint1: 'Para incluir o número 8, o limite final precisa ser maior que 8.', hint2: 'Use range(2, 9).', solution: 'for numero in range(2, 9):\n    print(numero)'
  },
  {
    id: 14, module: 1, title: 'Repetições com while', time: '50–60 min',
    learn: ['while', 'Condição de repetição', 'Contador', 'Atualização de variável', 'Loop infinito'],
    importance: 'while é útil quando a repetição depende de uma condição e não sabemos necessariamente de antemão quantas vezes ela ocorrerá.',
    before: 'Você já conhece condições e repetição com for.',
    explanation: 'while repete um bloco enquanto a condição permanecer True. É necessário garantir que algo dentro do bloco possa alterar a condição; caso contrário, o programa pode entrar em um loop infinito.',
    everyday: '“Enquanto a garrafa não estiver cheia, continue colocando água.” A repetição termina quando a condição deixa de ser verdadeira.',
    programming: 'Um contador pode começar em 1 e aumentar a cada repetição até ultrapassar 5.',
    code: 'contador = 1\n\nwhile contador <= 5:\n    print(contador)\n    contador = contador + 1',
    lineByLine: 'contador começa em 1. while testa contador <= 5. O valor é mostrado e depois aumentado. Quando chega a 6, a condição fica False e o laço termina.',
    guided: 'Crie um contador que mostre de 1 a 3 e confirme onde ocorre a atualização da variável.',
    exercise: 'Use while para mostrar os números de 5 até 1 em ordem decrescente.',
    challenge: 'Crie um programa que continue pedindo uma palavra até o usuário digitar “sair”.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\ncontador = 1\nwhile contador <= 5:\n    print(contador)',
    common: 'Esquecer de atualizar a variável de controle e provocar loop infinito.',
    summary: 'while repete enquanto uma condição for verdadeira. A condição precisa poder mudar para que o laço termine.',
    task: 'Criar dois exemplos de while: um crescente e um decrescente.', video: null,
    hint1: 'Para contar para baixo, comece em 5.', hint2: 'Subtraia 1 do contador a cada repetição.', solution: 'contador = 5\nwhile contador >= 1:\n    print(contador)\n    contador = contador - 1'
  },
  {
    id: 15, module: 1, title: 'Desafio de lógica — Calculadora com menu', time: '50–60 min',
    learn: ['Combinar variáveis, input(), operadores e condições', 'Usar while em um menu', 'Organizar um programa em etapas', 'Revisar Aulas 11–15'],
    importance: 'Este desafio reúne o que você já estudou e mostra como várias estruturas simples formam um programa mais completo.',
    before: 'Você já estudou variáveis, entrada, operadores, if/elif/else, for e while.',
    explanation: 'A calculadora usa um menu dentro de um while. O usuário escolhe uma operação. if, elif e else decidem qual cálculo será executado. A opção 0 encerra o laço. O projeto deve usar apenas conhecimentos já estudados.',
    everyday: 'É semelhante a um menu de atendimento: você escolhe uma opção, o sistema executa a ação e volta ao menu até você escolher sair.',
    programming: 'O menu pode ter opções para somar, subtrair, multiplicar, dividir e sair.',
    code: 'opcao = ""\n\nwhile opcao != "0":\n    print("1 - Somar")\n    print("2 - Subtrair")\n    print("3 - Multiplicar")\n    print("4 - Dividir")\n    print("0 - Sair")\n    opcao = input("Escolha: ")',
    lineByLine: 'opcao começa diferente de 0. O while mantém o menu ativo. Cada print mostra uma opção e input() recebe a escolha. Depois, condições podem decidir qual operação executar.',
    guided: 'Primeiro construa apenas o menu e confirme que a opção 0 encerra a repetição. Depois acrescente uma operação por vez.',
    exercise: 'Complete o menu com a opção de soma usando dois números e if.',
    challenge: 'Finalizar a calculadora com soma, subtração, multiplicação, divisão e saída. Evite dividir por zero usando uma condição.',
    findError: 'Um menu usa while True sem nenhuma forma de sair e ainda não estudou break. Reorganize usando uma condição de while já conhecida.',
    common: 'Tentar escrever tudo de uma vez, esquecer de atualizar a opção e não tratar divisão por zero.',
    summary: 'O projeto combina entrada, decisões e repetição. A estratégia mais segura é construir e testar uma parte de cada vez. Esta aula também revisa decisões, indentação, for, range() e while.',
    task: 'Concluir a calculadora com menu e refazer pelo menos três exercícios das Aulas 11–15 sem olhar a solução.', video: null,
    hint1: 'Faça primeiro o menu funcionar e sair com 0.', hint2: 'Depois use if/elif para uma operação por vez.', solution: 'opcao = ""\nwhile opcao != "0":\n    print("1 - Somar | 2 - Subtrair | 3 - Multiplicar | 4 - Dividir | 0 - Sair")\n    opcao = input("Escolha: ")\n    if opcao != "0":\n        a = float(input("Primeiro número: "))\n        b = float(input("Segundo número: "))\n        if opcao == "1":\n            print(a + b)\n        elif opcao == "2":\n            print(a - b)\n        elif opcao == "3":\n            print(a * b)\n        elif opcao == "4":\n            if b != 0:\n                print(a / b)\n            else:\n                print("Não é possível dividir por zero.")\n        else:\n            print("Opção inválida")'
  }
);
