window.PDZ_DATA.lessons.push(
  {
    id: 101, module: 10, title: 'Localhost versus Internet', time: '50–60 min',
    learn: ['localhost', 'loopback', 'rede local', 'Internet', 'bind', '127.0.0.1', '0.0.0.0'],
    importance: 'Uma aplicação pode funcionar perfeitamente no seu computador e ainda assim não estar disponível para outras pessoas. Entender onde ela está acessível é essencial antes de publicar um projeto.',
    before: 'Você já estudou redes, IP, localhost, portas e aplicações full stack.',
    explanation: 'Localhost representa a própria máquina. Quando um servidor escuta apenas em 127.0.0.1, ele normalmente aceita conexões somente do próprio computador. Ao escutar em 0.0.0.0, o programa aceita conexões destinadas às interfaces de rede disponíveis, mas isso não transforma 0.0.0.0 em um endereço público nem garante acesso pela Internet. Firewall, roteamento, NAT e hospedagem ainda influenciam o acesso.',
    everyday: 'É como cozinhar em casa: a comida existe, mas outras pessoas não conseguem recebê-la até que exista um caminho de entrega e um endereço acessível.',
    programming: 'Compare um servidor iniciado apenas em localhost com um servidor configurado para aceitar conexões pela rede local.',
    code: '127.0.0.1  → somente a própria máquina\n0.0.0.0    → escuta nas interfaces disponíveis\n\nImportante: 0.0.0.0 não é um IP público para compartilhar.',
    lineByLine: '127.0.0.1 é o endereço de loopback IPv4. 0.0.0.0, usado como endereço de escuta, significa aceitar conexões destinadas às interfaces disponíveis. A acessibilidade real depende da rede e das regras do sistema.',
    guided: 'Explique três níveis: aplicativo acessível só no computador, acessível na rede local e acessível pela Internet.',
    exercise: 'Por que uma API rodando em 127.0.0.1 não costuma ser acessível por outro computador da mesma rede?',
    challenge: 'Explique por que trocar 127.0.0.1 por 0.0.0.0 não basta, por si só, para publicar uma aplicação na Internet.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Se o servidor está em 0.0.0.0, então esse é o endereço público do site.”',
    common: 'Confundir endereço de escuta com endereço público e imaginar que localhost significa Internet.',
    summary: 'Localhost é a própria máquina. Escutar em 0.0.0.0 amplia onde o processo aceita conexões, mas não publica automaticamente o sistema na Internet.',
    task: 'Desenhar um esquema mostrando computador local → rede local → Internet e indicar onde a aplicação está acessível em cada cenário.',
    video: '',
    hint1: 'Pense em quem consegue alcançar o processo pela rede.',
    hint2: 'Diferencie “onde o servidor escuta” de “qual endereço público existe”.',
    solution: 'Porque 127.0.0.1 é loopback e aponta para a própria máquina. Outro computador não usa o seu loopback para chegar ao seu servidor.'
  },
  {
    id: 102, module: 10, title: 'Servidores e VPS', time: '50–60 min',
    learn: ['servidor como papel', 'software servidor', 'infraestrutura', 'VPS', 'CPU', 'memória', 'armazenamento', 'rede'],
    importance: 'Aplicações publicadas precisam de um ambiente que permaneça disponível para receber requisições. Servidores cumprem esse papel.',
    before: 'Você entende cliente, servidor e a diferença entre localhost e acesso externo.',
    explanation: 'Servidor não é apenas um tipo especial de computador. A palavra pode indicar o papel de atender clientes, o software que oferece um serviço ou a infraestrutura onde esse software roda. Uma VPS é um servidor virtual privado: uma máquina virtual com recursos próprios dentro de uma infraestrutura maior. Ela é uma opção de hospedagem, não a única.',
    everyday: 'Um restaurante é um lugar físico, mas “servir” também é uma função. Em tecnologia, servidor pode indicar a função, o programa e a infraestrutura que sustenta o serviço.',
    programming: 'Imagine um processo FastAPI executando continuamente em uma VPS e recebendo requisições HTTP.',
    code: 'Cliente (navegador)\n        ↓\nInternet\n        ↓\nVPS\n  └─ processo FastAPI\n        ↓\nPostgreSQL',
    lineByLine: 'O navegador é cliente. A VPS fornece infraestrutura virtual. Dentro dela pode rodar o processo da aplicação. O banco pode estar na mesma infraestrutura ou em outro serviço.',
    guided: 'Diferencie servidor como papel, software e infraestrutura com um exemplo para cada caso.',
    exercise: 'O que é uma VPS e por que ela pode ser usada para hospedar uma API?',
    challenge: 'Explique por que dizer que “servidor é sempre um computador físico dedicado” é incorreto.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“VPS é obrigatoriamente um computador físico inteiro reservado para uma única pessoa.”',
    common: 'Confundir servidor com uma única forma de hardware e pensar que toda hospedagem exige VPS.',
    summary: 'Servidor é um papel/serviço e também pode se referir à infraestrutura. VPS é uma forma virtualizada de hospedagem.',
    task: 'Criar um desenho simples de cliente → servidor → banco de dados e identificar onde uma VPS pode aparecer.',
    video: '',
    hint1: 'A sigla VPS significa Virtual Private Server.',
    hint2: 'Pense em uma máquina virtual que pode rodar serviços continuamente.',
    solution: 'VPS é um servidor virtual privado com recursos alocados em infraestrutura virtualizada. Ela pode executar uma API continuamente e receber conexões pela rede.'
  },
  {
    id: 103, module: 10, title: 'Cloud: IaaS, PaaS e SaaS', time: '50–60 min',
    learn: ['cloud', 'IaaS', 'PaaS', 'SaaS', 'infraestrutura sob demanda', 'responsabilidade compartilhada'],
    importance: 'Grande parte das aplicações modernas é hospedada ou depende de serviços em nuvem. Entender os modelos básicos ajuda a escolher quanto da infraestrutura você quer administrar.',
    before: 'Você já sabe o que são servidores e VPS.',
    explanation: 'Computação em nuvem usa infraestrutura remota fornecida como serviço. IaaS oferece recursos de infraestrutura, como máquinas virtuais e rede. PaaS oferece uma plataforma mais pronta para executar a aplicação, abstraindo parte da infraestrutura. SaaS entrega um software pronto para uso. Em todos os casos existe infraestrutura física por trás; “nuvem” não significa ausência de computadores reais.',
    everyday: 'IaaS é parecido com alugar um espaço vazio e montar mais coisas; PaaS lembra alugar um espaço já preparado para trabalhar; SaaS é usar o serviço pronto.',
    programming: 'Classifique uma máquina virtual, uma plataforma que recebe seu código e um editor online pronto como exemplos conceituais de IaaS, PaaS e SaaS.',
    code: 'IaaS → mais controle da infraestrutura\nPaaS → foco maior na aplicação\nSaaS → software pronto para o usuário',
    lineByLine: 'IaaS deixa mais responsabilidade de configuração com você. PaaS automatiza mais partes da infraestrutura. SaaS entrega a aplicação pronta para uso.',
    guided: 'Monte uma tabela com IaaS, PaaS e SaaS e escreva o que o provedor entrega e o que o usuário ainda administra.',
    exercise: 'Qual modelo normalmente exige que você cuide mais do sistema operacional: IaaS, PaaS ou SaaS?',
    challenge: 'Explique por que “cloud” não significa que os dados ficam sem servidores físicos.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Na nuvem não existem servidores físicos; tudo é apenas virtual.”',
    common: 'Confundir cloud com virtualização apenas e tratar IaaS, PaaS e SaaS como sinônimos.',
    summary: 'IaaS, PaaS e SaaS representam níveis diferentes de serviço e de responsabilidade sobre a infraestrutura e o software.',
    task: 'Criar um quadro comparativo IaaS × PaaS × SaaS com um exemplo genérico de uso para cada modelo.',
    video: '',
    hint1: 'IaaS oferece a camada mais próxima da infraestrutura.',
    hint2: 'SaaS entrega o software pronto.',
    solution: 'IaaS normalmente exige mais administração do sistema operacional e da infraestrutura do que PaaS ou SaaS.'
  },
  {
    id: 104, module: 10, title: 'Ambientes: desenvolvimento, testes e produção', time: '50–60 min',
    learn: ['desenvolvimento', 'testes', 'produção', 'configuração por ambiente', 'dados separados'],
    importance: 'Separar ambientes reduz o risco de testar mudanças diretamente onde usuários reais e dados reais estão sendo atendidos.',
    before: 'Você conhece servidores, cloud e aplicações full stack.',
    explanation: 'Desenvolvimento é o ambiente usado para criar e experimentar. Testes é usado para validar comportamentos antes da liberação. Produção é o ambiente real usado por usuários. Cada ambiente pode ter configurações, URLs, bancos e credenciais diferentes. Testes destrutivos ou experimentais não devem ser feitos diretamente em produção.',
    everyday: 'É como ensaiar antes de uma apresentação: você experimenta em um espaço seguro, verifica o resultado e só depois apresenta ao público.',
    programming: 'Compare três configurações da mesma aplicação: desenvolvimento local, ambiente de testes e produção.',
    code: 'DEV  → banco_dev, logs detalhados\nTEST → banco_teste, dados de teste\nPROD → banco_producao, configuração protegida',
    lineByLine: 'O código pode ser semelhante, mas as configurações mudam conforme o ambiente. Os dados e segredos também devem permanecer separados.',
    guided: 'Liste o que não deveria ser compartilhado automaticamente entre desenvolvimento e produção.',
    exercise: 'Por que é perigoso usar o banco de produção para experimentar comandos de desenvolvimento?',
    challenge: 'Explique como variáveis de ambiente ajudam a usar o mesmo código com configurações diferentes em cada ambiente.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\n“Para facilitar, desenvolvimento e produção devem usar exatamente o mesmo banco de dados.”',
    common: 'Usar credenciais de produção no desenvolvimento e testar alterações diretamente em dados reais.',
    summary: 'Desenvolvimento, testes e produção têm finalidades diferentes e devem ter configurações e dados adequadamente separados.',
    task: 'Desenhar uma tabela DEV / TEST / PROD com objetivo, tipo de dados e cuidados principais.',
    video: '',
    hint1: 'Produção atende usuários reais.',
    hint2: 'Experimentos e testes devem ocorrer fora do ambiente produtivo.',
    solution: 'Porque um erro pode alterar ou excluir dados reais e afetar usuários. Use bancos e dados específicos de desenvolvimento/teste.'
  },
  {
    id: 105, module: 10, title: 'Deploy de uma aplicação', time: '50–60 min',
    learn: ['deploy', 'dependências', 'comando de inicialização', 'logs', 'variáveis de ambiente', 'segredos', '.env', 'banco de produção'],
    importance: 'Deploy é o processo que transforma uma versão do seu projeto em uma aplicação disponível em um ambiente de execução.',
    before: 'Você entende localhost, servidores, cloud e ambientes.',
    explanation: 'Fazer deploy envolve levar o código a um ambiente, instalar dependências, definir como a aplicação inicia, configurar variáveis de ambiente e serviços externos, observar logs e conectar o banco de produção. Segredos não devem ser escritos no código nem enviados ao Git. Um arquivo .env pode ser útil localmente, mas quando contém segredos deve estar fora do versionamento. Em produção, a plataforma costuma fornecer um mecanismo próprio de configuração de variáveis e segredos.',
    everyday: 'Publicar uma aplicação é como abrir uma loja: não basta levar os produtos; é preciso preparar energia, acesso, estoque, regras de funcionamento e acompanhamento de problemas.',
    programming: 'Monte um checklist de deploy para uma API FastAPI com PostgreSQL.',
    code: 'Checklist:\n1. código versionado\n2. dependências declaradas\n3. comando de inicialização\n4. variáveis de ambiente\n5. banco de produção\n6. logs\n7. segredos fora do Git',
    lineByLine: 'Cada item resolve uma necessidade do ambiente: reproduzir o código, instalar bibliotecas, iniciar o serviço, configurar valores externos, persistir dados, diagnosticar falhas e proteger credenciais.',
    guided: 'Crie um arquivo `.env.example` apenas com nomes de variáveis e valores fictícios, sem qualquer segredo real.',
    exercise: 'Por que um arquivo `.env` com senhas não deve ser enviado ao repositório?',
    challenge: 'Explique a diferença entre configuração pública do aplicativo e segredo de produção.',
    findError: 'EXEMPLO COM ERRO — NÃO COPIE COMO SOLUÇÃO\nDATABASE_PASSWORD="minha-senha-real"  # commitado no Git',
    common: 'Colocar credenciais no código, esquecer dependências, não observar logs e usar o banco local como se fosse automaticamente adequado para produção.',
    summary: 'Deploy combina código, dependências, inicialização, configuração, banco, logs e proteção de segredos.',
    task: 'Criar um checklist de deploy e um `.env.example` fictício contendo apenas nomes de variáveis como DATABASE_URL e APP_ENV.',
    video: '',
    hint1: 'Segredos não pertencem ao código-fonte.',
    hint2: 'Git mantém histórico, então um segredo commitado pode continuar exposto mesmo após ser apagado de uma versão posterior.',
    solution: 'Porque o Git registra histórico e o repositório pode ser compartilhado ou acessado por outras pessoas e serviços. Segredos devem ser configurados fora do código e do versionamento.'
  }
);