(() => {
'use strict';
const topics=[
['Algoritmos','Organize um problema em entrada, processamento e saída.','Você vai criar um programa que recebe duas notas, calcula a média e depois mostra o resultado. Qual etapa deve acontecer primeiro?',['Entrada','Saída','Framework'],0],
['Primeiro programa','Use print() para mostrar informações.','Seu programa precisa exibir a mensagem “Cadastro concluído” no terminal. Qual código faz isso?',['input("Cadastro concluído")','print("Cadastro concluído")','range("Cadastro concluído")'],1],
['VS Code','Crie arquivos .py e execute pelo terminal integrado.','Você vai salvar no VS Code um arquivo contendo código Python. Qual nome de arquivo está correto?',['aula.py','aula.html','aula.sql'],0],
['Strings','Textos ficam entre aspas.','Você precisa guardar o nome de uma aluna como texto. Qual valor é uma string válida em Python?',['42','"Olá"','True'],1],
['Variáveis','Variáveis guardam valores que o programa usa.','Você quer guardar a idade 20 na variável idade. Qual linha faz a atribuição corretamente?',['idade = 20','idade == 20','print(idade)'],0],
['Tipos','int, float, str e bool representam dados diferentes.','Um sistema precisa guardar o preço 19.90 para fazer cálculos. Qual tipo representa melhor esse valor?',['float','str','bool'],0],
['Entrada de dados','input() recebe dados digitados pelo usuário.','O programa deve perguntar o nome ao usuário e guardar o que ele digitar. Qual função recebe essa entrada?',['input()','print()','len()'],0],
['Conversão','int() e float() convertem textos numéricos.','input() devolveu o texto "10", mas você precisa somá-lo a outro número inteiro. Qual conversão deve usar?',['str("10")','int("10")','bool("10")'],1],
['Aritmética','Python calcula com +, -, *, /, //, % e **.','Você quer descobrir se um número é par verificando o resto da divisão por 2. Qual operador deve usar?',['%','//','**'],0],
['Comparações','==, !=, >, <, >= e <= produzem valores booleanos.','Para verificar se senha_digitada tem exatamente o mesmo valor de senha_correta, qual operador deve ser usado?',['=','==','!='],1],
['Lógica booleana','and, or e not combinam condições.','Uma inscrição só é aceita se idade >= 18 E documento_ok for verdadeiro. Qual operador combina essas duas condições?',['or','and','not'],1],
['if','if executa um bloco quando a condição é verdadeira.','O sistema deve mostrar “Aprovado” somente quando media >= 7. Qual estrutura inicia essa decisão?',['if','for','def'],0],
['elif e else','elif testa outra condição e else cobre o restante.','Depois de testar if e elif, você precisa tratar qualquer caso que sobrou. Qual palavra usa?',['else','import','while'],0],
['for','for percorre sequências e intervalos.','Você precisa executar uma ação exatamente 5 vezes usando range(5). Qual estrutura é adequada?',['for','if','class'],0],
['while','while repete enquanto a condição for verdadeira.','Um menu deve continuar aparecendo enquanto opcao != 0. Qual laço é adequado?',['while','import','return'],0],
['Listas','Listas armazenam vários valores e podem mudar.','Você precisa guardar três notas e depois alterar uma delas. Qual estrutura é uma lista Python?',['[1,2,3]','(1,2,3)','{"a":1}'],0],
['Tuplas e conjuntos','Tuplas são imutáveis; sets evitam duplicatas.','Você recebeu vários códigos repetidos e quer manter apenas valores únicos. Qual coleção ajuda diretamente?',['list','set','str'],1],
['Dicionários','Dicionários relacionam chaves e valores.','Você precisa relacionar a chave nome ao valor Ana. Qual estrutura representa isso?',['{"nome":"Ana"}','["Ana"]','("Ana",)'],0],
['Funções','def cria funções reutilizáveis; return devolve resultados.','Você quer criar uma função chamada calcular_media para reutilizar esse cálculo. Qual palavra inicia a definição?',['class','def','import'],1],
['Projeto Python','Combine entrada, condições, laços, coleções e funções.','Qual é a melhor atitude diante de um projeto grande?',['Dividir em partes','Escrever tudo de uma vez','Ignorar testes'],0],
['Arquivos','with open() permite ler e escrever arquivos.','Qual estrutura ajuda a fechar arquivo corretamente?',['with open','while','match'],0],
['JSON','JSON é um formato de troca de dados.','Qual módulo Python trabalha com JSON?',['json','math','random'],0],
['Exceções','try/except permite tratar falhas esperadas.','Qual captura uma exceção?',['except','return','yield'],0],
['POO','Classes modelam objetos com dados e comportamentos.','Qual palavra cria classe em Python?',['class','object','new'],0],
['Objetos','Uma instância é um objeto criado a partir de uma classe.','Objeto criado de uma classe é:',['instância','loop','módulo'],0],
['Métodos','Métodos são funções ligadas a objetos.','Em Python, qual referência normalmente aponta para a instância?',['self','this','me'],0],
['Construtores','__init__ inicializa novos objetos.','Qual método inicializa uma instância?',['__init__','__main__','__str__'],0],
['Encapsulamento','Organize estado e comportamento dentro das classes.','Encapsular ajuda principalmente a:',['Organizar responsabilidades','Aumentar o monitor','Instalar Python'],0],
['Refatoração','Melhore estrutura sem alterar o comportamento esperado.','Refatorar significa:',['Melhorar código preservando comportamento','Apagar testes','Trocar linguagem'],0],
['Projeto Python POO','Modele Aluno, Turma e Curso usando classes.','Antes de programar classes, faça o quê?',['Identifique responsabilidades','Copie código','Ignore dados'],0],
['Java: começo','Java usa JDK para compilar e executar projetos.','Qual kit usamos para desenvolver Java?',['JDK','CSS','SQL'],0],
['Java: saída','System.out.println imprime uma linha.','Qual imprime em Java?',['System.out.println','print','console.log'],0],
['Java: tipos','Java declara tipos como int, double e boolean.','Qual representa inteiro?',['int','String','double'],0],
['Java: entrada','Scanner pode receber dados do teclado.','Qual classe é comum para entrada inicial?',['Scanner','Printer','ReaderUI'],0],
['Java: condições','Java também usa if/else.','Qual palavra representa alternativa?',['else','elif','otherwise'],0],
['Java: switch','switch seleciona casos.','Qual palavra identifica um caso?',['case','when','option'],0],
['Java: for','for pode repetir com contador.','Qual é um laço?',['for','package','public'],0],
['Java: while','while repete por condição.','Qual palavra cria repetição condicional?',['while','static','void'],0],
['Java: arrays','Arrays guardam elementos do mesmo tipo.','Qual sintaxe indica array de int?',['int[]','int{}','array<int>'],0],
['Java: métodos','Métodos agrupam comportamento reutilizável.','Qual palavra indica ausência de retorno?',['void','null','empty'],0],
['Java: classes','class define um novo tipo.','Qual palavra cria classe?',['class','def','structonly'],0],
['Java: objetos','new cria instâncias.','Qual palavra instancia um objeto?',['new','make','create'],0],
['Java: construtores','Construtores preparam o objeto.','O construtor tem normalmente o mesmo nome da:',['classe','variável','interface'],0],
['Java: encapsulamento','private restringe acesso direto.','Qual modificador restringe acesso?',['private','public','open'],0],
['Java: herança','extends cria relação de herança entre classes.','Qual palavra indica herança?',['extends','inherits','superclass'],0],
['Java: polimorfismo','Uma referência pode trabalhar com diferentes implementações compatíveis.','Polimorfismo está ligado a:',['múltiplas formas','arquivos','DNS'],0],
['Java: interfaces','interface define contratos de comportamento.','Uma interface descreve principalmente:',['contrato','banco','terminal'],0],
['Java: coleções','ArrayList é uma coleção dinâmica.','Qual coleção é dinâmica?',['ArrayList','int[] fixo','String'],0],
['Java: Map e Set','Map usa chave/valor; Set evita duplicatas.','Qual evita duplicatas?',['Set','Map','String'],0],
['Java: exceções','try/catch trata exceções em Java.','Qual bloco captura a exceção?',['catch','except','rescue'],0],
['Git','Git registra versões do projeto.','Qual comando inicia repositório?',['git init','git start','git new'],0],
['Commits','Um commit registra um ponto do histórico.','Qual comando prepara arquivo?',['git add','git push','git clone'],0],
['GitHub','GitHub hospeda repositórios remotos.','Git e GitHub são:',['Ferramentas relacionadas, mas diferentes','A mesma coisa','Linguagens'],0],
['Branches','Branches permitem linhas paralelas de trabalho.','Qual branch costuma ser principal?',['main','temp','cache'],0],
['HTML','HTML estrutura o conteúdo da página.','Qual tag representa parágrafo?',['<p>','<css>','<js>'],0],
['CSS','CSS controla apresentação visual.','Qual propriedade altera tamanho da fonte?',['font-size','text-code','html-size'],0],
['Flexbox','Flexbox organiza elementos em um eixo principal.','Qual ativa flexbox?',['display:flex','position:flex','flex:true'],0],
['Responsividade','Layouts devem se adaptar a telas diferentes.','Qual recurso CSS ajuda nisso?',['media queries','SQL','pip'],0],
['JavaScript','JavaScript adiciona comportamento à interface.','Qual declaração moderna cria constante?',['const','constant','fixed'],0],
['DOM','DOM representa o documento para o JavaScript.','Qual busca um elemento por seletor?',['querySelector','print','SELECT'],0],
['Eventos','Eventos respondem a ações como clique.','Qual método registra evento?',['addEventListener','addClickSQL','listenPython'],0],
['Formulários','Valide dados e forneça feedback claro.','placeholder substitui label?',['Não','Sim','Sempre'],0],
['React','React organiza interfaces em componentes.','Qual conceito é central no React?',['componentes','tabelas SQL','DNS'],0],
['JSX','JSX combina marcação e expressões JavaScript.','JSX é usado principalmente em:',['React','MySQL','Linux'],0],
['Props','Props passam dados para componentes.','Props servem para:',['passar dados','criar banco','compilar Java'],0],
['State','State representa dados que mudam na interface.','Qual hook básico gerencia estado?',['useState','useSQL','usePython'],0],
['Hooks','Hooks adicionam recursos a componentes funcionais.','Qual hook trata efeitos?',['useEffect','usePrint','useRouteSQL'],0],
['Rotas React','Rotas permitem diferentes telas no front-end.','Rotas alteram principalmente:',['visão/tela','CPU','JDK'],0],
['HTTP','HTTP organiza comunicação entre cliente e servidor.','Qual método normalmente consulta recurso?',['GET','POST','DELETE'],0],
['Request/Response','Cliente envia request e servidor devolve response.','Quem devolve response?',['servidor','teclado','CSS'],0],
['REST','REST modela recursos e operações via HTTP.','REST é principalmente:',['estilo arquitetural','banco','linguagem'],0],
['JSON em APIs','APIs frequentemente trocam JSON.','JSON é:',['formato de dados','framework','sistema operacional'],0],
['FastAPI','FastAPI cria APIs em Python.','Qual linguagem usamos com FastAPI aqui?',['Python','Java','CSS'],0],
['Rotas FastAPI','Decoradores associam funções a endpoints.','Qual exemplo representa GET?',['@app.get','@app.css','@app.sql'],0],
['Pydantic','Modelos validam dados recebidos.','Validação ajuda a:',['verificar estrutura dos dados','mudar monitor','criar DNS'],0],
['CRUD','CRUD = criar, ler, atualizar e excluir.','Qual letra representa Read?',['R','C','D'],0],
['SQL','SQL consulta e modifica bancos relacionais.','Qual comando consulta dados?',['SELECT','PRINT','FETCHJS'],0],
['Tabelas','Tabelas possuem linhas e colunas.','Uma linha representa normalmente:',['registro','CSS','servidor'],0],
['Chaves','PK identifica registros; FK relaciona tabelas.','Qual identifica registro de forma única?',['PK','FK','HTTP'],0],
['JOIN','JOIN combina dados relacionados.','Qual JOIN retorna correspondências entre tabelas?',['INNER JOIN','PRINT JOIN','CSS JOIN'],0],
['Python + Banco','Back-end conecta regras da aplicação aos dados.','Credenciais devem ficar:',['fora do código público','no HTML','no README público'],0],
['Full Stack','Front-end, API e banco trabalham juntos.','React conversa com FastAPI por:',['HTTP/API','HDMI','CSS'],0],
['Redes','IP identifica interfaces em redes.','Qual protocolo resolve nomes?',['DNS','CSS','SQL'],0],
['TCP/IP','TCP fornece transporte confiável orientado a conexão.','Qual é protocolo de transporte?',['TCP','HTML','JSON'],0],
['Linux','Terminal permite administrar arquivos e processos.','Qual comando muda diretório?',['cd','mvdirto','goto'],0],
['Permissões','Permissões controlam leitura, escrita e execução.','Qual comando altera permissões?',['chmod','pip','git add'],0],
['Deploy','Deploy disponibiliza uma aplicação em ambiente de execução.','Deploy significa:',['colocar aplicação em operação','apagar código','criar variável'],0],
['DNS','DNS liga nomes a endereços.','Domínio é resolvido por:',['DNS','React','Java'],0],
['Segurança','Segurança inclui autenticação, autorização e boas práticas.','Senha deve ser armazenada como:',['hash adequado','texto puro','comentário'],0],
['Criptografia','Criptografia protege confidencialidade e integridade conforme o mecanismo.','HTTPS usa proteção baseada em:',['TLS','CSS','SQL'],0],
['Projeto final','Integre front-end, API, banco, testes e deploy.','Primeiro passo de um projeto final?',['definir requisitos','programar sem plano','ignorar segurança'],0]
];
window.DEVQUEST_TOPICS=topics;
if (typeof globalThis !== 'undefined') globalThis.DEVQUEST_TOPICS=topics;
})();